#!/usr/bin/env python3
"""Audit handbook chapter coverage. Generates COVERAGE.md when run without --strict."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def has_csharp(text: str) -> bool:
    return bool(re.search(r"```(?:csharp|cs)\b", text, re.I))


def has_go(text: str) -> bool:
    return bool(re.search(r"```go\b", text))


def has_stub_code(text: str) -> bool:
    for block in re.findall(r"```(?:csharp|cs|go)\n(.*?)```", text, re.S | re.I):
        if "..." in block and "append(" not in block:
            return True
    return False


def has_complexity(text: str) -> bool:
    return bool(re.search(r"Big O|O\(|complexity|Time:|Space:", text, re.I))


def has_problem(text: str) -> bool:
    return bool(re.search(r"Problem|Canonical|Motivat", text, re.I))


def has_realworld(text: str) -> bool:
    return bool(re.search(r"Real[- ]?World|Production|Redis|PostgreSQL|\.NET", text, re.I))


def has_diagram(text: str) -> bool:
    return bool(re.search(r"!\[.*\]\(/images/", text))


def has_project_tip(text: str) -> bool:
    return "::: tip Project Lab" in text


def has_quiz_callout(text: str) -> bool:
    return "::: tip Quizzes & Challenges" in text


def load_quiz_page_paths() -> set[str]:
    topics_dir = ROOT / "quizzes" / "topics"
    paths: set[str] = set()
    if not topics_dir.exists():
        return paths
    for path in sorted(topics_dir.glob("*.ts")):
        text = read_text(path)
        match = re.search(r"pagePath:\s*'([^']+)'", text)
        if match:
            paths.add(match.group(1))
    return paths


def page_path_for_row(section: str, folder: str, filename: str) -> str:
    return f"/{folder}/{Path(filename).stem}"


def read_examples_index() -> str:
    p = ROOT / "examples" / "README.md"
    return p.read_text(encoding="utf-8") if p.exists() else ""


def chapter_rows() -> list[dict]:
    rows = []
    quiz_paths = load_quiz_page_paths()
    sections = [
        ("Fundamentals", "fundamentals"),
        ("Data Structures", "data-structures"),
        ("Algorithms", "algorithms"),
    ]
    for section, folder in sections:
        for path in sorted((ROOT / folder).glob("*.md")):
            text = read_text(path)
            slug = path.stem
            page_path = page_path_for_row(section, folder, path.name)
            rows.append(
                {
                    "section": section,
                    "topic": slug,
                    "path": f"{folder}/{path.name}",
                    "page_path": page_path,
                    "concept": len(text.splitlines()) >= 40,
                    "csharp": has_csharp(text),
                    "go": has_go(text),
                    "complexity": has_complexity(text),
                    "problem": has_problem(text),
                    "realworld": has_realworld(text),
                    "diagram": has_diagram(text),
                    "example": slug.replace("-", "_") in read_examples_index(),
                    "project": has_project_tip(text),
                    "quiz": page_path in quiz_paths,
                    "quiz_callout": has_quiz_callout(text),
                    "stub": has_stub_code(text),
                    "lines": len(text.splitlines()),
                }
            )
    return rows


def render_coverage_md(rows: list[dict]) -> str:
    def yn(v: bool) -> str:
        return "Y" if v else "N"

    lines = [
        "# Handbook Coverage Matrix",
        "",
        "Auto-generated by `scripts/audit_coverage.py`. Re-run `npm run verify:coverage` after chapter edits.",
        "",
        "| Section | Topic | C# | Go | Cx | Problem | RealWorld | Diagram | Example | Project | Quiz | Callout | Lines |",
        "|---------|-------|----|----|----|---------|-----------|---------|---------|---------|------|---------|-------|",
    ]
    for r in rows:
        lines.append(
            f"| {r['section']} | {r['topic']} | {yn(r['csharp'])} | {yn(r['go'])} | {yn(r['complexity'])} | "
            f"{yn(r['problem'])} | {yn(r['realworld'])} | {yn(r['diagram'])} | {yn(r['example'])} | "
            f"{yn(r['project'])} | {yn(r['quiz'])} | {yn(r['quiz_callout'])} | {r['lines']} |"
        )

    total = len(rows)
    cs = sum(1 for r in rows if r["csharp"])
    go = sum(1 for r in rows if r["go"])
    both = sum(1 for r in rows if r["csharp"] and r["go"])
    stubs = [r for r in rows if r["stub"]]
    quiz_cov = sum(1 for r in rows if r["quiz"])
    callout_cov = sum(1 for r in rows if r["quiz_callout"])

    lines.extend(
        [
            "",
            "## Summary",
            "",
            f"- **Chapters:** {total}",
            f"- **With C#:** {cs}/{total}",
            f"- **With Go:** {go}/{total}",
            f"- **With both:** {both}/{total}",
            f"- **With quiz pack:** {quiz_cov}/{total}",
            f"- **With quiz callout:** {callout_cov}/{total}",
            f"- **Stub code blocks:** {len(stubs)}",
            "",
        ]
    )
    if stubs:
        lines.append("### Stub warnings")
        for r in stubs:
            lines.append(f"- `{r['path']}`")
        lines.append("")
    return "\n".join(lines)


def strict_check(rows: list[dict]) -> list[str]:
    errors = []
    for r in rows:
        if r["section"] == "Fundamentals":
            continue
        if not r["csharp"]:
            errors.append(f"{r['path']}: missing C#")
        if not r["go"]:
            errors.append(f"{r['path']}: missing Go")
        if r["stub"]:
            errors.append(f"{r['path']}: stub code block")
        if r["section"] == "Algorithms" and not r["complexity"]:
            if r["topic"] == "08-pseudocode-binary-search":
                continue
            errors.append(f"{r['path']}: missing complexity")
        if not r["quiz"]:
            errors.append(f"{r['path']}: missing quiz pack")
        if not r["quiz_callout"]:
            errors.append(f"{r['path']}: missing quiz callout")
    for r in rows:
        if r["section"] != "Fundamentals":
            continue
        if not r["quiz"]:
            errors.append(f"{r['path']}: missing quiz pack")
        if not r["quiz_callout"]:
            errors.append(f"{r['path']}: missing quiz callout")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--write", action="store_true", help="Write COVERAGE.md")
    args = parser.parse_args()

    rows = chapter_rows()
    content = render_coverage_md(rows)

    if args.write or not args.strict:
        (ROOT / "COVERAGE.md").write_text(content, encoding="utf-8")

    if args.strict:
        errors = strict_check(rows)
        if errors:
            print("Coverage audit FAILED:")
            for e in errors:
                print(f"  - {e}")
            return 1
        print(f"Coverage audit passed ({len(rows)} chapters).")
        return 0

    print(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())