import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/43-aho-corasick',
  topicId: 'aho-corasick',
  title: 'Aho-Corasick',
  quiz: [
    {
      id: 'ac-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Aho-Corasick solves:',
      options: [
        { id: 'a', text: 'Multiple pattern matching in one text scan' },
        { id: 'b', text: 'Single pattern matching only' },
        { id: 'c', text: 'Sorting k strings' },
        { id: 'd', text: 'Matrix multiplication order' },
      ],
      correct: ['a'],
      explanation: 'Build one automaton from all patterns; search text in a single pass.',
    },
    {
      id: 'ac-q2',
      type: 'mcq',
      difficulty: 'medium',
      question: 'Failure links in Aho-Corasick are built using:',
      options: [
        { id: 'a', text: 'BFS from trie root — KMP LPS generalized to a trie' },
        { id: 'b', text: 'DFS post-order only' },
        { id: 'c', text: 'Random hashing' },
        { id: 'd', text: 'Bubble sort on patterns' },
      ],
      correct: ['a'],
      explanation: 'BFS assigns fail pointers like KMP borders for every trie node.',
    },
    {
      id: 'ac-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Output links collect patterns ending at a node plus patterns from failure targets.',
      correct: true,
      explanation: 'child.Output.AddRange(child.Fail.Output) ensures overlapping matches are reported.',
    },
    {
      id: 'ac-q4',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Search phase complexity for text length n with k total pattern occurrences z:',
      options: [
        { id: 'a', text: 'O(n + z)' },
        { id: 'b', text: 'O(n × k)' },
        { id: 'c', text: 'O(k²)' },
        { id: 'd', text: 'O(n²)' },
      ],
      correct: ['a'],
      explanation: 'Linear text scan; reporting z matches adds O(z). Preprocessing is paid once.',
    },
    {
      id: 'ac-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Antivirus scans a file for 10,000 virus signatures. Why Aho-Corasick over KMP×k?',
      options: [
        { id: 'a', text: 'O(n) per file vs O(n × k) — essential at scale' },
        { id: 'b', text: 'KMP cannot find overlaps' },
        { id: 'c', text: 'Aho-Corasick uses less memory than one KMP' },
        { id: 'd', text: 'KMP only works on DNA' },
      ],
      correct: ['a'],
      explanation: 'One automaton scan vs thousands of separate passes — the production difference.',
    },
    {
      id: 'ac-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'Patterns ["he","she","his","hers"] on "ushers" demonstrate ___ matches.',
      correct: ['overlapping', 'overlap'],
      aliases: ['overlapped'],
      explanation: 'Multiple patterns can end at/near the same text positions — AC reports all.',
    },
    {
      id: 'ac-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Aho-Corasick components? (Select all)',
      options: [
        { id: 'a', text: 'Trie of all patterns' },
        { id: 'b', text: 'Failure links' },
        { id: 'c', text: 'Output links / output lists at nodes' },
        { id: 'd', text: 'Rolling hash per window' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Trie + fail + output — no hashing required; deterministic automaton.',
    },
    {
      id: 'ac-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'During search, when no edge for char c exists, what happens?',
      code: `while (node != _root && !node.Children.ContainsKey(c))
    node = node.Fail!;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Follow failure links until a transition for c exists or return to root' },
        { id: 'b', text: 'Restart text from index 0' },
        { id: 'c', text: 'Abort search' },
        { id: 'd', text: 'Hash the remaining text' },
      ],
      correct: ['a'],
      explanation: 'Failure links are the multi-pattern analogue of KMP shifting on mismatch.',
    },
  ],
  challenges: [
    {
      id: 'ac-c1',
      type: 'scenario',
      difficulty: 'medium',
      question: 'k=10,000 patterns, text length n=1M. Naive KMP per pattern visits roughly:',
      options: [
        { id: 'a', text: 'O(n × k) ≈ 10 billion character steps' },
        { id: 'b', text: 'O(n + k)' },
        { id: 'c', text: 'O(log n)' },
        { id: 'd', text: 'O(k)' },
      ],
      correct: ['a'],
      explanation: 'Chapter example: separate KMP runs multiply text work by pattern count.',
    },
    {
      id: 'ac-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'Content moderation must flag any of hundreds of banned phrases in streaming logs. Best fit?',
      options: [
        { id: 'a', text: 'Build Aho-Corasick once; scan each log line in O(line length)' },
        { id: 'b', text: 'Regex catastrophic backtracking on combined pattern' },
        { id: 'c', text: 'Sort phrases and binary search each word' },
        { id: 'd', text: 'Levenshtein against every phrase per character' },
      ],
      correct: ['a'],
      explanation: 'Multi-pattern keyword filtering at scale is a textbook Aho-Corasick use case.',
    },
  ],
} satisfies QuizPack