import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/21-bst-operations',
  topicId: 'bst-operations',
  title: 'BST Operations',
  quiz: [
    {
      id: 'bst-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'How do you find the k-th smallest element in a BST?',
      options: [
        { id: 'a', text: 'Inorder traversal (left → root → right), stop at k' },
        { id: 'b', text: 'Level-order BFS' },
        { id: 'c', text: 'Preorder traversal only' },
        { id: 'd', text: 'Reverse the tree' },
      ],
      correct: ['a'],
      explanation: 'Inorder visits BST nodes in sorted order; count until you reach k.',
    },
    {
      id: 'bst-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Average-case time for BST search when the tree is balanced:',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['b'],
      explanation: 'Balanced BST height is O(log n); search follows one root-to-leaf path.',
    },
    {
      id: 'bst-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Checking only parent < child < grandchild is sufficient to validate a BST.',
      correct: false,
      explanation: 'BST invariant applies to entire subtrees — a node must be within (min, max) bounds passed down from ancestors.',
    },
    {
      id: 'bst-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'In a BST, find LCA of nodes with values 3 and 9. Current node is 6. Where do you go next?',
      options: [
        { id: 'a', text: 'Return 6 — it is the LCA' },
        { id: 'b', text: 'Go left' },
        { id: 'c', text: 'Go right' },
        { id: 'd', text: 'Go to parent' },
      ],
      correct: ['a'],
      explanation: '3 < 6 and 9 > 6 — one target is left, one is right. Current node is the split point = LCA.',
    },
    {
      id: 'bst-q5',
      type: 'mcq',
      difficulty: 'hard',
      question: 'When deleting a BST node with two children, the standard approach is:',
      options: [
        { id: 'a', text: 'Replace value with inorder successor (min of right subtree), then delete successor' },
        { id: 'b', text: 'Delete both subtrees' },
        { id: 'c', text: 'Swap with parent always' },
        { id: 'd', text: 'Convert to linked list first' },
      ],
      correct: ['a'],
      explanation: 'Copying the successor value preserves BST order; then delete the successor node (which has ≤1 child).',
    },
    {
      id: 'bst-q6',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What does this BST validation check enforce?',
      code: `if (node.Val <= min || node.Val >= max) return false;
return Validate(node.Left, min, node.Val)
    && Validate(node.Right, node.Val, max);`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Every node lies strictly between inherited min/max bounds' },
        { id: 'b', text: 'Tree is perfectly balanced' },
        { id: 'c', text: 'No duplicate values allowed ever' },
        { id: 'd', text: 'Parent is always the median' },
      ],
      correct: ['a'],
      explanation: 'Bounds tighten as you descend: left subtree max becomes node.Val, right subtree min becomes node.Val.',
    },
    {
      id: 'bst-q7',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Insert in a BST follows the same path as search, adding a new leaf when null is reached.',
      correct: true,
      explanation: 'Compare val to root: go left if smaller, right if larger; create node at the null child position.',
    },
    {
      id: 'bst-q8',
      type: 'complexity',
      difficulty: 'hard',
      question: 'Worst-case height of a BST built from sorted ascending input:',
      options: [
        { id: 'a', text: 'O(log n)' },
        { id: 'b', text: 'O(n)' },
        { id: 'c', text: 'O(1)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['b'],
      explanation: 'Sorted insertions create a right-skewed chain — degenerates to a linked list, O(n) per operation.',
    },
  ],
  challenges: [
    {
      id: 'bst-c1',
      type: 'trace',
      difficulty: 'hard',
      question: 'BST: root=8, left=3 (with children 1,6), right=10 (with child 14). Kth smallest with k=4?',
      options: [
        { id: 'a', text: '8' },
        { id: 'b', text: '6' },
        { id: 'c', text: '10' },
        { id: 'd', text: '3' },
      ],
      correct: ['a'],
      explanation: 'Inorder: 1, 3, 6, 8, 10, 14. The 4th smallest (k=4) is 8.',
    },
    {
      id: 'bst-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement BST LCA: given root and two TreeNode references p and q, return their lowest common ancestor using BST ordering.',
      rubric: [
        'If both p and q values are less than root, recurse left',
        'If both are greater than root, recurse right',
        'Otherwise root is the LCA (split point)',
        'Handle null root appropriately',
        'O(h) time — no full tree scan needed',
      ],
      explanation: 'BST ordering makes LCA a simple descent. Test with root=6, p=2, q=8 → LCA is 6.',
    },
  ],
} satisfies QuizPack