import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/12-merge-sort',
  topicId: 'merge-sort',
  title: 'Merge Sort',
  quiz: [
    {
      id: 'ms-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Which paradigm does merge sort use?',
      options: [
        { id: 'a', text: 'Divide and conquer' },
        { id: 'b', text: 'Greedy' },
        { id: 'c', text: 'Dynamic programming' },
        { id: 'd', text: 'Backtracking' },
      ],
      correct: ['a'],
      explanation: 'Split in half, sort each half recursively, merge sorted halves.',
    },
    {
      id: 'ms-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'Worst-case time complexity of merge sort:',
      options: [
        { id: 'a', text: 'O(n)' },
        { id: 'b', text: 'O(n log n)' },
        { id: 'c', text: 'O(n²)' },
        { id: 'd', text: 'O(2^n)' },
      ],
      correct: ['b'],
      explanation: 'Always divides log n levels, each level does O(n) merge work — guaranteed O(n log n).',
    },
    {
      id: 'ms-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Merge sort is a stable sorting algorithm.',
      correct: true,
      explanation: 'When merging, take from left first if equal — preserves relative order of equal elements.',
    },
    {
      id: 'ms-q4',
      type: 'mcq',
      difficulty: 'medium',
      question: 'Main space disadvantage of standard merge sort vs in-place quicksort:',
      options: [
        { id: 'a', text: 'Requires O(n) auxiliary space for merging' },
        { id: 'b', text: 'Requires O(n²) space' },
        { id: 'c', text: 'Cannot sort integers' },
        { id: 'd', text: 'Uses recursion so no extra space' },
      ],
      correct: ['a'],
      explanation: 'Typical implementation copies into temp arrays during merge.',
    },
    {
      id: 'ms-q5',
      type: 'ordering',
      difficulty: 'medium',
      question: 'Merge sort on [38, 27, 43, 3]. Order the merge steps (top-level merge last):',
      items: [
        { id: 'a', text: 'Split into [38,27] and [43,3]' },
        { id: 'b', text: 'Merge [27,38] and [3,43]' },
        { id: 'c', text: 'Final merge to [3,27,38,43]' },
        { id: 'd', text: 'Split [38,27] into [38] and [27]' },
      ],
      correct: ['d', 'a', 'b', 'c'],
      explanation: 'Divide fully, then merge up: singles → pairs → final.',
    },
    {
      id: 'ms-q6',
      type: 'scenario',
      difficulty: 'medium',
      question: 'You need guaranteed O(n log n) for sorting 50M records on disk (external sort). Why merge sort?',
      options: [
        { id: 'a', text: 'Predictable performance + merges map well to sequential disk reads' },
        { id: 'b', text: 'Merge sort is always in-place on disk' },
        { id: 'c', text: 'Quicksort has no worst case' },
        { id: 'd', text: 'Bubble sort is faster at scale' },
      ],
      correct: ['a'],
      explanation: 'External merge sort is the classic large-file sorting approach.',
    },
    {
      id: 'ms-q7',
      type: 'fill-blank',
      difficulty: 'hard',
      question: 'The merge step of two sorted halves of total size n takes O(___) time.',
      correct: ['n', 'O(n)', 'o(n)'],
      aliases: ['linear'],
      explanation: 'Each element is compared and placed once — linear in combined size.',
    },
    {
      id: 'ms-q8',
      type: 'code-analysis',
      difficulty: 'medium',
      question: 'What happens if merge always takes from right when arr[i] == arr[j]?',
      code: `if (arr[i] <= arr[j]) out.push(arr[i++]);
else out.push(arr[j++]);`,
      codeLang: 'pseudocode',
      options: [
        { id: 'a', text: 'Stability is preserved (left taken first on equal)' },
        { id: 'b', text: 'Stability is broken for equal elements' },
        { id: 'c', text: 'Sort becomes O(n²)' },
        { id: 'd', text: 'Infinite loop' },
      ],
      correct: ['a'],
      explanation: 'Taking from left on <= preserves original left-half order for equal keys.',
    },
  ],
  challenges: [
    {
      id: 'ms-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Merge [3, 27, 38] with [9, 10, 82]. What is the first 3 elements of the result?',
      options: [
        { id: 'a', text: '[3, 9, 10]' },
        { id: 'b', text: '[3, 27, 38]' },
        { id: 'c', text: '[9, 10, 27]' },
        { id: 'd', text: '[3, 27, 9]' },
      ],
      correct: ['a'],
      explanation: '3 < 9, then 9 < 27, then 10 < 27 → [3, 9, 10, ...].',
    },
    {
      id: 'ms-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'Linked list sort: why merge sort is preferred over quicksort?',
      options: [
        { id: 'a', text: 'Merge sort can run in O(1) extra space with pointer rewiring and O(n log n) time' },
        { id: 'b', text: 'Quicksort needs random access which linked lists lack efficiently' },
        { id: 'c', text: 'Both a and b' },
        { id: 'd', text: 'Linked lists cannot be sorted' },
      ],
      correct: ['c'],
      explanation: 'No random access hurts quicksort\'s partition; merge sort only needs sequential access.',
    },
  ],
} satisfies QuizPack