import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/39-kmp',
  topicId: 'kmp',
  title: 'Knuth-Morris-Pratt (KMP)',
  quiz: [
    {
      id: 'kmp-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What does the LPS array encode for pattern P?',
      options: [
        { id: 'a', text: 'Longest proper prefix of P[0..i] that is also a suffix' },
        { id: 'b', text: 'Longest substring of P' },
        { id: 'c', text: 'Number of occurrences in text' },
        { id: 'd', text: 'Hash of each prefix' },
      ],
      correct: ['a'],
      explanation: 'LPS[i] tells how far to shift the pattern on mismatch without rescanning text.',
    },
    {
      id: 'kmp-q2',
      type: 'trace',
      difficulty: 'medium',
      question: 'P = "ABABCABAB". What is LPS[7]?',
      options: [
        { id: 'a', text: '3' },
        { id: 'b', text: '4' },
        { id: 'c', text: '2' },
        { id: 'd', text: '0' },
      ],
      correct: ['a'],
      explanation: 'Prefix "ABA" (length 3) matches suffix of P[0..7] — LPS[7] = 3.',
    },
    {
      id: 'kmp-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'KMP never moves the text pointer backward during search.',
      correct: true,
      explanation: 'On mismatch, only the pattern index jumps via LPS; i only increases over time.',
    },
    {
      id: 'kmp-q4',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Total KMP time for text length n and pattern length m:',
      options: [
        { id: 'a', text: 'O(n + m)' },
        { id: 'b', text: 'O(n × m)' },
        { id: 'c', text: 'O(n log m)' },
        { id: 'd', text: 'O(m²)' },
      ],
      correct: ['a'],
      explanation: 'LPS build O(m) + single-pass search O(n) = linear total.',
    },
    {
      id: 'kmp-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Naive matching is O(n×m) on T="aaa…ab", P="aaa…ab". Why does KMP win here?',
      options: [
        { id: 'a', text: 'LPS reuses matched prefix overlap instead of restarting comparisons' },
        { id: 'b', text: 'KMP hashes the pattern' },
        { id: 'c', text: 'KMP scans right-to-left' },
        { id: 'd', text: 'KMP skips characters probabilistically' },
      ],
      correct: ['a'],
      explanation: 'Repeated partial matches are the worst case for naive; KMP shifts intelligently via LPS.',
    },
    {
      id: 'kmp-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'After a full match at pattern index j == m, KMP sets j = LPS[j - 1] to find ___ matches.',
      correct: ['overlapping', 'overlap'],
      aliases: ['overlapped', 'further'],
      explanation: 'The suffix-prefix overlap may allow another match starting inside the just-matched region.',
    },
    {
      id: 'kmp-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'KMP advantages vs other matchers? (Select all)',
      options: [
        { id: 'a', text: 'Deterministic O(n + m) worst case' },
        { id: 'b', text: 'No hash collisions' },
        { id: 'c', text: 'Best average-case speed on long English text' },
        { id: 'd', text: 'LPS ideas generalize to Aho-Corasick failure links' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'Boyer-Moore often wins on natural language; KMP guarantees linear time deterministically.',
    },
    {
      id: 'kmp-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'On mismatch with j > 0, why set j = lps[j-1] instead of j = 0?',
      code: `} else if (j > 0) {
    j = lps[j - 1];
}`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Reuse the longest proper prefix that is also a suffix of the matched portion' },
        { id: 'b', text: 'Restart guarantees fewer comparisons' },
        { id: 'c', text: 'Move text pointer back one step' },
        { id: 'd', text: 'Skip building LPS' },
      ],
      correct: ['a'],
      explanation: 'This is the core KMP insight — border reuse avoids redundant re-comparison.',
    },
  ],
  challenges: [
    {
      id: 'kmp-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'P = "AABA". What is the full LPS array (indices 0..3)?',
      options: [
        { id: 'a', text: '[0, 1, 0, 1]' },
        { id: 'b', text: '[0, 0, 1, 2]' },
        { id: 'c', text: '[0, 1, 2, 3]' },
        { id: 'd', text: '[0, 0, 0, 0]' },
      ],
      correct: ['a'],
      explanation: 'A→0, AA→1, AAB→0 (no border), AABA→1 ("A" prefix = suffix).',
    },
    {
      id: 'kmp-c2',
      type: 'variant',
      difficulty: 'hard',
      question: 'SearchFirst for pattern in text. After SearchAll finds matches, first index is:',
      options: [
        { id: 'a', text: 'matches[0], or -1 if empty' },
        { id: 'b', text: 'Always 0' },
        { id: 'c', text: 'n - m' },
        { id: 'd', text: 'LPS[m-1]' },
      ],
      correct: ['a'],
      explanation: 'SearchAll records i - m on each full match; first element is earliest occurrence.',
    },
  ],
} satisfies QuizPack