import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/13-quicksort',
  topicId: 'quicksort',
  title: 'Quicksort',
  quiz: [
    {
      id: 'qs-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What are the three main steps of quicksort?',
      options: [
        { id: 'a', text: 'Pick pivot, partition, recursively sort left and right' },
        { id: 'b', text: 'Split in half, merge sorted halves, return' },
        { id: 'c', text: 'Build heap, extract max repeatedly' },
        { id: 'd', text: 'Count digits, stable place, repeat per digit' },
      ],
      correct: ['a'],
      explanation: 'Divide-and-conquer via partitioning — the combine step is free because pivot lands in final position.',
    },
    {
      id: 'qs-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Worst-case time complexity of quicksort with naive last-element pivot on already-sorted input:',
      options: [
        { id: 'a', text: 'O(n log n)' },
        { id: 'b', text: 'O(n²)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(log n)' },
      ],
      correct: ['b'],
      explanation: 'Last-element pivot on sorted data gives unbalanced partitions of size n-1 and 0 — quadratic recursion.',
    },
    {
      id: 'qs-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Quicksort sorts in place with O(log n) average stack depth.',
      correct: true,
      explanation: 'Chapter table: average O(n log n) time, O(log n) stack; partitioning uses constant extra space.',
    },
    {
      id: 'qs-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Millions of integers in RAM; you want in-place speed and good cache locality. Why is quicksort a top pick?',
      options: [
        { id: 'a', text: 'In-place partitioning with excellent average-case performance and cache-friendly access' },
        { id: 'b', text: 'Guaranteed O(n log n) worst case without any fallback' },
        { id: 'c', text: 'O(1) extra memory like merge sort' },
        { id: 'd', text: 'Stable sort preserving duplicate order' },
      ],
      correct: ['a'],
      explanation: 'Canonical chapter problem: large in-memory arrays where merge sort’s O(n) extra space is costly.',
    },
    {
      id: 'qs-q5',
      type: 'trace',
      difficulty: 'hard',
      question: 'Lomuto partition on [3, 6, 8, 10, 1, 2, 1] with pivot = last element (1). What index does partition return?',
      options: [
        { id: 'a', text: '0' },
        { id: 'b', text: '3' },
        { id: 'c', text: '6' },
        { id: 'd', text: '4' },
      ],
      correct: ['a'],
      explanation: 'Pivot 1 is smallest; Lomuto places it at index 0 after swapping through the partition loop.',
    },
    {
      id: 'qs-q6',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'In Lomuto partition, elements ___ pivot end up left of the pivot’s final position.',
      correct: ['<', 'less than', 'smaller than'],
      explanation: 'Scan j from lo to hi-1; when arr[j] < pivot, swap into the growing left region tracked by i.',
    },
    {
      id: 'qs-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Production robustness techniques for quicksort include: (Select all that apply)',
      options: [
        { id: 'a', text: 'Random pivot selection' },
        { id: 'b', text: '3-way (Dutch National Flag) partition for many duplicates' },
        { id: 'c', text: 'Median-of-three pivot' },
        { id: 'd', text: 'Always use first element as pivot on sorted inputs' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Chapter warns naive last-element pivot on sorted data → O(n²). Random/3-way/median-of-three mitigate this.',
    },
    {
      id: 'qs-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'Why is there no explicit merge/combine step after recursive calls?',
      code: `int p = Partition(arr, lo, hi);
QuickSort(arr, lo, p - 1);
QuickSort(arr, p + 1, hi);`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Partitioning already places pivot correctly; subarrays are sorted independently' },
        { id: 'b', text: 'A hidden merge happens in the stack frame' },
        { id: 'c', text: 'The array is copied to auxiliary storage each level' },
        { id: 'd', text: 'Quicksort is not actually recursive' },
      ],
      correct: ['a'],
      explanation: 'Key insight from the chapter: partition is the combine — pivot is in final position when subcalls finish.',
    },
  ],
  challenges: [
    {
      id: 'qs-c1',
      type: 'variant',
      difficulty: 'hard',
      question: '3-way partition (Dutch National Flag) helps when:',
      options: [
        { id: 'a', text: 'Many duplicate pivot values would otherwise cause O(n²) with 2-way partition' },
        { id: 'b', text: 'The input must be stable' },
        { id: 'c', text: 'Keys are integers in range 0–150 only' },
        { id: 'd', text: 'The array is stored on disk' },
      ],
      correct: ['a'],
      explanation: 'Chapter’s 3-way variant groups <, =, > pivot in one pass — essential for duplicate-heavy inputs.',
    },
    {
      id: 'qs-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement Lomuto quicksort (partition + recursive sort). Sort a small random array and verify in-place ordering.',
      rubric: [
        'Base case: lo >= hi return',
        'Partition with pivot = arr[hi]',
        'Track i, scan j, swap smaller elements left',
        'Swap pivot into position i, return i',
        'Recurse on [lo, p-1] and [p+1, hi]',
      ],
      explanation: 'Core in-memory sorter — .NET Array.Sort uses introsort built on quicksort ideas.',
    },
  ],
} satisfies QuizPack