import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/26-dfs',
  topicId: 'dfs',
  title: 'DFS',
  quiz: [
    {
      id: 'dfs-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Which data structure drives depth-first exploration?',
      options: [
        { id: 'a', text: 'Stack (explicit or recursion call stack)' },
        { id: 'b', text: 'Queue (FIFO)' },
        { id: 'c', text: 'Min-heap only' },
        { id: 'd', text: 'Deque used only as queue' },
      ],
      correct: ['a'],
      explanation: 'DFS goes deep first — last discovered, first processed = stack behavior.',
    },
    {
      id: 'dfs-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Time complexity of DFS on a graph with V vertices and E edges:',
      options: [
        { id: 'a', text: 'O(V + E)' },
        { id: 'b', text: 'O(V²)' },
        { id: 'c', text: 'O(E log V)' },
        { id: 'd', text: 'O(V)' },
      ],
      correct: ['a'],
      explanation: 'Each vertex and edge visited at most once with proper visited tracking.',
    },
    {
      id: 'dfs-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'DFS can detect cycles in a directed graph by finding a back edge to a node on the recursion stack.',
      correct: true,
      explanation: 'White-gray-black (0/1/2) states: gray neighbor = back edge = cycle. BFS cannot detect directed cycles this cleanly.',
    },
    {
      id: 'dfs-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Count connected components in an undirected graph. Which approach?',
      options: [
        { id: 'a', text: 'DFS flood-fill from each unvisited node, increment counter' },
        { id: 'b', text: 'Dijkstra from every node' },
        { id: 'c', text: 'Sort edges by weight' },
        { id: 'd', text: 'Binary search on component count' },
      ],
      correct: ['a'],
      explanation: 'Each DFS from an unvisited node discovers one entire component — increment count per new flood.',
    },
    {
      id: 'dfs-q5',
      type: 'trace',
      difficulty: 'medium',
      question: 'Grid DFS for islands: cell visited by marking grid[r][c] = \'0\'. Why mark in-place?',
      options: [
        { id: 'a', text: 'Avoid separate visited array and prevent revisiting cells' },
        { id: 'b', text: 'Sort the grid' },
        { id: 'c', text: 'Compute shortest path' },
        { id: 'd', text: 'Required for Dijkstra' },
      ],
      correct: ['a'],
      explanation: 'Mutating visited cells (or a visited set) prevents infinite loops and double-counting islands.',
    },
    {
      id: 'dfs-q6',
      type: 'mcq',
      difficulty: 'hard',
      question: 'DFS vs BFS on a very wide but shallow graph — memory advantage often goes to:',
      options: [
        { id: 'a', text: 'DFS (stack depth vs BFS queue width)' },
        { id: 'b', text: 'BFS always' },
        { id: 'c', text: 'Neither uses memory' },
        { id: 'd', text: 'DFS uses O(V²) always' },
      ],
      correct: ['a'],
      explanation: 'BFS queue can hold an entire level (wide); DFS stack depth is tree height (shallow).',
    },
    {
      id: 'dfs-q7',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Iterative DFS with an explicit stack avoids recursion depth limits on very deep graphs.',
      correct: true,
      explanation: 'Recursion can overflow on deep grids/trees; explicit stack gives the same traversal with controlled memory.',
    },
    {
      id: 'dfs-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'In directed cycle detection, what does state[nei] == 1 mean?',
      code: `if (state[nei] == 1) return true;  // back edge`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Neighbor is currently on the DFS recursion stack (gray node)' },
        { id: 'b', text: 'Neighbor is fully processed (black)' },
        { id: 'c', text: 'Neighbor is unvisited (white)' },
        { id: 'd', text: 'Neighbor has indegree 0' },
      ],
      correct: ['a'],
      explanation: 'State 1 = on stack. An edge to an on-stack node is a back edge → cycle detected.',
    },
  ],
  challenges: [
    {
      id: 'dfs-c1',
      type: 'trace',
      difficulty: 'hard',
      question: 'Directed graph: 0→1, 1→2, 2→0. DFS from 0 with on-stack tracking. Cycle detected?',
      options: [
        { id: 'a', text: 'Yes — when visiting 2, neighbor 0 is on stack' },
        { id: 'b', text: 'No — DFS never finds cycles' },
        { id: 'c', text: 'Only if undirected' },
        { id: 'd', text: 'Only with BFS' },
      ],
      correct: ['a'],
      explanation: '0→1→2→0 forms a directed cycle. When DFS at 2 sees edge to 0 (state=1), back edge found.',
    },
    {
      id: 'dfs-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement CountIslands: given a 2D grid of \'1\' (land) and \'0\' (water), return number of connected land regions using DFS.',
      rubric: [
        'Iterate every cell; when grid[r][c] == \'1\', increment count',
        'DFS flood-fill: mark visited (set to \'0\'), explore 4 directions',
        'Bounds-check and skip water/already visited',
        'Return total island count',
        'O(rows × cols) time',
      ],
      explanation: 'Classic grid DFS. Test on [[1,1,0],[1,0,0],[0,0,1]] → 2 islands.',
    },
  ],
} satisfies QuizPack