import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/35-lcs',
  topicId: 'lcs',
  title: 'Longest Common Subsequence',
  quiz: [
    {
      id: 'lcs-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'X = "AGGTAB", Y = "GXTXAYB". What is the LCS length?',
      options: [
        { id: 'a', text: '4' },
        { id: 'b', text: '3' },
        { id: 'c', text: '5' },
        { id: 'd', text: '6' },
      ],
      correct: ['a'],
      explanation: 'One optimal LCS is "GTAB" — four characters in order, not necessarily contiguous.',
    },
    {
      id: 'lcs-q2',
      type: 'mcq',
      difficulty: 'medium',
      question: 'When X[i-1] == Y[j-1], the LCS recurrence is:',
      options: [
        { id: 'a', text: 'dp[i][j] = dp[i-1][j-1] + 1' },
        { id: 'b', text: 'dp[i][j] = max(dp[i-1][j], dp[i][j-1])' },
        { id: 'c', text: 'dp[i][j] = dp[i-1][j-1]' },
        { id: 'd', text: 'dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1])' },
      ],
      correct: ['a'],
      explanation: 'Matching characters extend the LCS diagonally from the previous prefix pair.',
    },
    {
      id: 'lcs-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'A subsequence must use contiguous characters from the original string.',
      correct: false,
      explanation: 'Subsequences preserve relative order but may skip characters; substrings must be contiguous.',
    },
    {
      id: 'lcs-q4',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Time and space of the standard 2D LCS DP for strings of lengths m and n:',
      options: [
        { id: 'a', text: 'O(m × n) time, O(m × n) space' },
        { id: 'b', text: 'O(m + n) time, O(1) space' },
        { id: 'c', text: 'O(m × n log n) time' },
        { id: 'd', text: 'O(2^m) time' },
      ],
      correct: ['a'],
      explanation: 'Fill an (m+1)×(n+1) table; two-row optimization reduces space to O(min(m,n)).',
    },
    {
      id: 'lcs-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Git diff tools use LCS-family algorithms primarily to:',
      options: [
        { id: 'a', text: 'Find unchanged regions between two versions of text' },
        { id: 'b', text: 'Compress files losslessly' },
        { id: 'c', text: 'Sort commit history' },
        { id: 'd', text: 'Hash passwords securely' },
      ],
      correct: ['a'],
      explanation: 'Diff highlights matching lines/tokens — the core insight is longest common subsequence on sequences.',
    },
    {
      id: 'lcs-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'When characters do not match, LCS takes the maximum of the cell ___ and the cell to the left.',
      correct: ['above', 'up', 'top'],
      aliases: ['upward', 'previous row'],
      explanation: 'dp[i][j] = max(dp[i-1][j], dp[i][j-1]) — best of dropping a char from X or from Y.',
    },
    {
      id: 'lcs-q7',
      type: 'mcq',
      difficulty: 'hard',
      question: 'Shortest common supersequence length for strings of lengths m, n with LCS length L:',
      options: [
        { id: 'a', text: 'm + n - L' },
        { id: 'b', text: 'm + n + L' },
        { id: 'c', text: 'max(m, n) - L' },
        { id: 'd', text: 'm × n - L' },
      ],
      correct: ['a'],
      explanation: 'Overlay the LCS once; remaining characters from each string are inserted around it.',
    },
    {
      id: 'lcs-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'During LCS reconstruction, when x[ii-1] == y[jj-1], what happens?',
      code: `if (x[ii - 1] == y[jj - 1]) {
    sb.Append(x[ii - 1]);
    ii--; jj--;
}`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'The matching character is part of the LCS; move diagonally' },
        { id: 'b', text: 'Skip both characters without recording' },
        { id: 'c', text: 'Move left only' },
        { id: 'd', text: 'Restart from dp[0][0]' },
      ],
      correct: ['a'],
      explanation: 'Equal characters belong to the LCS; backtrack from dp[m][n] along diagonal matches.',
    },
  ],
  challenges: [
    {
      id: 'lcs-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'X = "ABC", Y = "AC". Build dp. What is dp[3][2]?',
      options: [
        { id: 'a', text: '2' },
        { id: 'b', text: '1' },
        { id: 'c', text: '3' },
        { id: 'd', text: '0' },
      ],
      correct: ['a'],
      explanation: 'LCS is "AC" (length 2). Match A, skip B in X, match C.',
    },
    {
      id: 'lcs-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'You only need LCS length, not reconstruction, and m >> n. Best space optimization?',
      options: [
        { id: 'a', text: 'Two-row DP using O(min(m, n)) space' },
        { id: 'b', text: 'Store full 3D table' },
        { id: 'c', text: 'Memoize all 2^n subsequences of X' },
        { id: 'd', text: 'Use a heap' },
      ],
      correct: ['a'],
      explanation: 'Only the previous and current rows are needed; swap shorter string to columns to minimize rows.',
    },
  ],
} satisfies QuizPack