import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/18-hashing',
  topicId: 'hashing',
  title: 'Hashing',
  quiz: [
    {
      id: 'hash-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What average-case complexity does a hash map provide for insert and lookup?',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['a'],
      explanation: 'Good hash function + bounded load factor → constant expected time per operation.',
    },
    {
      id: 'hash-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Worst-case lookup in a hash table with pathological collisions:',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(n²)' },
      ],
      correct: ['c'],
      explanation: 'All keys in one bucket degrades to linear scan — mitigated by randomized hashing against HashDoS.',
    },
    {
      id: 'hash-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Two Sum can be solved in O(n) time using a hash map storing seen values → indices.',
      correct: true,
      explanation: 'For each nums[i], check if (target - nums[i]) was seen — chapter canonical hashing problem.',
    },
    {
      id: 'hash-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Deduplicate millions of log lines in an ETL pipeline. Natural structure to use?',
      options: [
        { id: 'a', text: 'Hash set (map keys to struct{}) tracking seen strings' },
        { id: 'b', text: 'Bubble sort then scan' },
        { id: 'c', text: 'Binary search on unsorted lines' },
        { id: 'd', text: 'Counting sort on string length only' },
      ],
      correct: ['a'],
      explanation: 'Chapter Go example: map[string]struct{} for O(1) average membership checks while streaming.',
    },
    {
      id: 'hash-q5',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'Hash tables typically resize when load factor exceeds about ___ (common range 0.7–0.75).',
      correct: ['0.75', '0.7', '75%', '70%'],
      explanation: 'Chapter: resize when load factor exceeds threshold to keep chains/probes short.',
    },
    {
      id: 'hash-q6',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Collision resolution strategies include: (Select all that apply)',
      options: [
        { id: 'a', text: 'Chaining (buckets of lists)' },
        { id: 'b', text: 'Open addressing with probe sequences' },
        { id: 'c', text: 'Merge sort on buckets' },
        { id: 'd', text: 'Binary search on unsorted keys' },
      ],
      correct: ['a', 'b'],
      explanation: 'Hash tables resolve index collisions via chaining or probing — not comparison sorting.',
    },
    {
      id: 'hash-q7',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'In Two Sum, why store nums[i] in the map AFTER checking for complement?',
      code: `int need = target - nums[i];
if (map.TryGetValue(need, out int j))
    return new[] { j, i };
map[nums[i]] = i;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Prevents using the same element twice as both operands' },
        { id: 'b', text: 'Makes the algorithm O(n²)' },
        { id: 'c', text: 'Required because the array is sorted' },
        { id: 'd', text: 'Ensures lexicographically smallest indices always' },
      ],
      correct: ['a'],
      explanation: 'Check complement first, then insert current index — avoids pairing an element with itself.',
    },
    {
      id: 'hash-q8',
      type: 'trace',
      difficulty: 'medium',
      question: 'Two Sum on nums=[2, 7, 11, 15], target=9. At i=1 (value 7), what happens?',
      options: [
        { id: 'a', text: 'need=2 found in map at index 0 → return [0, 1]' },
        { id: 'b', text: 'need=2 not found; map stays empty' },
        { id: 'c', text: 'Return [-1, -1] immediately' },
        { id: 'd', text: 'need=7 found at index 1' },
      ],
      correct: ['a'],
      explanation: 'i=0 stores 2→0. At i=1, need=9-7=2, map has 2 at j=0, return [0,1].',
    },
  ],
  challenges: [
    {
      id: 'hash-c1',
      type: 'variant',
      difficulty: 'hard',
      question: 'Randomized hashing in .NET and Go helps mitigate:',
      options: [
        { id: 'a', text: 'HashDoS — adversarial inputs crafted to force O(n) collisions' },
        { id: 'b', text: 'Integer overflow in binary search' },
        { id: 'c', text: 'Stable sort requirements' },
        { id: 'd', text: 'Radix sort digit extraction' },
      ],
      correct: ['a'],
      explanation: 'Chapter notes worst-case O(n) from pathological collisions; randomized hashes raise attack cost.',
    },
    {
      id: 'hash-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement Two Sum using a hash map. Return indices for nums=[2, 7, 11, 15], target=9 → [0, 1].',
      rubric: [
        'Iterate with index i',
        'Compute need = target - nums[i]',
        'If need in map, return [map[need], i]',
        'Otherwise store nums[i] → i',
        'Return sentinel if no pair (e.g. [-1,-1])',
      ],
      explanation: 'Master this pattern first — foundation for anagram grouping, subarray sum, and caches.',
    },
  ],
} satisfies QuizPack