import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/21-bst-operations',
  topicId: 'bst-operations',
  title: 'BST Operations',
  quiz: [
    {
      id: 'bst-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'How do you find the k-th smallest element in a BST?',
      options: [
        { id: 'a', text: 'Inorder traversal (left → root → right), stop at k' },
        { id: 'b', text: 'Level-order BFS' },
        { id: 'c', text: 'Preorder traversal only' },
        { id: 'd', text: 'Reverse the tree' },
      ],
      correct: ['a'],
      explanation: 'Inorder visits BST nodes in sorted order; count until you reach k.',
    },
    {
      id: 'bst-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Average-case time for BST search when the tree is balanced:',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['b'],
      explanation: 'Balanced BST height is O(log n); search follows one root-to-leaf path.',
    },
    {
      id: 'bst-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Checking only parent < child < grandchild is sufficient to validate a BST.',
      correct: false,
      explanation: 'BST invariant applies to entire subtrees — a node must be within (min, max) bounds passed down from ancestors.',
    },
    {
      id: 'bst-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'In a BST, find LCA of nodes with values 3 and 9. Current node is 6. Where do you go next?',
      options: [
        { id: 'a', text: 'Return 6 — it is the LCA' },
        { id: 'b', text: 'Go left' },
        { id: 'c', text: 'Go right' },
        { id: 'd', text: 'Go to parent' },
      ],
      correct: ['a'],
      explanation: '3 < 6 and 9 > 6 — one target is left, one is right. Current node is the split point = LCA.',
    },
    {
      id: 'bst-q5',
      type: 'mcq',
      difficulty: 'hard',
      question: 'When deleting a BST node with two children, the standard approach is:',
      options: [
        { id: 'a', text: 'Replace value with inorder successor (min of right subtree), then delete successor' },
        { id: 'b', text: 'Delete both subtrees' },
        { id: 'c', text: 'Swap with parent always' },
        { id: 'd', text: 'Convert to linked list first' },
      ],
      correct: ['a'],
      explanation: 'Copying the successor value preserves BST order; then delete the successor node (which has ≤1 child).',
    },
    {
      id: 'bst-q6',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What does this BST validation check enforce?',
      code: `if (node.Val <= min || node.Val >= max) return false;
return Validate(node.Left, min, node.Val)
    && Validate(node.Right, node.Val, max);`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Every node lies strictly between inherited min/max bounds' },
        { id: 'b', text: 'Tree is perfectly balanced' },
        { id: 'c', text: 'No duplicate values allowed ever' },
        { id: 'd', text: 'Parent is always the median' },
      ],
      correct: ['a'],
      explanation: 'Bounds tighten as you descend: left subtree max becomes node.Val, right subtree min becomes node.Val.',
    },
    {
      id: 'bst-q7',
      type: 'mcq',
      difficulty: 'medium',
      question: 'Floor of value x in a BST is:',
      options: [
        { id: 'a', text: 'The largest node value ≤ x' },
        { id: 'b', text: 'The smallest node value ≥ x' },
        { id: 'c', text: 'The root node always' },
        { id: 'd', text: 'The deepest leaf' },
      ],
      correct: ['a'],
      explanation: 'Floor walks like search, tracking the last node with value < x as candidate when going right.',
    },
    {
      id: 'bst-q8',
      type: 'trace',
      difficulty: 'hard',
      question: 'BST with values {5,3,7,1,4}. Floor(4) = ? (exact match returns itself)',
      options: [
        { id: 'a', text: '4' },
        { id: 'b', text: '3' },
        { id: 'c', text: '5' },
        { id: 'd', text: '1' },
      ],
      correct: ['a'],
      explanation: '4 exists in the tree — floor of an exact match is the value itself.',
    },
  ],
  challenges: [
    {
      id: 'bst-c1',
      type: 'trace',
      difficulty: 'hard',
      question: 'BST: 20 root, left 10 (children 5,15), right 30. Ceil(12) = ?',
      options: [
        { id: 'a', text: '15' },
        { id: 'b', text: '10' },
        { id: 'c', text: '20' },
        { id: 'd', text: '5' },
      ],
      correct: ['a'],
      explanation: '12 is between 10 and 15 in the left subtree; smallest value ≥ 12 is 15.',
    },
    {
      id: 'bst-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement BST Floor: return the largest value ≤ target, or indicate not found.',
      rubric: [
        'Walk from root comparing target to node value',
        'When node.Val < target, record as floor candidate and go right',
        'When node.Val > target, go left',
        'Return target immediately on exact match',
        'Return best floor candidate or not-found after walk',
      ],
      explanation: 'Floor/ceil are search variants with a running candidate. Test ceil(12) on the tree above → 15.',
    },
  ],
} satisfies QuizPack