import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/36-edit-distance',
  topicId: 'edit-distance',
  title: 'Edit Distance (Levenshtein)',
  quiz: [
    {
      id: 'ed-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Which operations are allowed in standard Levenshtein distance?',
      options: [
        { id: 'a', text: 'Insert, delete, replace' },
        { id: 'b', text: 'Insert and delete only' },
        { id: 'c', text: 'Swap any two characters' },
        { id: 'd', text: 'Transpose adjacent characters only' },
      ],
      correct: ['a'],
      explanation: 'Classic Levenshtein counts single-character insert, delete, and replace. Transpose is Damerau-Levenshtein.',
    },
    {
      id: 'ed-q2',
      type: 'mcq',
      difficulty: 'medium',
      question: 'Minimum edits to transform "horse" into "ros":',
      options: [
        { id: 'a', text: '3' },
        { id: 'b', text: '2' },
        { id: 'c', text: '4' },
        { id: 'd', text: '5' },
      ],
      correct: ['a'],
      explanation: 'One optimal sequence: delete h, delete r, replace e→s (other optimal sequences also cost 3).',
    },
    {
      id: 'ed-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'When word1[i-1] == word2[j-1], dp[i][j] = dp[i-1][j-1] with no extra cost.',
      correct: true,
      explanation: 'Matching characters require no edit — inherit cost from the diagonal predecessor.',
    },
    {
      id: 'ed-q4',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Standard 2D Levenshtein DP time complexity for lengths m and n:',
      options: [
        { id: 'a', text: 'O(m × n)' },
        { id: 'b', text: 'O(m + n)' },
        { id: 'c', text: 'O(m × n × log n)' },
        { id: 'd', text: 'O(2^m)' },
      ],
      correct: ['a'],
      explanation: 'Fill (m+1)×(n+1) table; Ukkonen banded DP can do O(m × d) when actual distance d is small.',
    },
    {
      id: 'ed-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'A phone autocorrect ranks dictionary candidates by lowest edit distance. Why is this deployed so widely?',
      options: [
        { id: 'a', text: 'Typos are usually few edits from the intended word' },
        { id: 'b', text: 'Edit distance runs in O(1) for all words' },
        { id: 'c', text: 'It finds semantic synonyms' },
        { id: 'd', text: 'It requires no dictionary' },
      ],
      correct: ['a'],
      explanation: 'Levenshtein models keyboard slips and missing letters — practical fuzzy matching for spell check.',
    },
    {
      id: 'ed-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'Base case dp[i][0] = i models deleting all ___ characters of word1.',
      correct: ['i', 'first i', 'remaining'],
      aliases: ['prefix'],
      explanation: 'Transforming word1[0..i-1] to empty word2 requires i deletions.',
    },
    {
      id: 'ed-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Which statements relate LCS and edit distance? (Select all)',
      options: [
        { id: 'a', text: 'Insert/delete-only distance = m + n - 2×LCS' },
        { id: 'b', text: 'Both use a 2D DP grid on two strings' },
        { id: 'c', text: 'Full Levenshtein always equals m + n - LCS' },
        { id: 'd', text: 'Replace can make Levenshtein cheaper than insert/delete only' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'With replace allowed, distance ≤ m + n - LCS; equality does not always hold.',
    },
    {
      id: 'ed-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'On mismatch, what does this recurrence compute?',
      code: `dp[i, j] = 1 + Math.Min(
    dp[i - 1, j],      // delete
    Math.Min(dp[i, j - 1], dp[i - 1, j - 1])  // insert, replace
);`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: '1 + cheapest of delete from word1, insert into word1, or replace' },
        { id: 'b', text: 'Longest common subsequence length' },
        { id: 'c', text: 'Number of permutations' },
        { id: 'd', text: 'Hamming distance only' },
      ],
      correct: ['a'],
      explanation: 'Three neighbors represent the three single-character edit operations plus one cost.',
    },
  ],
  challenges: [
    {
      id: 'ed-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'word1 = "cat", word2 = "cut". What is dp[3][3]?',
      options: [
        { id: 'a', text: '1' },
        { id: 'b', text: '2' },
        { id: 'c', text: '3' },
        { id: 'd', text: '0' },
      ],
      correct: ['a'],
      explanation: 'Single replace: a→u. All other characters match.',
    },
    {
      id: 'ed-c2',
      type: 'variant',
      difficulty: 'hard',
      question: 'Damerau-Levenshtein adds which operation as a single step?',
      options: [
        { id: 'a', text: 'Transposition of two adjacent characters (ab → ba)' },
        { id: 'b', text: 'Swap any two non-adjacent characters' },
        { id: 'c', text: 'Delete two characters at once' },
        { id: 'd', text: 'Insert a substring' },
      ],
      correct: ['a'],
      explanation: 'Adjacent transposition captures common typos like "hte" → "the" in one edit.',
    },
  ],
} satisfies QuizPack