import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/32-astar',
  topicId: 'astar',
  title: 'A*',
  quiz: [
    {
      id: 'astar-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'A* combines Dijkstra with what extra term?',
      options: [
        { id: 'a', text: 'Heuristic h(n) — f(n) = g(n) + h(n)' },
        { id: 'b', text: 'Random edge weights' },
        { id: 'c', text: 'Topological ordering' },
        { id: 'd', text: 'Union-Find' },
      ],
      correct: ['a'],
      explanation: 'g(n) = cost from start; h(n) = estimated cost to goal; f(n) guides search toward the target.',
    },
    {
      id: 'astar-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'A* time complexity in typical cases:',
      options: [
        { id: 'a', text: 'O(E log V) — similar to Dijkstra but explores fewer nodes with good h' },
        { id: 'b', text: 'O(V³)' },
        { id: 'c', text: 'O(1)' },
        { id: 'd', text: 'O(n!)' },
      ],
      correct: ['a'],
      explanation: 'Same priority-queue structure as Dijkstra; heuristic quality determines how many nodes are explored.',
    },
    {
      id: 'astar-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'An admissible heuristic never overestimates the true cost to the goal.',
      correct: true,
      explanation: 'Admissibility guarantees A* finds optimal path — h(n) ≤ actual distance to goal.',
    },
    {
      id: 'astar-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Grid pathfinding with 4-directional moves and varying terrain costs. Why A* over plain Dijkstra?',
      options: [
        { id: 'a', text: 'Manhattan heuristic focuses search toward goal — explores far fewer cells' },
        { id: 'b', text: 'A* handles negative weights' },
        { id: 'c', text: 'Dijkstra cannot work on grids' },
        { id: 'd', text: 'A* does not need a priority queue' },
      ],
      correct: ['a'],
      explanation: 'Dijkstra expands uniformly in all directions; A* with Manhattan h prioritizes cells closer to goal.',
    },
    {
      id: 'astar-q5',
      type: 'mcq',
      difficulty: 'hard',
      question: 'Manhattan distance on a 4-directional grid is admissible because:',
      options: [
        { id: 'a', text: 'You cannot reach the goal in fewer than |Δr| + |Δc| steps' },
        { id: 'b', text: 'It always overestimates' },
        { id: 'c', text: 'Diagonal moves are required' },
        { id: 'd', text: 'Grid must have no obstacles' },
      ],
      correct: ['a'],
      explanation: 'Each step changes row or column by 1 — minimum steps needed is Manhattan distance, never less.',
    },
    {
      id: 'astar-q6',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What is enqueued into the open set priority queue?',
      code: `open.Enqueue(nei, tent + H(nei));`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'f(n) = g(nei) + h(nei) where tent is g(nei)' },
        { id: 'b', text: 'Only h(nei)' },
        { id: 'c', text: 'Only g(nei)' },
        { id: 'd', text: 'Random priority' },
      ],
      correct: ['a'],
      explanation: 'tent is g-score (cost from start); tent + H(nei) is f-score used for priority ordering.',
    },
    {
      id: 'astar-q7',
      type: 'true-false',
      difficulty: 'medium',
      question: 'BFS finds optimal paths on grids with varying terrain costs.',
      correct: false,
      explanation: 'BFS works for unweighted (unit cost) grids. Varying terrain costs require Dijkstra or A*.',
    },
    {
      id: 'astar-q8',
      type: 'scenario',
      difficulty: 'hard',
      question: 'Game engines (Unity, Unreal) use A* for pathfinding. Inadmissible heuristic causes:',
      options: [
        { id: 'a', text: 'May find suboptimal paths — overestimates make A* greedy and wrong' },
        { id: 'b', text: 'Always faster optimal paths' },
        { id: 'c', text: 'Handles negative cycles' },
        { id: 'd', text: 'No effect on correctness' },
      ],
      correct: ['a'],
      explanation: 'Overestimating h can skip nodes on the true shortest path — optimality guarantee is lost.',
    },
  ],
  challenges: [
    {
      id: 'astar-c1',
      type: 'trace',
      difficulty: 'hard',
      question: 'Start (0,0), goal (2,2), 4-directional unit costs, no obstacles. Manhattan h(0,0) = ?',
      options: [
        { id: 'a', text: '4' },
        { id: 'b', text: '2' },
        { id: 'c', text: '3' },
        { id: 'd', text: '0' },
      ],
      correct: ['a'],
      explanation: '|2-0| + |2-0| = 4. Admissible lower bound on steps needed.',
    },
    {
      id: 'astar-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement A* on a 2D grid: cells with cost ≥ 0, -1 = wall. Return path from start to goal or empty if none.',
      rubric: [
        'gScore map: cost from start; cameFrom map for reconstruction',
        'Min-priority queue ordered by f = g + h (Manhattan to goal)',
        'Expand 4 neighbors, skip walls and out-of-bounds',
        'Update gScore and enqueue when tentative g improves',
        'Reconstruct path when goal dequeued/popped',
      ],
      explanation: 'Dijkstra + Manhattan heuristic. Test on open 3×3 grid from (0,0) to (2,2) — path length 5 cells.',
    },
  ],
} satisfies QuizPack