import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/14-heapsort',
  topicId: 'heapsort',
  title: 'Heapsort',
  quiz: [
    {
      id: 'hs-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What data structure property does heapsort exploit?',
      options: [
        { id: 'a', text: 'Binary max-heap (parent ≥ children)' },
        { id: 'b', text: 'BST in-order traversal' },
        { id: 'c', text: 'Hash bucket chaining' },
        { id: 'd', text: 'Adjacency list for graphs' },
      ],
      correct: ['a'],
      explanation: 'Build a max-heap in the array, then repeatedly swap root (max) to the end and heapify down.',
    },
    {
      id: 'hs-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'Guaranteed worst-case time complexity of heapsort:',
      options: [
        { id: 'a', text: 'O(n²)' },
        { id: 'b', text: 'O(n log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(log n)' },
      ],
      correct: ['b'],
      explanation: 'Build heap O(n) + n extractions each O(log n) → O(n log n) worst, average, and best.',
    },
    {
      id: 'hs-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Heapsort uses O(1) extra space beyond the input array.',
      correct: true,
      explanation: 'In-place heapify and swaps — no O(n) auxiliary buffer like merge sort.',
    },
    {
      id: 'hs-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Memory is extremely tight; you need O(n log n) worst-case guarantees without O(n) auxiliary arrays. Pick:',
      options: [
        { id: 'a', text: 'Heapsort' },
        { id: 'b', text: 'Merge sort' },
        { id: 'c', text: 'Naive quicksort with last-element pivot on sorted data' },
        { id: 'd', text: 'Bubble sort' },
      ],
      correct: ['a'],
      explanation: 'Chapter problem: reliable in-place O(n log n) when space is critical — heapsort’s niche.',
    },
    {
      id: 'hs-q5',
      type: 'trace',
      difficulty: 'hard',
      question: 'In heapify at index i, what are the child indices in a 0-based array heap of size n?',
      options: [
        { id: 'a', text: 'left = 2*i+1, right = 2*i+2' },
        { id: 'b', text: 'left = i-1, right = i+1' },
        { id: 'c', text: 'left = i/2, right = i/2+1' },
        { id: 'd', text: 'left = 2*i, right = 2*i+1' },
      ],
      correct: ['a'],
      explanation: 'Standard binary heap indexing from the chapter implementation.',
    },
    {
      id: 'hs-q6',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'Build-heap loops i from ___ down to 0 calling heapify.',
      correct: ['n/2-1', 'n/2 - 1'],
      explanation: 'Last non-leaf is at n/2 - 1; leaves need no initial heapify during build.',
    },
    {
      id: 'hs-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Heapsort compared to quicksort: (Select all that apply)',
      options: [
        { id: 'a', text: 'Heapsort has better worst-case time guarantee' },
        { id: 'b', text: 'Quicksort often wins on average cache behavior in practice' },
        { id: 'c', text: 'Heapsort avoids O(n) extra space that merge sort needs' },
        { id: 'd', text: 'Heapsort is stable by default' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Heapsort trades some cache locality for guaranteed bounds; it is not stable.',
    },
    {
      id: 'hs-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'After swapping arr[0] with arr[i] in the extraction loop, why call Heapify(arr, i, 0)?',
      code: `(arr[0], arr[i]) = (arr[i], arr[0]);
Heapify(arr, i, 0);`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'New root may violate heap property; heapify down on reduced heap size i' },
        { id: 'b', text: 'Rebuild entire heap from scratch each time' },
        { id: 'c', text: 'Sort the already-sorted tail portion' },
        { id: 'd', text: 'Convert max-heap to min-heap permanently' },
      ],
      correct: ['a'],
      explanation: 'Extract-max: move largest to sorted tail, shrink heap to size i, restore heap property at root.',
    },
  ],
  challenges: [
    {
      id: 'hs-c1',
      type: 'variant',
      difficulty: 'hard',
      question: 'Introsort (.NET Array.Sort) switches to heapsort when:',
      options: [
        { id: 'a', text: 'Recursion depth exceeds a limit — avoiding quicksort’s O(n²) path' },
        { id: 'b', text: 'The array has fewer than 10 elements' },
        { id: 'c', text: 'All elements are equal' },
        { id: 'd', text: 'Input is already sorted ascending' },
      ],
      correct: ['a'],
      explanation: 'Chapter notes heapsort as introsort’s fallback when recursion depth or space is a concern.',
    },
    {
      id: 'hs-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement heapsort: build max-heap, then extract-max loop with heapify. Sort [4, 10, 3, 5, 1].',
      rubric: [
        'Build heap: for i from n/2-1 down to 0, heapify(arr, n, i)',
        'Extraction loop: swap arr[0] with arr[i], heapify(arr, i, 0)',
        'Heapify picks largest among node and children',
        'Recursive or iterative sift-down acceptable',
        'Final array sorted ascending',
      ],
      explanation: 'The reliable in-place guaranteed sorter — pair with heap chapter for full understanding.',
    },
  ],
} satisfies QuizPack