import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/47-consistent-hashing',
  topicId: 'consistent-hashing',
  title: 'Consistent Hashing',
  quiz: [
    {
      id: 'ch-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Naive `hash(key) % n` fails when n changes because:',
      options: [
        { id: 'a', text: 'Nearly every key remaps to a different node' },
        { id: 'b', text: 'Modulo is undefined for strings' },
        { id: 'c', text: 'Hash functions return negative values only' },
        { id: 'd', text: 'Keys cannot be hashed' },
      ],
      correct: ['a'],
      explanation: 'Changing n reshuffles almost all assignments — thundering herd of cache misses.',
    },
    {
      id: 'ch-q2',
      type: 'mcq',
      difficulty: 'medium',
      question: 'On a hash ring, a key is assigned to:',
      options: [
        { id: 'a', text: 'First node found clockwise from the key\'s hash position' },
        { id: 'b', text: 'The node with lowest hash always' },
        { id: 'c', text: 'Random node each request' },
        { id: 'd', text: 'The node with matching hostname' },
      ],
      correct: ['a'],
      explanation: 'Walk clockwise on the ring to successor node — classic consistent hashing lookup.',
    },
    {
      id: 'ch-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Virtual nodes (vnodes) help balance load when physical nodes have uneven arc sizes.',
      correct: true,
      explanation: 'Multiple ring positions per machine smooths distribution — often 100–150 replicas.',
    },
    {
      id: 'ch-q4',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Key lookup on a sorted hash ring with r positions:',
      options: [
        { id: 'a', text: 'O(log r) via binary search' },
        { id: 'b', text: 'O(1) always' },
        { id: 'c', text: 'O(r²)' },
        { id: 'd', text: 'O(n!)' },
      ],
      correct: ['a'],
      explanation: 'Binary search for first sortedKeys[i] >= hash(key); wrap if past end.',
    },
    {
      id: 'ch-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Adding 1 node to a cluster of n nodes with consistent hashing moves roughly:',
      options: [
        { id: 'a', text: 'K/(n+1) keys — about 1/(n+1) of all keys' },
        { id: 'b', text: '100% of keys' },
        { id: 'c', text: '0% of keys always' },
        { id: 'd', text: '50% regardless of n' },
      ],
      correct: ['a'],
      explanation: 'Only keys in the new node\'s arc between predecessor and successor migrate.',
    },
    {
      id: 'ch-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'Production systems should use stable hashes like FNV-1a or Murmur3, not .NET ___ which varies across processes.',
      correct: ['GetHashCode', 'GetHashCode()'],
      aliases: ['gethashcode'],
      explanation: 'Chapter warns GetHashCode() is not stable across runs — breaks distributed routing.',
    },
    {
      id: 'ch-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Which systems use consistent hashing variants? (Select all)',
      options: [
        { id: 'a', text: 'Memcached Ketama client' },
        { id: 'b', text: 'Cassandra / Dynamo-style sharding' },
        { id: 'c', text: 'Redis Cluster hash slots' },
        { id: 'd', text: 'Merge sort' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Distributed caches and databases rely on minimal-remap sharding.',
    },
    {
      id: 'ch-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'Why set `if (idx == sortedKeys.Count) idx = 0` after binary search?',
      code: `if (idx == sortedKeys.Count) idx = 0;
return ring[sortedKeys[idx]];`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Wrap around the ring when key hash exceeds all vnode positions' },
        { id: 'b', text: 'Handle empty ring' },
        { id: 'c', text: 'Sort keys descending' },
        { id: 'd', text: 'Delete the first node' },
      ],
      correct: ['a'],
      explanation: 'Ring is circular — first clockwise node from top wraps to lowest vnode position.',
    },
  ],
  challenges: [
    {
      id: 'ch-c1',
      type: 'scenario',
      difficulty: 'medium',
      question: '3 Memcached servers → add 4th. Naive mod-3 vs consistent hashing keys moved:',
      options: [
        { id: 'a', text: '~100% vs ~25%' },
        { id: 'b', text: '~25% vs ~100%' },
        { id: 'c', text: '0% vs 0%' },
        { id: 'd', text: '50% vs 50%' },
      ],
      correct: ['a'],
      explanation: 'Chapter canonical example: mod-n reshuffles everything; CH moves ~K/(n+1).',
    },
    {
      id: 'ch-c2',
      type: 'variant',
      difficulty: 'hard',
      question: 'Jump consistent hash (Google 2014) improves on basic ring by:',
      options: [
        { id: 'a', text: 'O(ln n) lookup, minimal migration, no ring storage' },
        { id: 'b', text: 'Eliminating all key movement forever' },
        { id: 'c', text: 'Using XOR only' },
        { id: 'd', text: 'Requiring O(n) lookup' },
      ],
      correct: ['a'],
      explanation: 'Jump CH is order-preserving with tiny memory — alternative to vnode rings.',
    },
  ],
} satisfies QuizPack