import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/11-insertion-sort',
  topicId: 'insertion-sort',
  title: 'Insertion Sort',
  quiz: [
    {
      id: 'is-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'How does insertion sort build the sorted result?',
      options: [
        { id: 'a', text: 'Maintains a sorted prefix and inserts each new element into its correct position' },
        { id: 'b', text: 'Repeatedly swaps only adjacent out-of-order pairs' },
        { id: 'c', text: 'Partitions around a pivot then recurses' },
        { id: 'd', text: 'Counts occurrences of each value in a range' },
      ],
      correct: ['a'],
      explanation: 'Like sorting playing cards in your hand: each new card slides into the already-sorted portion.',
    },
    {
      id: 'is-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'Best-case time complexity of insertion sort on n elements:',
      options: [
        { id: 'a', text: 'O(n)' },
        { id: 'b', text: 'O(n log n)' },
        { id: 'c', text: 'O(n²)' },
        { id: 'd', text: 'O(1)' },
      ],
      correct: ['a'],
      explanation: 'Already-sorted input: inner while never shifts, one comparison per element → O(n).',
    },
    {
      id: 'is-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Insertion sort is stable and in-place.',
      correct: true,
      explanation: 'Shifting only happens for larger elements; equal keys keep order. Uses O(1) extra space.',
    },
    {
      id: 'is-q4',
      type: 'trace',
      difficulty: 'medium',
      question: 'Sort [3, 1, 4, 2] with insertion sort. After processing i=2 (element 4), what is the array?',
      options: [
        { id: 'a', text: '[1, 3, 4, 2]' },
        { id: 'b', text: '[1, 4, 3, 2]' },
        { id: 'c', text: '[3, 1, 4, 2]' },
        { id: 'd', text: '[1, 3, 2, 4]' },
      ],
      correct: ['a'],
      explanation: 'After i=1: [1,3,4,2]. At i=2, key=4: 4>3, no shift needed — still [1,3,4,2].',
    },
    {
      id: 'is-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Log timestamps arrive mostly in order with occasional network-delay reversals. Why is insertion sort attractive?',
      options: [
        { id: 'a', text: 'Nearly sorted data approaches O(n); simple online-friendly shifts' },
        { id: 'b', text: 'It always beats merge sort on million-element random arrays' },
        { id: 'c', text: 'It needs O(n) extra memory for merging' },
        { id: 'd', text: 'It is unstable so duplicates are handled faster' },
      ],
      correct: ['a'],
      explanation: 'Chapter classic problem: mostly increasing stream with rare out-of-order entries — insertion sort shines.',
    },
    {
      id: 'is-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'In the implementation, the element being placed is stored in a variable called ___.',
      correct: ['key'],
      explanation: 'Both C# and Go implementations save arr[i] as key before shifting larger elements right.',
    },
    {
      id: 'is-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Where does insertion sort appear in production systems? (Select all that apply)',
      options: [
        { id: 'a', text: 'Timsort for small runs (~32–64 elements)' },
        { id: 'b', text: 'Introsort for tiny subarrays' },
        { id: 'c', text: 'Sorting a handful of UI dropdown items' },
        { id: 'd', text: 'Primary sorter for billion-row external sorts' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Hybrids use insertion sort for small/nearly sorted chunks — not as the main engine for huge datasets.',
    },
    {
      id: 'is-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What does the inner while loop accomplish?',
      code: `while (j >= 0 && arr[j] > key) {
    arr[j + 1] = arr[j];
    j--;
}`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Shifts larger elements one position right to make room for key' },
        { id: 'b', text: 'Swaps key with every equal element' },
        { id: 'c', text: 'Builds a max-heap from the prefix' },
        { id: 'd', text: 'Counts inversions in the array' },
      ],
      correct: ['a'],
      explanation: 'Elements greater than key slide right; loop stops when j points to the insertion slot.',
    },
  ],
  challenges: [
    {
      id: 'is-c1',
      type: 'variant',
      difficulty: 'hard',
      question: 'Online sorting (values arrive one at a time) maps naturally to insertion sort because:',
      options: [
        { id: 'a', text: 'Each arrival is inserted into the current sorted list without restarting' },
        { id: 'b', text: 'It requires knowing the final n before starting' },
        { id: 'c', text: 'It rebuilds a heap on every arrival' },
        { id: 'd', text: 'It only works after a full counting pass' },
      ],
      correct: ['a'],
      explanation: 'Chapter lists online sorting as a real-world use — incremental insert into sorted prefix.',
    },
    {
      id: 'is-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement insertion sort in-place. Sort [3, 1, 4, 2] and confirm final order [1, 2, 3, 4].',
      rubric: [
        'Outer loop from i=1 to n-1',
        'Save key = arr[i]',
        'Shift arr[j] right while j >= 0 and arr[j] > key',
        'Place key at arr[j+1]',
        'Correct sorted output',
      ],
      explanation: 'The practical O(n²) champion for small or nearly sorted data.',
    },
  ],
} satisfies QuizPack