import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/19-quickselect',
  topicId: 'quickselect',
  title: 'Quickselect',
  quiz: [
    {
      id: 'qs-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What does quickselect find without fully sorting the array?',
      options: [
        { id: 'a', text: 'The k-th smallest element' },
        { id: 'b', text: 'The longest increasing subsequence' },
        { id: 'c', text: 'All permutations' },
        { id: 'd', text: 'The maximum flow' },
      ],
      correct: ['a'],
      explanation: 'Quickselect partitions like quicksort but recurses only into the side containing index k.',
    },
    {
      id: 'qs-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Average-case time complexity of quickselect on n elements:',
      options: [
        { id: 'a', text: 'O(log n)' },
        { id: 'b', text: 'O(n)' },
        { id: 'c', text: 'O(n log n)' },
        { id: 'd', text: 'O(n²)' },
      ],
      correct: ['b'],
      explanation: 'Each partition shrinks the problem; expected work per level is O(n), with O(log n) levels on average.',
    },
    {
      id: 'qs-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Quickselect recurses into both partitions after each pivot step, like full quicksort.',
      correct: false,
      explanation: 'Only the partition containing index k is recursed — that is the key efficiency over full sort.',
    },
    {
      id: 'qs-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'You need the median of 10 million numbers in one pass with minimal extra memory. Best choice?',
      options: [
        { id: 'a', text: 'Quickselect with k = n/2' },
        { id: 'b', text: 'Merge sort the entire array' },
        { id: 'c', text: 'Counting sort always' },
        { id: 'd', text: 'BFS' },
      ],
      correct: ['a'],
      explanation: 'Median is the n/2-th order statistic. Quickselect averages O(n) time and O(1) extra space (iterative).',
    },
    {
      id: 'qs-q5',
      type: 'trace',
      difficulty: 'hard',
      question: 'Array [3, 2, 1, 5, 6, 4], k = 2 (0-indexed, 3rd smallest). After one partition with pivot = arr[hi] = 4, which index holds the answer?',
      options: [
        { id: 'a', text: 'Index 2 (value 3)' },
        { id: 'b', text: 'Index 0 (value 1)' },
        { id: 'c', text: 'Index 4 (value 5)' },
        { id: 'd', text: 'Index 5 (value 4)' },
      ],
      correct: ['a'],
      explanation: 'Lomuto partition with pivot 4 places sorted order around index 2; k=2 lands on the 3rd smallest (3).',
    },
    {
      id: 'qs-q6',
      type: 'mcq',
      difficulty: 'hard',
      question: 'Worst-case quickselect is O(n²). A common mitigation is:',
      options: [
        { id: 'a', text: 'Random pivot selection or introselect' },
        { id: 'b', text: 'Always pick the first element as pivot on sorted input' },
        { id: 'c', text: 'Use a stack instead of recursion only' },
        { id: 'd', text: 'Sort first, then binary search' },
      ],
      correct: ['a'],
      explanation: 'Adversarial or sorted input with fixed pivot causes unbalanced partitions; randomization or introselect fixes worst case.',
    },
    {
      id: 'qs-q7',
      type: 'true-false',
      difficulty: 'medium',
      question: 'C++ std::nth_element is based on the quickselect / partition idea.',
      correct: true,
      explanation: 'nth_element partially orders the range so the element at position n is the one that would appear there if fully sorted.',
    },
    {
      id: 'qs-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'After this loop iteration, which side should we recurse into for k = 1?',
      code: `int p = Partition(arr, lo, hi);
if (p == k) return arr[p];
if (k < p) hi = p - 1;
else lo = p + 1;`,
      codeLang: 'pseudocode',
      options: [
        { id: 'a', text: 'If p > k, search left (hi = p - 1)' },
        { id: 'b', text: 'If p > k, search right (lo = p + 1)' },
        { id: 'c', text: 'Always search both sides' },
        { id: 'd', text: 'Restart from lo = 0' },
      ],
      correct: ['a'],
      explanation: 'Elements left of pivot index are smaller; if k < p, the answer is in the left subarray.',
    },
  ],
  challenges: [
    {
      id: 'qs-c1',
      type: 'trace',
      difficulty: 'hard',
      question: 'Array [7, 10, 4, 3, 20, 15], k = 3 (0-indexed, 4th smallest). What value is returned?',
      options: [
        { id: 'a', text: '10' },
        { id: 'b', text: '7' },
        { id: 'c', text: '15' },
        { id: 'd', text: '4' },
      ],
      correct: ['a'],
      explanation: 'Sorted order: 3, 4, 7, 10, 15, 20. The 4th smallest (k=3) is 10.',
    },
    {
      id: 'qs-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement iterative quickselect that returns the k-th smallest element (0-indexed) in an int array.',
      rubric: [
        'Loop with lo/hi bounds until pivot index equals k',
        'Partition around a pivot (e.g. arr[hi]) and return pivot index',
        'If k < pivot index, recurse left; else recurse right',
        'Return arr[k] when pivot index matches k',
        'Handle empty or invalid range appropriately',
      ],
      explanation: 'Classic Lomuto partition + single-side recursion. Test on [3,2,1,5,6,4] with k=2 → 3.',
    },
  ],
} satisfies QuizPack