import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/28-dijkstra',
  topicId: 'dijkstra',
  title: 'Dijkstra',
  quiz: [
    {
      id: 'dij-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What problem does Dijkstra\'s algorithm solve?',
      options: [
        { id: 'a', text: 'Single-source shortest paths in graphs with non-negative edge weights' },
        { id: 'b', text: 'All-pairs shortest paths only' },
        { id: 'c', text: 'Minimum spanning tree' },
        { id: 'd', text: 'Topological sort' },
      ],
      correct: ['a'],
      explanation: 'Dijkstra computes minimum-cost distances from one source to all reachable vertices.',
    },
    {
      id: 'dij-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Time complexity with binary heap (lazy priority queue) on V vertices, E edges:',
      options: [
        { id: 'a', text: 'O((V + E) log V)' },
        { id: 'b', text: 'O(V²)' },
        { id: 'c', text: 'O(V × E)' },
        { id: 'd', text: 'O(E²)' },
      ],
      correct: ['a'],
      explanation: 'Each vertex/edge may enqueue heap entries; heap operations are O(log V).',
    },
    {
      id: 'dij-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Dijkstra works correctly with negative edge weights.',
      correct: false,
      explanation: 'Negative edges break the greedy invariant — a settled distance may be improved later. Use Bellman-Ford instead.',
    },
    {
      id: 'dij-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'GPS routing with road speeds and tolls (all non-negative costs). Best algorithm?',
      options: [
        { id: 'a', text: 'Dijkstra from source' },
        { id: 'b', text: 'BFS only' },
        { id: 'c', text: 'Bellman-Ford unless negative tolls exist' },
        { id: 'd', text: 'DFS only' },
      ],
      correct: ['a'],
      explanation: 'Weighted non-negative graph → Dijkstra. BFS only works for unweighted (unit cost) edges.',
    },
    {
      id: 'dij-q5',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'Why skip stale heap entries with `if (d > dist[u]) continue`?',
      code: `pq.TryDequeue(out int u, out int d);
if (d > dist[u]) continue;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Lazy heap may have outdated larger distances — ignore superseded entries' },
        { id: 'b', text: 'Detect negative cycles' },
        { id: 'c', text: 'Sort vertices by ID' },
        { id: 'd', text: 'Required for negative weights' },
      ],
      correct: ['a'],
      explanation: 'Lazy Dijkstra enqueues on every improvement without decrease-key; stale larger entries must be skipped.',
    },
    {
      id: 'dij-q6',
      type: 'mcq',
      difficulty: 'hard',
      question: 'The relax step for edge (u, v, w) is:',
      options: [
        { id: 'a', text: 'if dist[u] + w < dist[v], update dist[v] and parent[v]' },
        { id: 'b', text: 'if dist[v] + w < dist[u], swap u and v' },
        { id: 'c', text: 'if w < 0, use Dijkstra anyway' },
        { id: 'd', text: 'Always set dist[v] = dist[u] + w' },
      ],
      correct: ['a'],
      explanation: 'Relaxation tries to improve dist[v] through u — core of all shortest-path algorithms.',
    },
    {
      id: 'dij-q7',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Zero-weight edges are allowed in Dijkstra.',
      correct: true,
      explanation: 'Non-negative includes zero — greedy settling still works; zero-cost edges do not break correctness.',
    },
    {
      id: 'dij-q8',
      type: 'scenario',
      difficulty: 'hard',
      question: 'Reconstruct shortest path after Dijkstra. Which array do you walk backwards from target?',
      options: [
        { id: 'a', text: 'parent[] array from target following parent pointers to source' },
        { id: 'b', text: 'indegree[] array' },
        { id: 'c', text: 'visited[] only' },
        { id: 'd', text: 'Edge list unsorted' },
      ],
      correct: ['a'],
      explanation: 'parent[v] stores predecessor on shortest path; walk target → source, reverse to get path.',
    },
  ],
  challenges: [
    {
      id: 'dij-c1',
      type: 'trace',
      difficulty: 'hard',
      question: 'Graph: 0→(1,w=4), 0→(2,w=1), 2→(1,w=2). Shortest dist from 0 to 1?',
      options: [
        { id: 'a', text: '3' },
        { id: 'b', text: '4' },
        { id: 'c', text: '5' },
        { id: 'd', text: '1' },
      ],
      correct: ['a'],
      explanation: 'Path 0→2→1 costs 1+2=3, beating direct edge 0→1 with cost 4.',
    },
    {
      id: 'dij-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement Dijkstra with lazy min-heap: return dist[] and parent[] from source on a weighted adjacency list.',
      rubric: [
        'Initialize dist[source]=0, others to infinity; parent to -1',
        'Min-priority queue keyed by dist',
        'Pop u, skip if popped distance > dist[u]',
        'Relax each edge (u,v,w): update dist[v], parent[v], enqueue',
        'Reconstruct path by walking parent from target to source',
      ],
      explanation: 'Canonical lazy Dijkstra. Test on the 0→1(4), 0→2(1), 2→1(2) graph — dist[1]=3.',
    },
  ],
} satisfies QuizPack