import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/44-backtracking',
  topicId: 'backtracking',
  title: 'Backtracking',
  quiz: [
    {
      id: 'bt-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Backtracking is best described as:',
      options: [
        { id: 'a', text: 'DFS + pruning + undo (choose, explore, unchoose)' },
        { id: 'b', text: 'BFS on a graph' },
        { id: 'c', text: 'Dynamic programming bottom-up only' },
        { id: 'd', text: 'Greedy local optimum' },
      ],
      correct: ['a'],
      explanation: 'Try a choice, recurse, undo if dead end — explore decision tree with early cuts.',
    },
    {
      id: 'bt-q2',
      type: 'mcq',
      difficulty: 'medium',
      question: 'N-Queens places queens so no two share:',
      options: [
        { id: 'a', text: 'Same row, column, or diagonal' },
        { id: 'b', text: 'Same row only' },
        { id: 'c', text: 'Adjacent cells only' },
        { id: 'd', text: 'Same color square' },
      ],
      correct: ['a'],
      explanation: 'Classic constraint: one queen per row in standard formulation, plus column/diag checks.',
    },
    {
      id: 'bt-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Good pruning can make exponential worst-case search practical for many constraint problems.',
      correct: true,
      explanation: 'Without pruning, N-Queens and Sudoku are hopeless; constraints eliminate most branches.',
    },
    {
      id: 'bt-q4',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Subset sum via naive backtracking (no pruning) over n elements:',
      options: [
        { id: 'a', text: 'O(2^n) time' },
        { id: 'b', text: 'O(n)' },
        { id: 'c', text: 'O(n log n)' },
        { id: 'd', text: 'O(n²)' },
      ],
      correct: ['a'],
      explanation: 'Include/exclude each element — binary decision tree of depth n.',
    },
    {
      id: 'bt-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Regex engines may exhibit "catastrophic backtracking" when:',
      options: [
        { id: 'a', text: 'Alternation/quantifiers cause exponential retry on mismatch' },
        { id: 'b', text: 'Input is always sorted' },
        { id: 'c', text: 'DP memoization is enabled' },
        { id: 'd', text: 'Bitmasks are used' },
      ],
      correct: ['a'],
      explanation: 'Naive NFA-style backtracking can revisit the same state exponentially — known failure mode.',
    },
    {
      id: 'bt-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'The backtracking template: apply choice (choose), recurse (explore), then ___ the choice.',
      correct: ['undo', 'unchoose', 'revert'],
      aliases: ['restore', 'backtrack'],
      explanation: 'State must be restored so sibling branches see a clean partial solution.',
    },
    {
      id: 'bt-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Which are backtracking flagship problems? (Select all)',
      options: [
        { id: 'a', text: 'Sudoku solver' },
        { id: 'b', text: 'Generate valid parentheses' },
        { id: 'c', text: 'Merge sort' },
        { id: 'd', text: 'Word search on a grid' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'Merge sort is divide-and-conquer, not backtracking on a decision tree.',
    },
    {
      id: 'bt-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: "What does `board[row][col] = '.'` after recursion accomplish?",
      code: `board[row][col] = 'Q';
Backtrack(board, row + 1);
board[row][col] = '.';`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Undoes the queen placement before trying the next column' },
        { id: 'b', text: 'Marks the cell permanently visited' },
        { id: 'c', text: 'Saves the solution to disk' },
        { id: 'd', text: 'Prunes all future rows' },
      ],
      correct: ['a'],
      explanation: 'Classic unchoose step — restores board for the next sibling choice at this row.',
    },
  ],
  challenges: [
    {
      id: 'bt-c1',
      type: 'ordering',
      difficulty: 'medium',
      question: 'Order the backtracking template steps:',
      items: [
        { id: '1', text: 'Check if state is complete → record solution' },
        { id: '2', text: 'For each choice: prune if invalid' },
        { id: '3', text: 'Apply choice (choose)' },
        { id: '4', text: 'Recurse on next decisions (explore)' },
        { id: '5', text: 'Undo choice (unchoose)' },
      ],
      correct: ['1', '2', '3', '4', '5'],
      explanation: 'Base case first; per choice: prune → choose → explore → undo.',
    },
    {
      id: 'bt-c2',
      type: 'variant',
      difficulty: 'hard',
      question: 'N-Queens with bitmasks replaces isSafe() loops with O(1) checks using:',
      options: [
        { id: 'a', text: 'cols | diag1 | diag2 bit masks for occupied attacks' },
        { id: 'b', text: 'Hash map of strings' },
        { id: 'c', text: 'Floyd-Warshall' },
        { id: 'd', text: 'Segment tree only' },
      ],
      correct: ['a'],
      explanation: 'Bitmask N-Queens tracks columns and diagonals as integers — see chapter 45 cross-link.',
    },
  ],
} satisfies QuizPack