import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/27-topological-sort',
  topicId: 'topological-sort',
  title: 'Topological Sort',
  quiz: [
    {
      id: 'topo-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What does topological sort produce for a DAG?',
      options: [
        { id: 'a', text: 'Linear ordering where every edge u→v has u before v' },
        { id: 'b', text: 'Shortest path from source to all nodes' },
        { id: 'c', text: 'Minimum spanning tree' },
        { id: 'd', text: 'Maximum clique' },
      ],
      correct: ['a'],
      explanation: 'Topological order respects all precedence constraints — u must appear before v for every edge u→v.',
    },
    {
      id: 'topo-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Time complexity of Kahn\'s topological sort on V vertices and E edges:',
      options: [
        { id: 'a', text: 'O(V + E)' },
        { id: 'b', text: 'O(V²)' },
        { id: 'c', text: 'O(E log V)' },
        { id: 'd', text: 'O(V³)' },
      ],
      correct: ['a'],
      explanation: 'Each vertex enqueued/dequeued once; each edge relaxed once when decrementing indegree.',
    },
    {
      id: 'topo-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'A valid topological ordering exists if and only if the graph is a DAG (no directed cycles).',
      correct: true,
      explanation: 'A cycle means mutual dependencies — no linear order can satisfy all edges.',
    },
    {
      id: 'topo-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Course prerequisites: [1,0] means must take 0 before 1. Can all courses be finished?',
      options: [
        { id: 'a', text: 'Run Kahn\'s — if order length < numCourses, cycle exists' },
        { id: 'b', text: 'Sort courses alphabetically' },
        { id: 'c', text: 'Use Dijkstra' },
        { id: 'd', text: 'Always yes' },
      ],
      correct: ['a'],
      explanation: 'Build edge prerequisite→course, run Kahn\'s. Incomplete order = impossible schedule.',
    },
    {
      id: 'topo-q5',
      type: 'mcq',
      difficulty: 'hard',
      question: 'Kahn\'s algorithm starts by enqueueing all vertices with:',
      options: [
        { id: 'a', text: 'Indegree 0 (no unmet dependencies)' },
        { id: 'b', text: 'Maximum outdegree' },
        { id: 'c', text: 'Largest vertex ID' },
        { id: 'd', text: 'Visited flag set' },
      ],
      correct: ['a'],
      explanation: 'Indegree 0 nodes have no prerequisites — safe to process first.',
    },
    {
      id: 'topo-q6',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Kahn\'s algorithm uses BFS on the indegree layer; DFS post-order is an alternative.',
      correct: true,
      explanation: 'Both run O(V+E). Kahn peels indegree-0 nodes; DFS pushes nodes after visiting all descendants.',
    },
    {
      id: 'topo-q7',
      type: 'scenario',
      difficulty: 'hard',
      question: 'npm/yarn install order is a real-world application of:',
      options: [
        { id: 'a', text: 'Topological sort on package dependency DAG' },
        { id: 'b', text: 'Floyd-Warshall' },
        { id: 'c', text: 'Reservoir sampling' },
        { id: 'd', text: 'Trie autocomplete' },
      ],
      correct: ['a'],
      explanation: 'Package A depends on B → edge B→A. Install order is a topological sort of the dependency graph.',
    },
    {
      id: 'topo-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'Kahn\'s returns hasCycle = true when:',
      code: `return (order, order.Count != n);`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Fewer than n vertices were processed — some nodes never reached indegree 0' },
        { id: 'b', text: 'The queue was empty at start' },
        { id: 'c', text: 'There are no edges' },
        { id: 'd', text: 'n is odd' },
      ],
      correct: ['a'],
      explanation: 'Nodes on a cycle never have indegree reduced to 0 — they remain unprocessed when queue stalls.',
    },
  ],
  challenges: [
    {
      id: 'topo-c1',
      type: 'trace',
      difficulty: 'hard',
      question: 'Edges: 0→1, 0→2, 1→3, 2→3. Valid topological order?',
      options: [
        { id: 'a', text: '0, 1, 2, 3' },
        { id: 'b', text: '3, 0, 1, 2' },
        { id: 'c', text: '1, 0, 2, 3' },
        { id: 'd', text: '2, 3, 0, 1' },
      ],
      correct: ['a'],
      explanation: '0 before 1,2; 1,2 before 3. [0,1,2,3] and [0,2,1,3] are valid — option (a) works.',
    },
    {
      id: 'topo-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement Kahn\'s topological sort: given n and edge list (from, to), return order and whether a cycle exists.',
      rubric: [
        'Build adjacency list and indegree array from edges',
        'Enqueue all indegree-0 vertices',
        'Dequeue u, append to order, decrement indegree of neighbors',
        'Enqueue neighbor when indegree becomes 0',
        'Return hasCycle = (order.length != n)',
      ],
      explanation: 'Canonical build-pipeline algorithm. Test on cycle 0→1→2→0 → hasCycle true.',
    },
  ],
} satisfies QuizPack