import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/09-exponential-search',
  topicId: 'exponential-search',
  title: 'Exponential Search',
  quiz: [
    {
      id: 'es-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What problem does exponential search primarily solve?',
      options: [
        { id: 'a', text: 'Searching sorted data when the size is unknown or unbounded' },
        { id: 'b', text: 'Searching unsorted arrays in O(log n)' },
        { id: 'c', text: 'Sorting arrays with O(n) comparisons' },
        { id: 'd', text: 'Finding duplicates without extra memory' },
      ],
      correct: ['a'],
      explanation: 'Standard binary search needs a known upper bound. Exponential search finds a range first, then binary searches inside it.',
    },
    {
      id: 'es-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Time complexity when the target is at index i in a sorted array (i may be far smaller than n):',
      options: [
        { id: 'a', text: 'O(i)' },
        { id: 'b', text: 'O(log i)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(i log n)' },
      ],
      correct: ['b'],
      explanation: 'Doubling bounds takes O(log i) steps, then binary search on a range of size ≤ i also costs O(log i).',
    },
    {
      id: 'es-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Exponential search requires the array to be sorted.',
      correct: true,
      explanation: 'The bound-finding step assumes arr[i] <= target implies all earlier elements are smaller — monotonic order.',
    },
    {
      id: 'es-q4',
      type: 'trace',
      difficulty: 'medium',
      question: 'Sorted array [2, 3, 5, 7, 11, 13, 17, 19, 23, 29], target 13. After bound-finding (i doubles: 1, 2, 4, 8...), which range is binary searched?',
      options: [
        { id: 'a', text: '[i/2, min(i, n-1)] = [4, 8]' },
        { id: 'b', text: '[0, n-1]' },
        { id: 'c', text: '[8, 9] only' },
        { id: 'd', text: '[0, 1]' },
      ],
      correct: ['a'],
      explanation: 'i doubles: 1→2→4→8 until arr[8]=23 > 13. Binary search runs on [i/2, min(i,n-1)] = [4, 8], which contains index 5.',
      misconception: 'Students often skip the i/2 lower bound and binary search [0, i] instead.',
    },
    {
      id: 'es-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'A sorted log file may be enormous; you can read any line by index but do not know total lines upfront. Best search strategy for a timestamp?',
      options: [
        { id: 'a', text: 'Exponential search to bracket, then binary search in the range' },
        { id: 'b', text: 'Linear scan from line 0 always' },
        { id: 'c', text: 'Binary search from line 0 to Integer.MAX_VALUE' },
        { id: 'd', text: 'Hash the timestamp without reading the file' },
      ],
      correct: ['a'],
      explanation: 'Chapter real-world case: probe exponentially until you pass the target region, then binary search locally.',
    },
    {
      id: 'es-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'In bound-finding, the index variable i starts at 1 and is multiplied by ___ each iteration.',
      correct: ['2'],
      explanation: 'Exponential growth: 1, 2, 4, 8, 16… until arr[i] >= target or i exceeds length.',
    },
    {
      id: 'es-q7',
      type: 'ordering',
      difficulty: 'medium',
      question: 'Order the steps of exponential search:',
      items: [
        { id: '1', text: 'If arr[0] == target, return 0' },
        { id: '2', text: 'Double i while i < n and arr[i] <= target' },
        { id: '3', text: 'Binary search in [i/2, min(i, n-1)]' },
        { id: '4', text: 'Return -1 if array is empty' },
      ],
      correct: ['4', '1', '2', '3'],
      explanation: 'Handle empty, check first element, expand bound exponentially, then standard binary search on the discovered range.',
    },
    {
      id: 'es-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'Why check arr[0] == target before the doubling loop?',
      code: `if (arr[0] == target) return 0;
int i = 1;
while (i < arr.Length && arr[i] <= target) i *= 2;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'The doubling loop starts at i=1, so index 0 needs an explicit check' },
        { id: 'b', text: 'Index 0 is always out of bounds' },
        { id: 'c', text: 'Binary search cannot find index 0' },
        { id: 'd', text: 'It prevents O(n) behavior entirely' },
      ],
      correct: ['a'],
      explanation: 'Bound finding begins at i=1; without the arr[0] check you would miss a target at the first position.',
    },
  ],
  challenges: [
    {
      id: 'es-c1',
      type: 'variant',
      difficulty: 'hard',
      question: 'Exponential search is related to the Two Crystal Balls problem because both:',
      options: [
        { id: 'a', text: 'Use exponentially growing probes before narrowing the search' },
        { id: 'b', text: 'Require unsorted input' },
        { id: 'c', text: 'Always need O(n) drops in the worst case' },
        { id: 'd', text: 'Avoid binary search entirely' },
      ],
      correct: ['a'],
      explanation: 'Chapter links optimal jump strategies (crystal balls) with exponential bracketing + binary refinement.',
    },
    {
      id: 'es-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement exponential search: bound-finding then binarySearchRange. Test on the chapter array for target 13.',
      rubric: [
        'Return -1 for empty array',
        'Handle arr[0] == target early',
        'Double i while in bounds and arr[i] <= target',
        'Binary search on [i/2, min(i, n-1)]',
        'Return correct index or -1',
      ],
      explanation: 'Combine the two phases from the chapter implementations. Target 13 should be found at index 5.',
    },
  ],
} satisfies QuizPack