import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/07-binary-search',
  topicId: 'binary-search',
  title: 'Binary Search',
  quiz: [
    {
      id: 'bs-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What precondition does classic binary search require?',
      options: [
        { id: 'a', text: 'The data must be sorted' },
        { id: 'b', text: 'The data must fit in GPU memory' },
        { id: 'c', text: 'The data must have no duplicates' },
        { id: 'd', text: 'The data must be a linked list' },
      ],
      correct: ['a'],
      explanation: 'Binary search eliminates half the search space by comparing to the middle — only works if order is meaningful.',
    },
    {
      id: 'bs-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'Time complexity of binary search on n elements:',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['b'],
      explanation: 'Halving the search space each step → at most log₂(n) steps.',
    },
    {
      id: 'bs-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'The Two Crystal Balls problem is a pure binary search problem with no modifications needed.',
      correct: false,
      explanation: 'Limited balls change the cost model. Optimal strategy uses decreasing jumps, not naive halving.',
    },
    {
      id: 'bs-q4',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'Why use `left + (right - left) / 2` instead of `(left + right) / 2`?',
      code: `int mid = left + (right - left) / 2;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Prevents integer overflow when left + right exceeds int max' },
        { id: 'b', text: 'Makes the algorithm O(1)' },
        { id: 'c', text: 'Required for unsorted arrays' },
        { id: 'd', text: 'It is slower but more accurate' },
      ],
      correct: ['a'],
      explanation: 'Famous bug in production code. Overflow in (left+right) can wrap negative.',
    },
    {
      id: 'bs-q5',
      type: 'trace',
      difficulty: 'medium',
      question: 'Sorted array [2, 5, 8, 12, 16, 23, 38, 56, 72, 91]. Search for 23. Which index is checked first (mid)?',
      options: [
        { id: 'a', text: 'Index 4 (value 16)' },
        { id: 'b', text: 'Index 5 (value 23)' },
        { id: 'c', text: 'Index 0 (value 2)' },
        { id: 'd', text: 'Index 9 (value 91)' },
      ],
      correct: ['a'],
      explanation: 'left=0, right=9, mid=(0+9)/2=4, arr[4]=16. 23>16, search right half.',
    },
    {
      id: 'bs-q6',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Finding a word in a dictionary ordered alphabetically. Best approach?',
      options: [
        { id: 'a', text: 'Binary search — O(log n) lookups' },
        { id: 'b', text: 'Linear scan from page 1' },
        { id: 'c', text: 'Random page jumps' },
        { id: 'd', text: 'Sort the dictionary first each time' },
      ],
      correct: ['a'],
      explanation: 'Sorted static data + repeated lookups = binary search textbook use case.',
    },
    {
      id: 'bs-q7',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'Binary search loop invariant: the target, if it exists, is always in the range [___, right].',
      correct: ['left', 'l'],
      explanation: 'We shrink [left, right] while maintaining that the answer lies within it.',
    },
    {
      id: 'bs-q8',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Which variants extend binary search? (Select all that apply)',
      options: [
        { id: 'a', text: 'Lower bound / first position where arr[i] >= target' },
        { id: 'b', text: 'Search on answer (binary search on the result space)' },
        { id: 'c', text: 'Search in rotated sorted array' },
        { id: 'd', text: 'Search in unsorted array in O(log n)' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Unsorted arrays cannot be binary searched in O(log n) without preprocessing.',
    },
  ],
  challenges: [
    {
      id: 'bs-c1',
      type: 'variant',
      difficulty: 'hard',
      question: 'Two crystal balls, 100 floors. Roughly how many drops in the optimal worst case?',
      options: [
        { id: 'a', text: 'About 14' },
        { id: 'b', text: 'About 50' },
        { id: 'c', text: 'About 7' },
        { id: 'd', text: 'About 100' },
      ],
      correct: ['a'],
      explanation: 'Solve x(x+1)/2 >= 100 → x ≈ 14. Decreasing jump strategy from the chapter.',
    },
    {
      id: 'bs-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement classic binary search returning index or -1. Test on the sorted array from q5 searching for 23.',
      rubric: [
        'Initialize left=0, right=n-1',
        'Loop while left <= right',
        'Compute mid without overflow',
        'Return mid on match; narrow left or right on mismatch',
        'Return -1 if loop ends without match',
      ],
      explanation: 'Open Playground from this page and implement. Trace should find index 5 for 23.',
    },
  ],
} satisfies QuizPack