import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/15-timsort',
  topicId: 'timsort',
  title: 'Timsort',
  quiz: [
    {
      id: 'ts-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What real-world property does Timsort exploit that pure merge/quicksort ignore?',
      options: [
        { id: 'a', text: 'Existing partial order — natural runs in data' },
        { id: 'b', text: 'Random uniform distribution only' },
        { id: 'c', text: 'Keys limited to 0–255' },
        { id: 'd', text: 'Linked-list-only storage' },
      ],
      correct: ['a'],
      explanation: 'Real data often contains already sorted or reverse-sorted runs; Timsort merges them instead of starting from scratch.',
    },
    {
      id: 'ts-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Best-case time complexity of Timsort on already sorted data:',
      options: [
        { id: 'a', text: 'O(n)' },
        { id: 'b', text: 'O(n log n)' },
        { id: 'c', text: 'O(n²)' },
        { id: 'd', text: 'O(1)' },
      ],
      correct: ['a'],
      explanation: 'Chapter table: fully sorted input can be recognized as one run — linear work.',
    },
    {
      id: 'ts-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Timsort is a stable sorting algorithm.',
      correct: true,
      explanation: 'Merge uses <= when picking from runs, preserving relative order of equal elements.',
    },
    {
      id: 'ts-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Which runtimes use Timsort (or derivatives) as described in the chapter?',
      options: [
        { id: 'a', text: 'Python list.sort() and Java Arrays.sort() for objects' },
        { id: 'b', text: 'C qsort only' },
        { id: 'c', text: 'GPU radix pipelines exclusively' },
        { id: 'd', text: 'Embedded bubble-sort-only firmware' },
      ],
      correct: ['a'],
      explanation: 'Python since 2002, Java 7+ for objects — also Android, V8, and others.',
    },
    {
      id: 'ts-q5',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Simplified educational Timsort combines which techniques? (Select all that apply)',
      options: [
        { id: 'a', text: 'Insertion sort on small runs (minRun ~32)' },
        { id: 'b', text: 'Bottom-up merge of doubling run sizes' },
        { id: 'c', text: '3-way quicksort partition only' },
        { id: 'd', text: 'Run detection and galloping (in production versions)' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'Educational version uses insertion + merge; production adds run detection, stack invariants, galloping.',
    },
    {
      id: 'ts-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'The educational implementation uses minRun = ___ as the threshold for insertion-sorting small chunks.',
      correct: ['32'],
      explanation: 'Chapter constant: sort runs of up to ~32–64 elements with insertion sort before merging.',
    },
    {
      id: 'ts-q7',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Timsort always uses O(1) extra space like heapsort.',
      correct: false,
      explanation: 'Chapter table lists O(n) auxiliary space for merges — stability and run merging need scratch buffers.',
    },
    {
      id: 'ts-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'In the simplified merge, why use `left[i] <= right[j]` instead of `<`?',
      code: `arr[k++] = left[i] <= right[j] ? left[i++] : right[j++];`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Stability: take from left when equal to preserve original order' },
        { id: 'b', text: 'Faster on random data only' },
        { id: 'c', text: 'Required for counting sort compatibility' },
        { id: 'd', text: 'Prevents integer overflow' },
      ],
      correct: ['a'],
      explanation: 'Stable merge rule: on tie, prefer left run element — core to Timsort’s stability guarantee.',
    },
  ],
  challenges: [
    {
      id: 'ts-c1',
      type: 'variant',
      difficulty: 'hard',
      question: 'Galloping mode in production Timsort activates when:',
      options: [
        { id: 'a', text: 'One run consistently wins comparisons — copy chunks in bulk instead of one-by-one' },
        { id: 'b', text: 'The array has fewer than 2 elements' },
        { id: 'c', text: 'All keys are negative' },
        { id: 'd', text: 'Merge sort stack overflows' },
      ],
      correct: ['a'],
      explanation: 'When one side dominates, galloping copies ranges efficiently — beyond the simplified chapter code.',
    },
    {
      id: 'ts-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement simplified Timsort: insertion-sort minRun chunks, then bottom-up merge doubling sizes.',
      rubric: [
        'Define minRun = 32',
        'Insertion sort each chunk [i, min(i+minRun-1, n-1)]',
        'Merge passes with size doubling from minRun',
        'Stable merge with <= tie-breaking',
        'Correct sort on mixed / partially sorted input',
      ],
      explanation: 'Shows how real-world sorters beat theoretical purity by exploiting data patterns.',
    },
  ],
} satisfies QuizPack