import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/30-floyd-warshall',
  topicId: 'floyd-warshall',
  title: 'Floyd-Warshall',
  quiz: [
    {
      id: 'fw-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What does Floyd-Warshall compute?',
      options: [
        { id: 'a', text: 'Shortest paths between all pairs of vertices' },
        { id: 'b', text: 'Single-source shortest path only' },
        { id: 'c', text: 'Minimum spanning tree' },
        { id: 'd', text: 'Maximum matching' },
      ],
      correct: ['a'],
      explanation: 'All-pairs shortest paths — dist[i][j] for every pair (i, j) in one O(V³) run.',
    },
    {
      id: 'fw-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Floyd-Warshall time and space complexity for V vertices:',
      options: [
        { id: 'a', text: 'O(V³) time, O(V²) space' },
        { id: 'b', text: 'O(V²) time, O(V) space' },
        { id: 'c', text: 'O(V × E) time, O(E) space' },
        { id: 'd', text: 'O(V⁴) time, O(V³) space' },
      ],
      correct: ['a'],
      explanation: 'Three nested loops over k, i, j — V³ updates on a V×V distance matrix.',
    },
    {
      id: 'fw-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'The core DP recurrence is: dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]).',
      correct: true,
      explanation: 'For each intermediate k, try routing from i to j through k — classic dynamic programming.',
    },
    {
      id: 'fw-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Dense graph with V ≤ 400, need all-pairs distances. Often prefer:',
      options: [
        { id: 'a', text: 'Floyd-Warshall — simple O(V³) code, all answers at once' },
        { id: 'b', text: 'BFS from each node on weighted graph' },
        { id: 'c', text: 'Kruskal\'s algorithm' },
        { id: 'd', text: 'Reservoir sampling' },
      ],
      correct: ['a'],
      explanation: 'For small dense graphs, Floyd-Warshall is competitive and gives every pair in one pass.',
    },
    {
      id: 'fw-q5',
      type: 'mcq',
      difficulty: 'hard',
      question: 'How do you detect a negative cycle after Floyd-Warshall?',
      options: [
        { id: 'a', text: 'Check if any dist[i][i] < 0' },
        { id: 'b', text: 'Check if dist[0][0] > 0' },
        { id: 'c', text: 'Count edges' },
        { id: 'd', text: 'Run topological sort' },
      ],
      correct: ['a'],
      explanation: 'Negative dist[i][i] means a negative-weight cycle through vertex i.',
    },
    {
      id: 'fw-q6',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Floyd-Warshall can handle negative edge weights (if no negative cycles).',
      correct: true,
      explanation: 'Unlike Dijkstra, the DP recurrence works with negative edges — but negative cycles make shortest paths undefined.',
    },
    {
      id: 'fw-q7',
      type: 'scenario',
      difficulty: 'hard',
      question: 'Transitive closure (can i reach j?) uses the Warshall variant with:',
      options: [
        { id: 'a', text: 'Boolean OR instead of min: reach[i][j] ||= reach[i][k] && reach[k][j]' },
        { id: 'b', text: 'Max instead of min' },
        { id: 'c', text: 'Division of distances' },
        { id: 'd', text: 'Sorting rows' },
      ],
      correct: ['a'],
      explanation: 'Same triple-loop structure — OR for reachability instead of min for distances.',
    },
    {
      id: 'fw-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'Initialization: dist[i][j] = 0 when i == j, else infinity if no edge. Why dist[i][i] = 0?',
      code: `dist[i,j] = i == j ? 0 : Inf;`,
      codeLang: 'pseudocode',
      options: [
        { id: 'a', text: 'Zero cost to stay at same vertex — base case for DP' },
        { id: 'b', text: 'Detect negative cycles immediately' },
        { id: 'c', text: 'Required for undirected graphs only' },
        { id: 'd', text: 'Makes all paths zero' },
      ],
      correct: ['a'],
      explanation: 'Self-distance is 0. After algorithm, dist[i][i] < 0 indicates negative cycle through i.',
    },
  ],
  challenges: [
    {
      id: 'fw-c1',
      type: 'trace',
      difficulty: 'hard',
      question: '3 nodes: edges 0→1 (w=1), 1→2 (w=2), 0→2 (w=10). After Floyd-Warshall, dist[0][2] = ?',
      options: [
        { id: 'a', text: '3' },
        { id: 'b', text: '10' },
        { id: 'c', text: '13' },
        { id: 'd', text: '2' },
      ],
      correct: ['a'],
      explanation: 'Direct 0→2 costs 10; via 0→1→2 costs 1+2=3. Floyd-Warshall finds the shorter route.',
    },
    {
      id: 'fw-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement Floyd-Warshall AllPairs: given V×V weight matrix, return dist matrix and hasNegativeCycle flag.',
      rubric: [
        'Clone input matrix as dist',
        'Triple loop: for k, for i, for j update dist[i][j]',
        'Use min(dist[i][j], dist[i][k] + dist[k][j]) with infinity guards',
        'After loops, check dist[i][i] < 0 for any i',
        'Return dist and negative cycle flag',
      ],
      explanation: 'Canonical triple loop. Test on 3-node example above — dist[0][2]=3.',
    },
  ],
} satisfies QuizPack