import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/42-z-algorithm',
  topicId: 'z-algorithm',
  title: 'Z-Algorithm',
  quiz: [
    {
      id: 'z-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Z[i] in the Z-array represents:',
      options: [
        { id: 'a', text: 'Length of longest substring starting at i matching a prefix of S' },
        { id: 'b', text: 'Number of occurrences of character i' },
        { id: 'c', text: 'Longest suffix ending at i' },
        { id: 'd', text: 'Hash of S[i..]' },
      ],
      correct: ['a'],
      explanation: 'Z[i] compares S[i..] against S[0..] — prefix-suffix match length from position i.',
    },
    {
      id: 'z-q2',
      type: 'mcq',
      difficulty: 'medium',
      question: 'Pattern matching with Z-algorithm typically uses:',
      options: [
        { id: 'a', text: 'combined = pattern + separator + text; match where Z[i] == pattern.Length' },
        { id: 'b', text: 'LPS table on text only' },
        { id: 'c', text: 'Rolling hash on pattern only' },
        { id: 'd', text: 'Suffix tree on text reversed' },
      ],
      correct: ['a'],
      explanation: 'Separator ensures no false prefix match crosses pattern/text boundary.',
    },
    {
      id: 'z-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'The Z-box [l, r] tracks a substring S[l..r] that matches prefix S[0..r-l].',
      correct: true,
      explanation: 'When i ≤ r, seed Z[i] from prior work inside the Z-box before extending.',
    },
    {
      id: 'z-q4',
      type: 'complexity',
      difficulty: 'medium',
      question: 'ComputeZ on string length n and pattern matching via Z:',
      options: [
        { id: 'a', text: 'O(n) for Z; O(n + m) total for search' },
        { id: 'b', text: 'O(n²) always' },
        { id: 'c', text: 'O(n log n)' },
        { id: 'd', text: 'O(m²)' },
      ],
      correct: ['a'],
      explanation: 'Each character advances r at most once — linear total work.',
    },
    {
      id: 'z-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'SmallestPeriod uses Z to find p where n % p == 0 and z[n-p] >= p. This detects:',
      options: [
        { id: 'a', text: 'Whether S repeats with period p' },
        { id: 'b', text: 'Longest palindrome' },
        { id: 'c', text: 'Edit distance' },
        { id: 'd', text: 'Graph diameter' },
      ],
      correct: ['a'],
      explanation: 'z[n-p] ≥ p means suffix at n-p aligns with prefix of length p — string periodicity.',
    },
    {
      id: 'z-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'When i ≤ r, Z[i] is seeded with min(r - i + 1, Z[i - ___]).',
      correct: ['l'],
      aliases: ['l'],
      explanation: 'Z[i-l] is the analogous prefix match inside the Z-box; cap by box boundary.',
    },
    {
      id: 'z-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Z vs KMP — which are true? (Select all)',
      options: [
        { id: 'a', text: 'Both achieve O(n + m) exact matching' },
        { id: 'b', text: 'Z preprocesses a combined string; KMP builds LPS on pattern' },
        { id: 'c', text: 'Z cannot help with period/border problems' },
        { id: 'd', text: 'Both are deterministic and collision-free' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'Z is also useful for periods and borders — competitive programming staple.',
    },
    {
      id: 'z-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'Why must the separator in `pattern + "\\0" + text` not appear in pattern or text?',
      code: `string combined = pattern + "\0" + text;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Prevents a match from spanning from text into pattern falsely' },
        { id: 'b', text: 'Speeds up sorting' },
        { id: 'c', text: 'Required for Unicode only' },
        { id: 'd', text: 'Enables rolling hash' },
      ],
      correct: ['a'],
      explanation: 'A unique sentinel ensures Z[i]==m only when text substring equals full pattern.',
    },
  ],
  challenges: [
    {
      id: 'z-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'S = "aabxaabx". What is Z[5] (0-indexed)?',
      options: [
        { id: 'a', text: '4' },
        { id: 'b', text: '3' },
        { id: 'c', text: '1' },
        { id: 'd', text: '0' },
      ],
      correct: ['a'],
      explanation: 'S[5..] = "aabx" matches prefix S[0..3] = "aabx" — length 4.',
    },
    {
      id: 'z-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'You need exact matching and also smallest string period. One algorithm choice?',
      options: [
        { id: 'a', text: 'Z-algorithm — handles both matching and period via same Z machinery' },
        { id: 'b', text: 'Rabin-Karp only' },
        { id: 'c', text: 'Binary search on length' },
        { id: 'd', text: 'Dijkstra' },
      ],
      correct: ['a'],
      explanation: 'Z is a Swiss-army linear string tool for matching, borders, and periods.',
    },
  ],
} satisfies QuizPack