import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/45-bit-manipulation',
  topicId: 'bit-manipulation',
  title: 'Bit Manipulation',
  quiz: [
    {
      id: 'bit-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Single Number: every element appears twice except one. Best technique:',
      options: [
        { id: 'a', text: 'XOR all elements — pairs cancel to 0' },
        { id: 'b', text: 'Sort and scan' },
        { id: 'c', text: 'Use a hash map only' },
        { id: 'd', text: 'Multiply all elements' },
      ],
      correct: ['a'],
      explanation: 'a ^ a = 0 and XOR is commutative — singleton remains.',
    },
    {
      id: 'bit-q2',
      type: 'mcq',
      difficulty: 'medium',
      question: 'Power of two check for n > 0:',
      options: [
        { id: 'a', text: 'n & (n - 1) == 0' },
        { id: 'b', text: 'n % 3 == 0' },
        { id: 'c', text: 'n | (n - 1) == 0' },
        { id: 'd', text: 'n ^ n == 1' },
      ],
      correct: ['a'],
      explanation: 'Powers of two have single bit set; n-1 clears that bit; AND yields 0.',
    },
    {
      id: 'bit-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Brian Kernighan popcount uses `n &= n - 1` to clear the lowest set bit each iteration.',
      correct: true,
      explanation: 'Each loop removes one 1-bit; iteration count equals popcount.',
    },
    {
      id: 'bit-q4',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Kernighan popcount loop iterations for integer n:',
      options: [
        { id: 'a', text: 'Equal to number of set bits in n' },
        { id: 'b', text: 'Always 32 regardless of n' },
        { id: 'c', text: 'O(log log n)' },
        { id: 'd', text: 'O(2^n)' },
      ],
      correct: ['a'],
      explanation: 'Each iteration clears exactly one set bit — at most word-width iterations.',
    },
    {
      id: 'bit-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Chess engine Stockfish uses bitboards because:',
      options: [
        { id: 'a', text: 'Bitwise ops generate attacks and moves in O(1) on 64-bit words' },
        { id: 'b', text: 'Bits replace minimax entirely' },
        { id: 'c', text: 'Arrays are banned in C++' },
        { id: 'd', text: 'Floating point is faster' },
      ],
      correct: ['a'],
      explanation: 'Each square/attack set as a bit enables blazing fast set operations.',
    },
    {
      id: 'bit-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'Isolate the lowest set bit: n & ___',
      correct: ['-n', '(-n)'],
      aliases: ['negative n', '- n'],
      explanation: 'Two\'s complement: n & -n extracts the rightmost 1-bit.',
    },
    {
      id: 'bit-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Which bit tricks are correct? (Select all)',
      options: [
        { id: 'a', text: 'Gray code: i ^ (i >> 1)' },
        { id: 'b', text: 'Subset iteration: for s := mask; s > 0; s = (s-1) & mask' },
        { id: 'c', text: 'XOR swap is recommended for production banking systems' },
        { id: 'd', text: 'n << k multiplies by 2^k for integers' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'XOR swap is interview trivia — aliasing and readability make it poor production practice.',
    },
    {
      id: 'bit-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'In bitmask N-Queens, what does `available & -available` do?',
      code: `int bit = available & -available;
available -= bit;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Picks one available column/diagonal position to place a queen' },
        { id: 'b', text: 'Clears all bits' },
        { id: 'c', text: 'Counts queens placed' },
        { id: 'd', text: 'Hashes the board' },
      ],
      correct: ['a'],
      explanation: 'Standard technique to iterate set bits in available — one queen per recursive branch.',
    },
  ],
  challenges: [
    {
      id: 'bit-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'XOR [4, 1, 2, 1, 2]. Result?',
      options: [
        { id: 'a', text: '4' },
        { id: 'b', text: '0' },
        { id: 'c', text: '1' },
        { id: 'd', text: '7' },
      ],
      correct: ['a'],
      explanation: '4 ^ 1 ^ 2 ^ 1 ^ 2 = 4 ^ (1^1) ^ (2^2) = 4.',
    },
    {
      id: 'bit-c2',
      type: 'debug',
      difficulty: 'hard',
      question: 'IsPowerOfTwo returns true for n=0. Bug?',
      options: [
        { id: 'a', text: 'Yes — must require n > 0; 0 is not a power of two' },
        { id: 'b', text: 'No — 0 is 2^∞' },
        { id: 'c', text: 'No — 0 has one bit set' },
        { id: 'd', text: 'Yes — should use n % 2' },
      ],
      correct: ['a'],
      explanation: 'Chapter implementation: `n > 0 && (n & (n-1)) == 0` — 0 fails the positivity guard.',
    },
  ],
} satisfies QuizPack