import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/38-longest-increasing-subsequence',
  topicId: 'longest-increasing-subsequence',
  title: 'Longest Increasing Subsequence',
  quiz: [
    {
      id: 'lis-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: '[10, 9, 2, 5, 3, 7, 101, 18] — what is the LIS length?',
      options: [
        { id: 'a', text: '4' },
        { id: 'b', text: '3' },
        { id: 'c', text: '5' },
        { id: 'd', text: '8' },
      ],
      correct: ['a'],
      explanation: 'One LIS is [2, 3, 7, 101] or [2, 5, 7, 101] — length 4, not contiguous.',
    },
    {
      id: 'lis-q2',
      type: 'mcq',
      difficulty: 'medium',
      question: 'In O(n²) DP, `dp[i]` means:',
      options: [
        { id: 'a', text: 'Length of longest increasing subsequence ending at index i' },
        { id: 'b', text: 'Length of LIS starting at index i' },
        { id: 'c', text: 'Number of increasing subsequences ending at i' },
        { id: 'd', text: 'Value of the smallest element in the LIS' },
      ],
      correct: ['a'],
      explanation: 'dp[i] = 1 + max(dp[j]) for j < i where nums[j] < nums[i]; answer = max(dp).',
    },
    {
      id: 'lis-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Patience sorting maintains `tails[len]` as the smallest possible tail of an increasing subsequence of that length.',
      correct: true,
      explanation: 'Smaller tails keep more extension options without reducing achievable lengths.',
    },
    {
      id: 'lis-q4',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Patience sorting / tails + binary search LIS complexity:',
      options: [
        { id: 'a', text: 'O(n log n) time, O(n) space' },
        { id: 'b', text: 'O(n²) time' },
        { id: 'c', text: 'O(n) time' },
        { id: 'd', text: 'O(2^n) time' },
      ],
      correct: ['a'],
      explanation: 'Each element does binary search on tails (length ≤ n) — O(n log n) total.',
    },
    {
      id: 'lis-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Git patience diff uses LIS to:',
      options: [
        { id: 'a', text: 'Find longest runs of unchanged lines between file versions' },
        { id: 'b', text: 'Compress repository objects' },
        { id: 'c', text: 'Sign commits cryptographically' },
        { id: 'd', text: 'Sort branches by date' },
      ],
      correct: ['a'],
      explanation: 'Patience diff finds stable matching lines — an LIS application on sequences.',
    },
    {
      id: 'lis-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'In patience sorting, if binary search finds `pos == tails.Count`, the current number ___ the LIS length.',
      correct: ['extends', 'extends', 'increases'],
      aliases: ['lengthens', 'grows'],
      explanation: 'Appending means we built a subsequence one longer than before.',
    },
    {
      id: 'lis-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Which are true about LIS approaches? (Select all)',
      options: [
        { id: 'a', text: 'O(n²) DP can reconstruct one LIS with a prev[] array' },
        { id: 'b', text: 'Patience sorting gives length only without extra structure' },
        { id: 'c', text: 'LIS must be a contiguous subarray' },
        { id: 'd', text: 'tails array stays sorted during patience sorting' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'LIS is a subsequence, not subarray. tails remains sorted for binary search.',
    },
    {
      id: 'lis-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What does replacing tails[idx] with num accomplish when idx < tails.Count?',
      code: `if (idx == tails.Count) tails.Add(num);
else tails[idx] = num;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Improves the tail for that length without shortening any achievable LIS' },
        { id: 'b', text: 'Removes the element from consideration' },
        { id: 'c', text: 'Decreases the final answer' },
        { id: 'd', text: 'Sorts the entire input array' },
      ],
      correct: ['a'],
      explanation: 'A smaller tail at length idx is strictly better for future extensions.',
    },
  ],
  challenges: [
    {
      id: 'lis-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'nums = [3, 1, 2]. O(n²) DP: what is max(dp)?',
      options: [
        { id: 'a', text: '2' },
        { id: 'b', text: '3' },
        { id: 'c', text: '1' },
        { id: 'd', text: '0' },
      ],
      correct: ['a'],
      explanation: 'dp = [1,1,2]: LIS [1,2] has length 2.',
    },
    {
      id: 'lis-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'Interview asks O(n log n) LIS length, then reconstruct one LIS. Practical approach?',
      options: [
        { id: 'a', text: 'Patience for length; separate O(n²) with prev[] for reconstruction' },
        { id: 'b', text: 'Sort the array and compare' },
        { id: 'c', text: 'Use BFS on all subsequences' },
        { id: 'd', text: 'Greedy: always pick the largest seen so far' },
      ],
      correct: ['a'],
      explanation: 'Common pattern: optimal length via tails; reconstruction needs predecessor tracking (often O(n²)).',
    },
  ],
} satisfies QuizPack