import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/29-bellman-ford',
  topicId: 'bellman-ford',
  title: 'Bellman-Ford',
  quiz: [
    {
      id: 'bf-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What advantage does Bellman-Ford have over Dijkstra?',
      options: [
        { id: 'a', text: 'Handles negative edge weights and detects negative cycles' },
        { id: 'b', text: 'Always faster on sparse graphs' },
        { id: 'c', text: 'Works only on DAGs' },
        { id: 'd', text: 'Requires no edge list' },
      ],
      correct: ['a'],
      explanation: 'Bellman-Ford relaxes all edges V-1 times — works with negatives; a Vth pass that improves means negative cycle.',
    },
    {
      id: 'bf-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Standard Bellman-Ford time complexity:',
      options: [
        { id: 'a', text: 'O(V × E)' },
        { id: 'b', text: 'O((V + E) log V)' },
        { id: 'c', text: 'O(V³)' },
        { id: 'd', text: 'O(E log E)' },
      ],
      correct: ['a'],
      explanation: 'V-1 rounds, each relaxing all E edges — O(V × E) worst case.',
    },
    {
      id: 'bf-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'After V-1 relaxation rounds, all simple shortest paths are found.',
      correct: true,
      explanation: 'A simple shortest path has at most V-1 edges; each round extends max path length by one.',
    },
    {
      id: 'bf-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Currency exchange rates modeled as -log(rate) edges. Negative cycle means:',
      options: [
        { id: 'a', text: 'Arbitrage opportunity — profit loop exists' },
        { id: 'b', text: 'Graph is disconnected' },
        { id: 'c', text: 'All rates are 1' },
        { id: 'd', text: 'Dijkstra would work' },
      ],
      correct: ['a'],
      explanation: 'Product of rates around cycle > 1 ↔ sum of -log rates < 0 ↔ negative cycle in transformed graph.',
    },
    {
      id: 'bf-q5',
      type: 'mcq',
      difficulty: 'hard',
      question: 'How is a negative-weight cycle detected after V-1 rounds?',
      options: [
        { id: 'a', text: 'One more full relaxation pass — any improvement means negative cycle' },
        { id: 'b', text: 'Check if dist[source] is zero' },
        { id: 'c', text: 'Count edges' },
        { id: 'd', text: 'Sort vertices topologically' },
      ],
      correct: ['a'],
      explanation: 'If distances still improve on round V, a path with V edges exists — must include a negative cycle.',
    },
    {
      id: 'bf-q6',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Early termination: if a full pass makes no updates, Bellman-Ford can stop early.',
      correct: true,
      explanation: 'No updates means convergence — distances are final even before V-1 rounds complete.',
    },
    {
      id: 'bf-q7',
      type: 'scenario',
      difficulty: 'hard',
      question: 'Cheapest Flights Within K Stops is related to Bellman-Ford because:',
      options: [
        { id: 'a', text: 'Exactly k relaxation rounds limit path to k+1 edges' },
        { id: 'b', text: 'It requires Floyd-Warshall' },
        { id: 'c', text: 'It is a trie problem' },
        { id: 'd', text: 'K stops means use BFS only' },
      ],
      correct: ['a'],
      explanation: 'Bellman-Ford round i finds shortest paths using at most i edges — run k+1 rounds for k stops.',
    },
    {
      id: 'bf-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'Why skip edges when dist[e.From] is infinity?',
      code: `if (dist[e.From] == double.PositiveInfinity) continue;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Unreachable source path — relaxation cannot improve dist[e.To]' },
        { id: 'b', text: 'Detect negative cycles' },
        { id: 'c', text: 'Optimization for undirected graphs only' },
        { id: 'd', text: 'Required for Dijkstra compatibility' },
      ],
      correct: ['a'],
      explanation: 'If u is unreachable (dist=∞), dist[u]+w is still ∞ — no point relaxing that edge.',
    },
  ],
  challenges: [
    {
      id: 'bf-c1',
      type: 'trace',
      difficulty: 'hard',
      question: '3 vertices: 0→1 (w=-1), 1→2 (w=-2), 2→0 (w=-3). Negative cycle from source 0?',
      options: [
        { id: 'a', text: 'Yes — total cycle weight is -6' },
        { id: 'b', text: 'No — all edges are negative but no cycle' },
        { id: 'c', text: 'Only if undirected' },
        { id: 'd', text: 'Dijkstra handles this' },
      ],
      correct: ['a'],
      explanation: '0→1→2→0 forms a directed cycle with weight -1 + -2 + -3 = -6. Shortest path is undefined.',
    },
    {
      id: 'bf-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement Bellman-Ford: given edge list, V, and source, return dist[] and hasNegativeCycle flag.',
      rubric: [
        'Initialize dist[source]=0, others to infinity',
        'Relax all edges V-1 times',
        'Early exit if a pass makes no updates',
        'Run one more pass — any improvement sets hasNegativeCycle',
        'Return dist and cycle flag',
      ],
      explanation: 'Canonical BF. Test on simple graph with negative edge but no cycle — correct distances returned.',
    },
  ],
} satisfies QuizPack