import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/10-bubble-sort',
  topicId: 'bubble-sort',
  title: 'Bubble Sort',
  quiz: [
    {
      id: 'bsort-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the core operation in bubble sort?',
      options: [
        { id: 'a', text: 'Compare and swap adjacent elements if out of order' },
        { id: 'b', text: 'Pick a pivot and partition the array' },
        { id: 'c', text: 'Merge two sorted halves' },
        { id: 'd', text: 'Insert each element into a sorted prefix' },
      ],
      correct: ['a'],
      explanation: 'Bubble sort repeatedly walks the list swapping neighbors — larger values "bubble" toward the end.',
    },
    {
      id: 'bsort-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'Worst-case time complexity of bubble sort on n elements:',
      options: [
        { id: 'a', text: 'O(n)' },
        { id: 'b', text: 'O(n log n)' },
        { id: 'c', text: 'O(n²)' },
        { id: 'd', text: 'O(2^n)' },
      ],
      correct: ['c'],
      explanation: 'Nested passes over shrinking ranges → about n²/2 comparisons in the worst case.',
    },
    {
      id: 'bsort-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'With the early-exit optimization, bubble sort runs in O(n) time on an already sorted array.',
      correct: true,
      explanation: 'One pass finds no swaps, swapped stays false, and the outer loop breaks immediately.',
    },
    {
      id: 'bsort-q4',
      type: 'trace',
      difficulty: 'medium',
      question: 'Array [5, 1, 4, 2]. After the first complete pass (j from 0 to n-i-1 with i=0), what is the array?',
      options: [
        { id: 'a', text: '[1, 4, 2, 5]' },
        { id: 'b', text: '[1, 2, 4, 5]' },
        { id: 'c', text: '[5, 1, 2, 4]' },
        { id: 'd', text: '[1, 5, 4, 2]' },
      ],
      correct: ['a'],
      explanation: '5↔1 → [1,5,4,2]; 5↔4 → [1,4,5,2]; 5↔2 → [1,4,2,5]. Largest element 5 is at the end.',
    },
    {
      id: 'bsort-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'You have ~20 stock prices that are almost sorted after a few out-of-order updates. Why might bubble sort be acceptable?',
      options: [
        { id: 'a', text: 'Tiny n makes O(n²) cheap; early exit helps nearly sorted data; code is simple to verify' },
        { id: 'b', text: 'It is always faster than quicksort for any size' },
        { id: 'c', text: 'It uses O(n) extra memory like merge sort' },
        { id: 'd', text: 'It guarantees O(n log n) worst case' },
      ],
      correct: ['a'],
      explanation: 'Chapter motivating example: simplicity and early termination trump raw asymptotics when n is very small.',
    },
    {
      id: 'bsort-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'Each pass of bubble sort places the largest unsorted element at the ___ of the active portion.',
      correct: ['end', 'right', 'back'],
      explanation: 'Like bubbles rising, the maximum sinks to the right end after each outer iteration.',
    },
    {
      id: 'bsort-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Which properties describe the optimized bubble sort from the chapter? (Select all that apply)',
      options: [
        { id: 'a', text: 'In-place (O(1) extra space)' },
        { id: 'b', text: 'Stable (equal elements keep relative order)' },
        { id: 'c', text: 'Only compares adjacent elements' },
        { id: 'd', text: 'Optimal for millions of random integers' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Adjacent swaps preserve stability and use constant space, but large random arrays need better algorithms.',
    },
    {
      id: 'bsort-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What does `if (!swapped) break` accomplish?',
      code: `if (!swapped) break; // already sorted`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Early termination when a pass performs zero swaps' },
        { id: 'b', text: 'Skips the final element only' },
        { id: 'c', text: 'Switches to insertion sort automatically' },
        { id: 'd', text: 'Resets the array to unsorted state' },
      ],
      correct: ['a'],
      explanation: 'Key optimization from the chapter: detect sorted state and avoid unnecessary passes.',
    },
  ],
  challenges: [
    {
      id: 'bsort-c1',
      type: 'variant',
      difficulty: 'hard',
      question: 'Cocktail shaker sort (bidirectional bubble) improves bubble sort by:',
      options: [
        { id: 'a', text: 'Alternating left-to-right and right-to-left passes to move small and large elements faster' },
        { id: 'b', text: 'Using a heap instead of adjacent swaps' },
        { id: 'c', text: 'Recursively halving the array' },
        { id: 'd', text: 'Counting digit frequencies' },
      ],
      correct: ['a'],
      explanation: 'Chapter mentions cocktail shaker as a bidirectional bubble variant for problems limited to adjacent swaps.',
    },
    {
      id: 'bsort-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement bubble sort with early-exit optimization. Sort [5, 1, 4, 2] and verify one pass leaves [1, 4, 2, 5].',
      rubric: [
        'Outer loop i from 0 to n-2',
        'Inner loop j to n-i-1 comparing arr[j] and arr[j+1]',
        'Swap when arr[j] > arr[j+1] and set swapped=true',
        'Break outer loop if swapped is false after a pass',
        'Fully sorted result [1, 2, 4, 5]',
      ],
      explanation: 'Hello-world of sorting — focus on adjacent compare/swap and the early-exit flag.',
    },
  ],
} satisfies QuizPack