import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/31-mst-kruskal-prim',
  topicId: 'mst',
  title: 'MST (Kruskal + Prim)',
  quiz: [
    {
      id: 'mst-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'A Minimum Spanning Tree (MST) of a connected weighted graph:',
      options: [
        { id: 'a', text: 'Connects all vertices with minimum total edge weight and no cycles' },
        { id: 'b', text: 'Finds shortest path between two nodes' },
        { id: 'c', text: 'Sorts vertices by weight' },
        { id: 'd', text: 'Always has V edges' },
      ],
      correct: ['a'],
      explanation: 'MST spans all V vertices with exactly V-1 edges and minimum total weight.',
    },
    {
      id: 'mst-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Kruskal\'s algorithm time complexity (dominated by sorting):',
      options: [
        { id: 'a', text: 'O(E log E)' },
        { id: 'b', text: 'O(V²)' },
        { id: 'c', text: 'O(V × E)' },
        { id: 'd', text: 'O(E + V log V) only if no sort' },
      ],
      correct: ['a'],
      explanation: 'Sort edges O(E log E); Union-Find operations are nearly O(1) amortized per edge.',
    },
    {
      id: 'mst-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Both Kruskal and Prim are greedy algorithms that produce correct MSTs.',
      correct: true,
      explanation: 'Both rely on the cut property — the lightest edge crossing any cut belongs to some MST.',
    },
    {
      id: 'mst-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Given an edge list for a sparse graph (E ≈ V). Natural MST algorithm?',
      options: [
        { id: 'a', text: 'Kruskal — sort edges and union-find' },
        { id: 'b', text: 'Floyd-Warshall' },
        { id: 'c', text: 'Topological sort' },
        { id: 'd', text: 'Trie insert' },
      ],
      correct: ['a'],
      explanation: 'Kruskal works directly on edge lists and excels on sparse graphs.',
    },
    {
      id: 'mst-q5',
      type: 'mcq',
      difficulty: 'hard',
      question: 'In Kruskal\'s, when do you add an edge (u, v, w) to the MST?',
      options: [
        { id: 'a', text: 'When Find(u) ≠ Find(v) — edge does not form a cycle' },
        { id: 'b', text: 'Always add the heaviest edge first' },
        { id: 'c', text: 'When u has maximum degree' },
        { id: 'd', text: 'Only if w is negative' },
      ],
      correct: ['a'],
      explanation: 'Union-Find checks if u and v are in different components; union if safe, skip if cycle.',
    },
    {
      id: 'mst-q6',
      type: 'mcq',
      difficulty: 'hard',
      question: 'Prim\'s algorithm grows the MST by always adding:',
      options: [
        { id: 'a', text: 'Cheapest edge from tree to a non-tree vertex' },
        { id: 'b', text: 'Random edge' },
        { id: 'c', text: 'Heaviest edge in the graph' },
        { id: 'd', text: 'Edge with most vertices' },
      ],
      correct: ['a'],
      explanation: 'Prim uses a min-heap of frontier edges — grow tree one cheapest connection at a time.',
    },
    {
      id: 'mst-q7',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Prim with binary heap runs in O(E log V) on sparse graphs.',
      correct: true,
      explanation: 'Each edge may enter heap once; heap ops O(log V). Dense array version is O(V²).',
    },
    {
      id: 'mst-q8',
      type: 'scenario',
      difficulty: 'hard',
      question: 'Minimum-cost fiber network connecting all cities. This is:',
      options: [
        { id: 'a', text: 'MST — connect all sites with minimum total cable length' },
        { id: 'b', text: 'Single-source shortest path' },
        { id: 'c', text: 'Topological sort of dependencies' },
        { id: 'd', text: 'Reservoir sampling' },
      ],
      correct: ['a'],
      explanation: 'Network design = classic MST application — Kruskal or Prim on city edge weights.',
    },
  ],
  challenges: [
    {
      id: 'mst-c1',
      type: 'trace',
      difficulty: 'hard',
      question: '4 vertices, edges: (0,1,1), (1,2,2), (0,2,3), (2,3,1). Kruskal MST total weight?',
      options: [
        { id: 'a', text: '4' },
        { id: 'b', text: '6' },
        { id: 'c', text: '7' },
        { id: 'd', text: '3' },
      ],
      correct: ['a'],
      explanation: 'Pick (0,1,1), (2,3,1), (1,2,2) — total 4. Skip (0,2,3) which would form no benefit over cheaper connections.',
    },
    {
      id: 'mst-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement Kruskal\'s MST: given n and undirected edge list, return MST edges and total weight using Union-Find.',
      rubric: [
        'Sort edges by weight ascending',
        'Initialize Union-Find with n components',
        'For each edge, if Find(u) ≠ Find(v), add to MST and Union(u,v)',
        'Stop when MST has n-1 edges',
        'Return MST edge list and sum of weights',
      ],
      explanation: 'Pair Kruskal with DSU. Test on 4-vertex example above — total weight 4.',
    },
  ],
} satisfies QuizPack