import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/22-bst-operations',
  topicId: 'bst-operations-22',
  title: 'BST Operations',
  quiz: [
    {
      id: 'bst22-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Chapter 22 redirects to chapter 21. Which operations are covered there?',
      options: [
        { id: 'a', text: 'Kth smallest, validate, LCA, insert, delete, floor, ceil' },
        { id: 'b', text: 'Dijkstra and Bellman-Ford only' },
        { id: 'c', text: 'Trie insert and prefix search' },
        { id: 'd', text: 'Reservoir sampling' },
      ],
      correct: ['a'],
      explanation: 'All BST operation content lives in chapter 21 — this page is a redirect stub.',
    },
    {
      id: 'bst22-q2',
      type: 'mcq',
      difficulty: 'medium',
      question: 'Floor of value x in a BST is:',
      options: [
        { id: 'a', text: 'The largest node value ≤ x' },
        { id: 'b', text: 'The smallest node value ≥ x' },
        { id: 'c', text: 'The root node always' },
        { id: 'd', text: 'The deepest leaf' },
      ],
      correct: ['a'],
      explanation: 'Floor walks like search, tracking the last node with value < x as candidate when going right.',
    },
    {
      id: 'bst22-q3',
      type: 'mcq',
      difficulty: 'medium',
      question: 'Ceil of value x in a BST is:',
      options: [
        { id: 'a', text: 'The smallest node value ≥ x' },
        { id: 'b', text: 'The largest node value ≤ x' },
        { id: 'c', text: 'The median of the tree' },
        { id: 'd', text: 'The inorder predecessor' },
      ],
      correct: ['a'],
      explanation: 'Ceil walks like search, tracking the last node with value > x as candidate when going left.',
    },
    {
      id: 'bst22-q4',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Deleting a BST node with zero children simply removes the node (returns null or child).',
      correct: true,
      explanation: 'Case 1: no children — detach the node. Case 2: one child — splice child up. Case 3: two children — successor swap.',
    },
    {
      id: 'bst22-q5',
      type: 'ordering',
      difficulty: 'hard',
      question: 'Order the three BST delete cases from simplest to most complex:',
      items: [
        { id: '1', text: 'Two children — copy successor, delete successor' },
        { id: '2', text: 'No children — remove node' },
        { id: '3', text: 'One child — replace with child' },
      ],
      correct: ['2', '3', '1'],
      explanation: 'No-child delete is trivial; one-child is a splice; two-child requires finding and removing the inorder successor.',
    },
    {
      id: 'bst22-q6',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Why do production systems like .NET SortedSet use red-black trees instead of plain BSTs?',
      options: [
        { id: 'a', text: 'Plain BSTs degrade to O(n) on sorted input; balanced trees stay O(log n)' },
        { id: 'b', text: 'BSTs cannot insert' },
        { id: 'c', text: 'Red-black trees use less memory always' },
        { id: 'd', text: 'BSTs only work on strings' },
      ],
      correct: ['a'],
      explanation: 'Sorted input skews plain BSTs; self-balancing trees maintain logarithmic height — see chapter 23.',
    },
    {
      id: 'bst22-q7',
      type: 'trace',
      difficulty: 'hard',
      question: 'BST with values {5,3,7,1,4}. Floor(4) = ? (exact match returns itself)',
      options: [
        { id: 'a', text: '4' },
        { id: 'b', text: '3' },
        { id: 'c', text: '5' },
        { id: 'd', text: '1' },
      ],
      correct: ['a'],
      explanation: '4 exists in the tree — floor of an exact match is the value itself.',
    },
    {
      id: 'bst22-q8',
      type: 'scenario',
      difficulty: 'hard',
      question: 'Database range query [lo, hi] on an ordered index most closely maps to which BST operation?',
      options: [
        { id: 'a', text: 'Inorder walk from floor(lo) collecting until > hi' },
        { id: 'b', text: 'Delete all nodes' },
        { id: 'c', text: 'Validate BST only' },
        { id: 'd', text: 'LCA of lo and hi only' },
      ],
      correct: ['a'],
      explanation: 'Range scans are inorder traversal between bounds — the same ordering BSTs provide in memory.',
    },
  ],
  challenges: [
    {
      id: 'bst22-c1',
      type: 'trace',
      difficulty: 'hard',
      question: 'BST: 20 root, left 10 (children 5,15), right 30. Ceil(12) = ?',
      options: [
        { id: 'a', text: '15' },
        { id: 'b', text: '10' },
        { id: 'c', text: '20' },
        { id: 'd', text: '5' },
      ],
      correct: ['a'],
      explanation: '12 is between 10 and 15 in the left subtree; smallest value ≥ 12 is 15.',
    },
    {
      id: 'bst22-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement BST Floor: return the largest value ≤ target, or indicate not found.',
      rubric: [
        'Walk from root comparing target to node value',
        'When node.Val < target, record as floor candidate and go right',
        'When node.Val > target, go left',
        'Return target immediately on exact match',
        'Return best floor candidate or not-found after walk',
      ],
      explanation: 'Floor/ceil are search variants with a running candidate. Test ceil(12) on the tree above → 15.',
    },
  ],
} satisfies QuizPack