import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/20-reservoir-sampling',
  topicId: 'reservoir-sampling',
  title: 'Reservoir Sampling',
  quiz: [
    {
      id: 'rs-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What problem does reservoir sampling solve?',
      options: [
        { id: 'a', text: 'Uniform random sample of k items from a stream without storing all data' },
        { id: 'b', text: 'Shortest path in a weighted graph' },
        { id: 'c', text: 'Sorting a linked list' },
        { id: 'd', text: 'Finding the MST of a graph' },
      ],
      correct: ['a'],
      explanation: 'One pass, O(k) memory — every stream element has equal probability k/n of being in the final sample.',
    },
    {
      id: 'rs-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Time and space complexity for sampling k items from a stream of n items:',
      options: [
        { id: 'a', text: 'O(n) time, O(k) space' },
        { id: 'b', text: 'O(n log n) time, O(n) space' },
        { id: 'c', text: 'O(k) time, O(1) space' },
        { id: 'd', text: 'O(n²) time, O(k) space' },
      ],
      correct: ['a'],
      explanation: 'Each of n items processed once; only the reservoir of size k is stored.',
    },
    {
      id: 'rs-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Algorithm R (k = 1) replaces the reservoir with item i with probability 1/i.',
      correct: true,
      explanation: 'For the first item, probability 1/1; for item i, replace with probability 1/i — gives uniform distribution over all n items.',
    },
    {
      id: 'rs-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'A billion-row log must be sampled to 1000 rows for analysis. You cannot load the full log. Which approach?',
      options: [
        { id: 'a', text: 'Reservoir sampling with k = 1000 in one streaming pass' },
        { id: 'b', text: 'Sort the entire log first' },
        { id: 'c', text: 'Take only the first 1000 rows' },
        { id: 'd', text: 'Hash map of all rows' },
      ],
      correct: ['a'],
      explanation: 'First 1000 rows are biased; reservoir sampling gives unbiased uniform random sample with bounded memory.',
    },
    {
      id: 'rs-q5',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What does `if (j < k) reservoir[j] = item` accomplish when j = rng.Next(i)?',
      code: `int j = rng.Next(i);
if (j < k) reservoir[j] = item;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Replace a random reservoir slot with probability k/i' },
        { id: 'b', text: 'Always append the new item' },
        { id: 'c', text: 'Sort the reservoir' },
        { id: 'd', text: 'Discard the item with probability k/i' },
      ],
      correct: ['a'],
      explanation: 'j is uniform in [0, i). P(j < k) = k/i — exactly the replacement probability needed for uniformity.',
    },
    {
      id: 'rs-q6',
      type: 'mcq',
      difficulty: 'medium',
      question: 'For the first k items in the stream (i ≤ k), what should the algorithm do?',
      options: [
        { id: 'a', text: 'Add each item directly to the reservoir' },
        { id: 'b', text: 'Skip them until i > k' },
        { id: 'c', text: 'Replace random slots' },
        { id: 'd', text: 'Sort them before adding' },
      ],
      correct: ['a'],
      explanation: 'Fill the reservoir with the first k items; replacement logic starts when i > k.',
    },
    {
      id: 'rs-q7',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Reservoir sampling requires knowing n (stream length) in advance.',
      correct: false,
      explanation: 'The algorithm is designed for unknown or infinite streams — only the current index i is needed.',
    },
    {
      id: 'rs-q8',
      type: 'scenario',
      difficulty: 'hard',
      question: 'Which real-world use case fits reservoir sampling best?',
      options: [
        { id: 'a', text: 'Telemetry sampling from a continuous log pipeline' },
        { id: 'b', text: 'Dijkstra shortest path' },
        { id: 'c', text: 'Topological sort of build dependencies' },
        { id: 'd', text: 'BST validation' },
      ],
      correct: ['a'],
      explanation: 'Datadog/Splunk-style pipelines sample huge streams with bounded memory — classic reservoir sampling.',
    },
  ],
  challenges: [
    {
      id: 'rs-c1',
      type: 'trace',
      difficulty: 'hard',
      question: 'Stream of 5 items, k = 2. After processing all 5, each item had what probability of being in the final sample?',
      options: [
        { id: 'a', text: '2/5 (40%)' },
        { id: 'b', text: '1/5 (20%)' },
        { id: 'c', text: '1/2 (50%)' },
        { id: 'd', text: 'Depends only on arrival order' },
      ],
      correct: ['a'],
      explanation: 'Reservoir sampling guarantees each of n items has probability k/n = 2/5 of appearing in the final sample.',
    },
    {
      id: 'rs-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement reservoir sampling for a generic stream: given Iterable<T>, k, and Random, return a uniform sample of size k.',
      rubric: [
        'Initialize empty reservoir; iterate stream with 1-based index i',
        'If reservoir size < k, append item',
        'Else pick j uniform in [0, i) and if j < k, replace reservoir[j]',
        'Return reservoir after stream ends',
        'Use proper randomness — j = rng.Next(i) in C# or rng.Intn(i) in Go',
      ],
      explanation: 'Algorithm R generalized to k > 1. Test with k=1 on [A,B,C] — each letter should have 1/3 chance.',
    },
  ],
} satisfies QuizPack