import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/23-self-balancing-trees',
  topicId: 'self-balancing-trees',
  title: 'Self-Balancing Trees',
  quiz: [
    {
      id: 'sbt-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Why do we need self-balancing trees instead of plain BSTs?',
      options: [
        { id: 'a', text: 'Plain BSTs can skew to O(n) height; balanced trees maintain O(log n)' },
        { id: 'b', text: 'BSTs cannot store integers' },
        { id: 'c', text: 'Balanced trees use less memory per node always' },
        { id: 'd', text: 'BSTs cannot delete nodes' },
      ],
      correct: ['a'],
      explanation: 'Sorted input creates a linked-list BST; red-black and AVL trees restore logarithmic height via rotations.',
    },
    {
      id: 'sbt-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Search/insert/delete time in a red-black or AVL tree with n nodes:',
      options: [
        { id: 'a', text: 'O(log n)' },
        { id: 'b', text: 'O(n)' },
        { id: 'c', text: 'O(1)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['a'],
      explanation: 'Both maintain height O(log n), so tree operations follow a single root-to-leaf path.',
    },
    {
      id: 'sbt-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Left and right rotations are shared primitives used by both red-black and AVL trees.',
      correct: true,
      explanation: 'Rotations restructure local subtrees without breaking BST ordering — foundation of all rebalancing.',
    },
    {
      id: 'sbt-q4',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'In augmented BST Select(k), what does leftSize represent?',
      code: `int leftSize = root.Left?.Size ?? 0;
if (k == leftSize + 1) return root.Val;
if (k <= leftSize) return Select(root.Left, k);`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Number of nodes in the left subtree' },
        { id: 'b', text: 'Height of the left child' },
        { id: 'c', text: 'Value of the leftmost node' },
        { id: 'd', text: 'Number of red nodes' },
      ],
      correct: ['a'],
      explanation: 'Size augmentation lets you find the k-th element in O(log n) by comparing k to left subtree size.',
    },
    {
      id: 'sbt-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Which production structure uses red-black trees under the hood?',
      options: [
        { id: 'a', text: '.NET SortedSet<T> and Java TreeMap' },
        { id: 'b', text: 'ArrayList' },
        { id: 'c', text: 'Hash table with chaining only' },
        { id: 'd', text: 'Stack' },
      ],
      correct: ['a'],
      explanation: 'Ordered collections in .NET and Java use red-black trees for O(log n) ordered operations.',
    },
    {
      id: 'sbt-q6',
      type: 'mcq',
      difficulty: 'hard',
      question: 'Order statistic Select(k) on an augmented balanced BST runs in:',
      options: [
        { id: 'a', text: 'O(log n)' },
        { id: 'b', text: 'O(n)' },
        { id: 'c', text: 'O(k)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['a'],
      explanation: 'Each step compares k to left subtree size and descends one level — height is O(log n).',
    },
    {
      id: 'sbt-q7',
      type: 'true-false',
      difficulty: 'medium',
      question: 'AVL trees are generally stricter about balance than red-black trees (tighter height bound).',
      correct: true,
      explanation: 'AVL enforces |balance| ≤ 1; red-black allows slightly looser balance with fewer rotations on insert.',
    },
    {
      id: 'sbt-q8',
      type: 'scenario',
      difficulty: 'hard',
      question: 'Linux kernel rbtree is used for scheduling and VMAs. What property makes balanced BSTs ideal here?',
      options: [
        { id: 'a', text: 'O(log n) insert/delete/search on ordered keys in dynamic kernel structures' },
        { id: 'b', text: 'O(1) prefix search' },
        { id: 'c', text: 'Guaranteed O(1) worst-case lookup' },
        { id: 'd', text: 'No pointers needed' },
      ],
      correct: ['a'],
      explanation: 'Kernel address spaces and timers need fast ordered map operations at scale — red-black trees deliver.',
    },
  ],
  challenges: [
    {
      id: 'sbt-c1',
      type: 'trace',
      difficulty: 'hard',
      question: 'Augmented tree: root size=7, left child size=3. Select(5) — which direction first?',
      options: [
        { id: 'a', text: 'Go right (k > leftSize + 1)' },
        { id: 'b', text: 'Go left' },
        { id: 'c', text: 'Return root' },
        { id: 'd', text: 'Full inorder traversal' },
      ],
      correct: ['a'],
      explanation: 'leftSize=3, k=5 > 4 — target is in right subtree. Recurse with k - leftSize - 1 = 1.',
    },
    {
      id: 'sbt-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement rightRotate on a BST node y (classic CLRS rotation). Return the new subtree root.',
      rubric: [
        'Let x = y.Left',
        'Set y.Left = x.Right',
        'Set x.Right = y',
        'Return x as new root of rotated subtree',
        'Preserve BST ordering (x < y, all in x.Right < y)',
      ],
      explanation: 'Rotations are local restructuring. Pair with leftRotate for AVL/RB fixups.',
    },
  ],
} satisfies QuizPack