import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/40-rabin-karp',
  topicId: 'rabin-karp',
  title: 'Rabin-Karp',
  quiz: [
    {
      id: 'rk-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Rabin-Karp compares substrings primarily using:',
      options: [
        { id: 'a', text: 'Rolling hash values with verification on match' },
        { id: 'b', text: 'LPS failure links' },
        { id: 'c', text: 'Right-to-left character comparison' },
        { id: 'd', text: 'Suffix arrays only' },
      ],
      correct: ['a'],
      explanation: 'Hash equality is a fast filter; confirm with direct compare to handle collisions.',
    },
    {
      id: 'rk-q2',
      type: 'true-false',
      difficulty: 'medium',
      question: 'If windowHash == patternHash, the substring always matches without further checks.',
      correct: false,
      explanation: 'Hashes can collide — always verify with character-by-character comparison.',
    },
    {
      id: 'rk-q3',
      type: 'mcq',
      difficulty: 'medium',
      question: 'Rolling hash slides the window by:',
      options: [
        { id: 'a', text: 'Subtract leading char × B^(m-1), multiply by B, add trailing char (mod M)' },
        { id: 'b', text: 'Recompute hash from scratch each position' },
        { id: 'c', text: 'XOR with random salt each step' },
        { id: 'd', text: 'Sort window characters' },
      ],
      correct: ['a'],
      explanation: 'O(1) update per slide after precomputing power = B^(m-1) mod M.',
    },
    {
      id: 'rk-q4',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Rabin-Karp average vs worst case (text n, pattern m):',
      options: [
        { id: 'a', text: 'Average O(n+m); worst O(n×m) if all hashes collide' },
        { id: 'b', text: 'Always O(n+m) deterministically' },
        { id: 'c', text: 'Always O(n×m)' },
        { id: 'd', text: 'O(n log n) always' },
      ],
      correct: ['a'],
      explanation: 'Collisions force full compares; large prime mod makes collisions rare in practice.',
    },
    {
      id: 'rk-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Plagiarism detection fingerprints document chunks with Rabin-Karp-style hashing because:',
      options: [
        { id: 'a', text: 'Rolling hashes enable fast screening of many windows at scale' },
        { id: 'b', text: 'Hashes prove semantic equivalence' },
        { id: 'c', text: 'It requires no storage' },
        { id: 'd', text: 'It only works on DNA' },
      ],
      correct: ['a'],
      explanation: 'Fingerprint windows, compare hash sets — classic large-scale duplicate detection.',
    },
    {
      id: 'rk-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'Double hashing uses two moduli so both must match before ___ — reduces adversarial collisions.',
      correct: ['verify', 'verification', 'verifying'],
      aliases: ['confirm', 'check'],
      explanation: 'Two independent hashes colliding is far less likely than one.',
    },
    {
      id: 'rk-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Rabin-Karp strengths? (Select all)',
      options: [
        { id: 'a', text: 'Natural extension to multiple patterns via hash set' },
        { id: 'b', text: 'Straightforward 2D template matching' },
        { id: 'c', text: 'Guaranteed no false positives' },
        { id: 'd', text: 'Used in rsync/Git rolling checksum ideas' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'False positives possible (hash collisions); verification eliminates false matches.',
    },
    {
      id: 'rk-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'Why precompute `power = B^(m-1) mod M` before the scan loop?',
      code: `for (int i = 0; i < m - 1; i++)
    power = power * Base % Mod;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Needed to subtract the contribution of the outgoing leftmost character' },
        { id: 'b', text: 'Stores the pattern length' },
        { id: 'c', text: 'Detects palindromes' },
        { id: 'd', text: 'Replaces the modulus' },
      ],
      correct: ['a'],
      explanation: 'Removing text[i] requires multiplying its coefficient (B^(m-1)) out of the rolling hash.',
    },
  ],
  challenges: [
    {
      id: 'rk-c1',
      type: 'design',
      difficulty: 'medium',
      question: 'You must match k patterns in one text pass. Best Rabin-Karp adaptation?',
      options: [
        { id: 'a', text: 'Hash all k patterns into a set; check membership per window hash' },
        { id: 'b', text: 'Run KMP k times always' },
        { id: 'c', text: 'Sort patterns alphabetically only' },
        { id: 'd', text: 'Use Boyer-Moore without preprocessing' },
      ],
      correct: ['a'],
      explanation: 'Single rolling window + hash set lookup — Rabin-Karp multi-pattern strength (Aho-Corasick is better at scale).',
    },
    {
      id: 'rk-c2',
      type: 'variant',
      difficulty: 'hard',
      question: 'Adversarial input might force many hash collisions. Mitigation?',
      options: [
        { id: 'a', text: 'Two independent moduli; verify only when both match' },
        { id: 'b', text: 'Use smaller modulus' },
        { id: 'c', text: 'Skip verification for speed' },
        { id: 'd', text: 'Use base 1' },
      ],
      correct: ['a'],
      explanation: 'Dual moduli dramatically reduce collision probability before expensive verify.',
    },
  ],
} satisfies QuizPack