import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/06-linear-search',
  topicId: 'linear-search',
  title: 'Linear Search',
  quiz: [
    {
      id: 'ls-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What does linear (sequential) search do?',
      options: [
        { id: 'a', text: 'Checks each element in order until a match is found or the list ends' },
        { id: 'b', text: 'Repeatedly halves a sorted search space' },
        { id: 'c', text: 'Jumps exponentially then binary searches' },
        { id: 'd', text: 'Hashes each element to an index' },
      ],
      correct: ['a'],
      explanation: 'Linear search is the baseline scan: no structure required, just compare element by element.',
    },
    {
      id: 'ls-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'Worst-case time complexity of linear search on n elements:',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['c'],
      explanation: 'In the worst case you examine every element once — O(n). Best case is O(1) if the target is first.',
    },
    {
      id: 'ls-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Linear search requires the data to be sorted.',
      correct: false,
      explanation: 'Linear search works on unsorted data. Sorting is a precondition for binary search, not linear search.',
    },
    {
      id: 'ls-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'You need to find one specific error string in a large unsorted log file with no index. Best first approach?',
      options: [
        { id: 'a', text: 'Linear scan through the file' },
        { id: 'b', text: 'Binary search without sorting' },
        { id: 'c', text: 'Exponential search on unsorted lines' },
        { id: 'd', text: 'Sort the entire file on every lookup' },
      ],
      correct: ['a'],
      explanation: 'Without order or a hash index, you must scan — linear search is the natural fallback.',
    },
    {
      id: 'ls-q5',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'When linear search does not find the target, it typically returns ___.',
      correct: ['-1'],
      explanation: 'The chapter implementations return -1 to signal "not found" after exhausting the array.',
    },
    {
      id: 'ls-q6',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'When is linear search a reasonable choice? (Select all that apply)',
      options: [
        { id: 'a', text: 'Very small arrays where setup cost of fancier structures is not worth it' },
        { id: 'b', text: 'Unsorted data with a single rare lookup' },
        { id: 'c', text: 'Linked lists where random access is unavailable' },
        { id: 'd', text: 'Millions of repeated lookups on static sorted data' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Repeated lookups on large sorted data should use binary search or a hash map, not linear scan.',
    },
    {
      id: 'ls-q7',
      type: 'trace',
      difficulty: 'medium',
      question: 'Array [4, 9, 2, 7, 1]. Search for 7. How many comparisons before returning the index?',
      options: [
        { id: 'a', text: '2' },
        { id: 'b', text: '3' },
        { id: 'c', text: '4' },
        { id: 'd', text: '5' },
      ],
      correct: ['c'],
      explanation: 'Compare 4 (no), 9 (no), 2 (no), 7 (yes) at index 3 — four comparisons.',
    },
    {
      id: 'ls-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'Why does this loop return immediately on match instead of continuing?',
      code: `for (int i = 0; i < arr.Length; i++) {
    if (arr[i] == target) return i;
}
return -1;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Standard linear search finds the first occurrence and stops early' },
        { id: 'b', text: 'The array must be sorted for this to work' },
        { id: 'c', text: 'It guarantees O(log n) performance' },
        { id: 'd', text: 'It collects all duplicate indices before returning' },
      ],
      correct: ['a'],
      explanation: 'First-match variant: stop as soon as target is found. A "find all" variant would continue scanning.',
    },
  ],
  challenges: [
    {
      id: 'ls-c1',
      type: 'variant',
      difficulty: 'hard',
      question: 'Sentinel linear search places the target at arr[n] so the inner loop avoids a bounds check each iteration. What precondition does it need?',
      options: [
        { id: 'a', text: 'Extra slot at index n (array size n+1) to store the sentinel' },
        { id: 'b', text: 'The array must be sorted ascending' },
        { id: 'c', text: 'Exactly one duplicate of the target' },
        { id: 'd', text: 'A hash function for the target' },
      ],
      correct: ['a'],
      explanation: 'Sentinel search is an optimization variant from the chapter — it needs one extra cell to park the sentinel value.',
    },
    {
      id: 'ls-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement linear search returning the index of the first match or -1. Test on [4, 9, 2, 7, 1] searching for 7 (expect index 3).',
      rubric: [
        'Loop from index 0 to n-1',
        'Return index immediately when arr[i] equals target',
        'Return -1 after the loop if no match',
        'No sorting or preprocessing required',
        'Correct result on the sample array',
      ],
      explanation: 'Open Playground from this page. This is the baseline every other search algorithm improves upon when structure exists.',
    },
  ],
} satisfies QuizPack