import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/24-trie-operations',
  topicId: 'trie-operations',
  title: 'Trie Operations',
  quiz: [
    {
      id: 'trie-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What type of queries do tries excel at?',
      options: [
        { id: 'a', text: 'Prefix-based string operations' },
        { id: 'b', text: 'Shortest path in weighted graphs' },
        { id: 'c', text: 'Sorting integers in O(n)' },
        { id: 'd', text: 'Matrix multiplication' },
      ],
      correct: ['a'],
      explanation: 'Tries walk one character at a time — insert, search, and prefix queries are O(m) where m is key length.',
    },
    {
      id: 'trie-q2',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Time to insert a word of length m into a trie:',
      options: [
        { id: 'a', text: 'O(m)' },
        { id: 'b', text: 'O(n) where n is total words' },
        { id: 'c', text: 'O(log m)' },
        { id: 'd', text: 'O(m log m)' },
      ],
      correct: ['a'],
      explanation: 'One step per character — follow or create child nodes along the path.',
    },
    {
      id: 'trie-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Search("apple") requires the final node to have IsEnd = true, not just that the path exists.',
      correct: true,
      explanation: 'Prefix "app" may exist as a path, but "apple" is only found if the terminal node is marked as end-of-word.',
    },
    {
      id: 'trie-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Autocomplete for prefix "prog" in a dictionary. Why use a trie over a hash map?',
      options: [
        { id: 'a', text: 'Trie walks prefix once then DFS collects completions; hash map has no efficient prefix query' },
        { id: 'b', text: 'Hash maps are always slower for exact match' },
        { id: 'c', text: 'Tries use O(1) space' },
        { id: 'd', text: 'Hash maps cannot store strings' },
      ],
      correct: ['a'],
      explanation: 'Hash maps excel at exact key lookup but cannot list all keys with a given prefix without scanning all keys.',
    },
    {
      id: 'trie-q5',
      type: 'mcq',
      difficulty: 'hard',
      question: 'Trie delete must sometimes remove nodes. When is a node removed after deletion?',
      options: [
        { id: 'a', text: 'When it is not an end-of-word and has no children' },
        { id: 'b', text: 'Always remove the entire trie' },
        { id: 'c', text: 'Never remove nodes' },
        { id: 'd', text: 'Only remove the root' },
      ],
      correct: ['a'],
      explanation: 'Post-order cleanup: unmark IsEnd, then prune leaf nodes that are not ends and have no children.',
    },
    {
      id: 'trie-q6',
      type: 'true-false',
      difficulty: 'medium',
      question: 'StartsWith("prog") returns true if the prefix path exists, even if no word ends at that node.',
      correct: true,
      explanation: 'StartsWith only checks that the prefix path exists — IsEnd is not required.',
    },
    {
      id: 'trie-q7',
      type: 'complexity',
      difficulty: 'hard',
      question: 'List all words with prefix p when k matches exist. Time complexity:',
      options: [
        { id: 'a', text: 'O(m + k)' },
        { id: 'b', text: 'O(m) only' },
        { id: 'c', text: 'O(k log k)' },
        { id: 'd', text: 'O(n × m)' },
      ],
      correct: ['a'],
      explanation: 'O(m) to find prefix node, O(k) to DFS and collect k matching words.',
    },
    {
      id: 'trie-q8',
      type: 'scenario',
      difficulty: 'hard',
      question: 'Word Search II on a board uses trie + DFS. What pruning does the trie enable?',
      options: [
        { id: 'a', text: 'Stop exploring paths when no trie child matches — avoid dead-end DFS branches' },
        { id: 'b', text: 'Sort the board first' },
        { id: 'c', text: 'Replace DFS with BFS always' },
        { id: 'd', text: 'Eliminate need for backtracking' },
      ],
      correct: ['a'],
      explanation: 'Trie acts as a prefix filter — if current path is not a prefix of any dictionary word, backtrack immediately.',
    },
  ],
  challenges: [
    {
      id: 'trie-c1',
      type: 'trace',
      difficulty: 'hard',
      question: 'Trie contains "cat", "car", "card". StartsWith("ca") and Search("car") results?',
      options: [
        { id: 'a', text: 'StartsWith true, Search true' },
        { id: 'b', text: 'StartsWith true, Search false' },
        { id: 'c', text: 'StartsWith false, Search true' },
        { id: 'd', text: 'Both false' },
      ],
      correct: ['a'],
      explanation: '"ca" is a valid prefix path; "car" exists with IsEnd marked at the terminal node.',
    },
    {
      id: 'trie-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement Trie with Insert, Search, and StartsWith for lowercase words.',
      rubric: [
        'TrieNode with children map and isEnd flag',
        'Insert: walk/create nodes per character, mark isEnd at last char',
        'Search: walk path, return true only if node exists and isEnd',
        'StartsWith: walk path, return true if full prefix path exists',
        'O(m) per operation where m is word/prefix length',
      ],
      explanation: 'Core trie API. Test: insert "app", "apple" — search("app") true, search("ap") false, startsWith("ap") true.',
    },
  ],
} satisfies QuizPack