import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/16-counting-sort',
  topicId: 'counting-sort',
  title: 'Counting Sort',
  quiz: [
    {
      id: 'cs-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What makes counting sort different from comparison-based sorts?',
      options: [
        { id: 'a', text: 'It counts occurrences per value instead of comparing pairs' },
        { id: 'b', text: 'It always uses a binary heap' },
        { id: 'c', text: 'It requires floating-point keys' },
        { id: 'd', text: 'It partitions around a random pivot' },
      ],
      correct: ['a'],
      explanation: 'Count frequencies in a range, then emit values in order — no element-to-element comparisons.',
    },
    {
      id: 'cs-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'Time complexity of counting sort on n elements with value range k:',
      options: [
        { id: 'a', text: 'O(n log n)' },
        { id: 'b', text: 'O(n + k)' },
        { id: 'c', text: 'O(n²)' },
        { id: 'd', text: 'O(k log k)' },
      ],
      correct: ['b'],
      explanation: 'One pass to count (O(n)) + traverse k buckets (O(k)) → O(n + k).',
    },
    {
      id: 'cs-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Counting sort works efficiently when k (the value range) is huge, e.g. sorting arbitrary 64-bit integers by value alone.',
      correct: false,
      explanation: 'Space and time blow up when k is enormous — counting sort needs a reasonable bounded range.',
    },
    {
      id: 'cs-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Sort 1 million ages (integers 0–150). Why beat comparison sorts?',
      options: [
        { id: 'a', text: 'O(n + 151) counting vs ~20M comparisons for O(n log n) sorts' },
        { id: 'b', text: 'Ages must be sorted with quicksort for stability' },
        { id: 'c', text: 'Comparison sorts cannot sort integers' },
        { id: 'd', text: 'Counting sort needs O(n²) time here' },
      ],
      correct: ['a'],
      explanation: 'Chapter canonical problem: small k makes counting sort dominate comparison-based approaches.',
    },
    {
      id: 'cs-q5',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'The count array typically has size ___ when values range from 0 to maxVal.',
      correct: ['maxVal+1', 'maxVal + 1'],
      explanation: 'C# implementation: `new int[maxVal + 1]` — one slot per possible value.',
    },
    {
      id: 'cs-q6',
      type: 'trace',
      difficulty: 'medium',
      question: 'Array [2, 5, 2, 1], maxVal=5. After counting (before output), what is count[2]?',
      options: [
        { id: 'a', text: '1' },
        { id: 'b', text: '2' },
        { id: 'c', text: '3' },
        { id: 'd', text: '0' },
      ],
      correct: ['b'],
      explanation: 'Two elements equal 2 → count[2] = 2.',
    },
    {
      id: 'cs-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Valid uses of counting sort include: (Select all that apply)',
      options: [
        { id: 'a', text: 'Sorting grades or byte values (small range)' },
        { id: 'b', text: 'Building block inside radix sort' },
        { id: 'c', text: 'Histogram bucketing in analytics' },
        { id: 'd', text: 'Arbitrary UUID strings lexicographically' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'UUIDs have huge key space — not a direct counting-sort target without encoding structure.',
    },
    {
      id: 'cs-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What does the nested loop `for v... for c...` in the simple implementation do?',
      code: `for (int v = 0; v <= maxVal; v++)
    for (int c = 0; c < count[v]; c++)
        arr[idx++] = v;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Writes each value v exactly count[v] times into sorted output' },
        { id: 'b', text: 'Partitions around pivot v' },
        { id: 'c', text: 'Heapifies the count array' },
        { id: 'd', text: 'Computes prefix sums only' },
      ],
      correct: ['a'],
      explanation: 'Direct placement variant: emit values in increasing order using frequency counts.',
    },
  ],
  challenges: [
    {
      id: 'cs-c1',
      type: 'variant',
      difficulty: 'hard',
      question: 'A stable counting sort variant uses prefix sums on count[] so that:',
      options: [
        { id: 'a', text: 'Elements are placed from right to left preserving original relative order for equal keys' },
        { id: 'b', text: 'The algorithm becomes in-place O(1) space' },
        { id: 'c', text: 'Negative numbers cannot be sorted' },
        { id: 'd', text: 'No auxiliary output array is needed ever' },
      ],
      correct: ['a'],
      explanation: 'Stable variant (used by radix sort): prefix sums give positions; reverse iteration keeps stability.',
    },
    {
      id: 'cs-c2',
      type: 'mini-code',
      difficulty: 'medium',
      question: 'Implement counting sort for integers 0..maxVal. Sort [2, 5, 2, 1] with maxVal=5.',
      rubric: [
        'Allocate count array of size maxVal+1',
        'Increment count[x] for each element',
        'Emit values in order using counts',
        'Handle the given maxVal parameter',
        'Output [1, 2, 2, 5]',
      ],
      explanation: 'Foundation for radix sort and fast bucketing when k is small.',
    },
  ],
} satisfies QuizPack