import type { QuizPack } from '../types'

export default {
  pagePath: '/algorithms/48-rate-limiting',
  topicId: 'rate-limiting',
  title: 'Rate Limiting Algorithms',
  quiz: [
    {
      id: 'rl-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Token bucket allows bursts by:',
      options: [
        { id: 'a', text: 'Accumulating tokens up to capacity; each request consumes one' },
        { id: 'b', text: 'Rejecting all requests until midnight' },
        { id: 'c', text: 'Sorting requests by size' },
        { id: 'd', text: 'Doubling limit at window boundaries' },
      ],
      correct: ['a'],
      explanation: 'Steady refill + capped bucket — burst up to capacity, then throttle.',
    },
    {
      id: 'rl-q2',
      type: 'mcq',
      difficulty: 'medium',
      question: 'Fixed window counter flaw at boundaries:',
      options: [
        { id: 'a', text: 'Client can send limit requests at 00:59 and limit more at 01:00 — 2× burst' },
        { id: 'b', text: 'Uses too much memory' },
        { id: 'c', text: 'Cannot run in O(1)' },
        { id: 'd', text: 'Tokens never refill' },
      ],
      correct: ['a'],
      explanation: 'Adjacent windows each allow full limit — boundary spike doubles effective rate.',
    },
    {
      id: 'rl-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Sliding window log stores timestamps and evicts entries older than the window for precise limiting.',
      correct: true,
      explanation: 'Queue of timestamps — count only requests within last window duration.',
    },
    {
      id: 'rl-q4',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Token bucket Allow() per request:',
      options: [
        { id: 'a', text: 'O(1) time and O(1) space per client' },
        { id: 'b', text: 'O(n) over total requests ever' },
        { id: 'c', text: 'O(log n)' },
        { id: 'd', text: 'O(k) where k is window size in seconds always' },
      ],
      correct: ['a'],
      explanation: 'Refill math on capacity, tokens, lastRefill — three values per client.',
    },
    {
      id: 'rl-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'API allows 100 req/min with bursts up to 20 extra. Best algorithm fit?',
      options: [
        { id: 'a', text: 'Token bucket — capacity 120, refill 100/60 per second' },
        { id: 'b', text: 'Fixed window only' },
        { id: 'c', text: 'Merge sort' },
        { id: 'd', text: 'Leaky bucket with zero leak rate' },
      ],
      correct: ['a'],
      explanation: 'Token bucket is the classic burst-tolerant rate limiter for API gateways.',
    },
    {
      id: 'rl-q6',
      type: 'fill-blank',
      difficulty: 'easy',
      question: 'Rejected requests should return HTTP ___ with Retry-After header.',
      correct: ['429', '429 Too Many Requests'],
      aliases: ['too many requests'],
      explanation: 'Standard semantics tell clients when to retry.',
    },
    {
      id: 'rl-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Distributed rate limiting patterns? (Select all)',
      options: [
        { id: 'a', text: 'Redis sorted set for sliding window timestamps' },
        { id: 'b', text: 'Lua script for atomic token bucket refill' },
        { id: 'c', text: 'Each gateway node with isolated counter — always accurate globally' },
        { id: 'd', text: 'Centralized rate-limit service' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'Isolated per-node counters under-count usage behind load balancers.',
    },
    {
      id: 'rl-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What does Refill() compute in TokenBucket?',
      code: `tokens = Math.Min(capacity, tokens + elapsed * refillRate);
lastRefill = now;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Adds tokens proportional to elapsed time, capped at capacity' },
        { id: 'b', text: 'Resets tokens to zero each call' },
        { id: 'c', text: 'Deletes expired requests from a queue' },
        { id: 'd', text: 'Sorts timestamps' },
      ],
      correct: ['a'],
      explanation: 'Continuous refill model — elapsed × rate, never exceed bucket capacity.',
    },
  ],
  challenges: [
    {
      id: 'rl-c1',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Need precise per-minute enforcement; memory per client acceptable. Choose:',
      options: [
        { id: 'a', text: 'Sliding window log' },
        { id: 'b', text: 'Fixed window only' },
        { id: 'c', text: 'No limiting' },
        { id: 'd', text: 'Token bucket with capacity 1 only' },
      ],
      correct: ['a'],
      explanation: 'Sliding window log is exact; token bucket trades precision for burst flexibility.',
    },
    {
      id: 'rl-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'Cloudflare-style O(1) memory with good sliding-window accuracy. Algorithm?',
      options: [
        { id: 'a', text: 'Sliding window counter — blend previous and current window counts' },
        { id: 'b', text: 'Store every request forever' },
        { id: 'c', text: 'Binary search on sorted timestamps per byte' },
        { id: 'd', text: 'Dijkstra on request graph' },
      ],
      correct: ['a'],
      explanation: 'Hybrid: count = prev×(1-elapsed/window) + curr — O(1) space, good accuracy.',
    },
  ],
} satisfies QuizPack