import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/01-array',
  topicId: 'array',
  title: 'Array',
  quiz: [
    {
      id: 'array-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Why does random access by index in an array achieve O(1) time?',
      options: [
        { id: 'a', text: 'Elements are stored in contiguous memory, enabling base + index × size addressing' },
        { id: 'b', text: 'Arrays automatically sort themselves on creation' },
        { id: 'c', text: 'Each element contains a pointer to the next element' },
        { id: 'd', text: 'The CPU pre-loads all array values into registers' },
      ],
      correct: ['a'],
      explanation: 'Contiguous layout lets the CPU compute any address in one arithmetic step.',
      misconception: 'Linked lists use pointers; arrays use contiguous blocks.',
    },
    {
      id: 'array-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'What is the time complexity of inserting an element at the beginning of an array?',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(n²)' },
      ],
      correct: ['c'],
      explanation: 'Every existing element must shift one position to make room at index 0.',
    },
    {
      id: 'array-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Arrays provide better CPU cache performance than linked lists for sequential access because of spatial locality.',
      correct: true,
      explanation: 'Contiguous memory means accessing arr[i] often brings arr[i+1] into cache for free.',
    },
    {
      id: 'array-q4',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'Which operations on a fixed-size array are O(1)? (Select all that apply)',
      options: [
        { id: 'a', text: 'Access by index' },
        { id: 'b', text: 'Update value at index' },
        { id: 'c', text: 'Search for a value (unsorted)' },
        { id: 'd', text: 'Insert at the end (when space is available)' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'Access, update, and append (when not full) are O(1). Unsorted search requires scanning all elements.',
    },
    {
      id: 'array-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'You know the exact number of pixels in a fixed-resolution game framebuffer (1920×1080) that never changes. Which structure fits best?',
      options: [
        { id: 'a', text: 'Fixed-size array' },
        { id: 'b', text: 'Linked list' },
        { id: 'c', text: 'Hash map' },
        { id: 'd', text: 'Skip list' },
      ],
      correct: ['a'],
      explanation: 'Known fixed size + need for fast index access = classic array use case.',
    },
    {
      id: 'array-q6',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'Searching for a value in an unsorted array requires ___ time in the worst case.',
      correct: ['O(n)', 'o(n)', 'linear'],
      aliases: ['n', 'on'],
      explanation: 'You may need to examine every element before finding the target or concluding it is absent.',
    },
    {
      id: 'array-q7',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What bug risk does this C-style pattern have?',
      code: `for (int i = 0; i <= arr.Length; i++) {
    total += arr[i];
}`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Index out of bounds — should be i < arr.Length' },
        { id: 'b', text: 'Infinite loop' },
        { id: 'c', text: 'Wrong time complexity' },
        { id: 'd', text: 'No bug — this is correct' },
      ],
      correct: ['a'],
      explanation: 'Using <= allows i to reach arr.Length, which is one past the last valid index (0 to Length-1).',
    },
    {
      id: 'array-q8',
      type: 'true-false',
      difficulty: 'medium',
      question: 'A Go slice is the same thing as a fixed-size array.',
      correct: false,
      explanation: 'Go arrays have fixed size at compile time. Slices are dynamic views over an underlying array (covered in the Dynamic Array chapter).',
    },
  ],
  challenges: [
    {
      id: 'array-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Array [10, 20, 30, 40, 50]. You delete index 2 (value 30). What does the array look like after shifting?',
      options: [
        { id: 'a', text: '[10, 20, 40, 50, _]' },
        { id: 'b', text: '[10, 20, 30, 40, 50]' },
        { id: 'c', text: '[10, 20, 40, 50, 50]' },
        { id: 'd', text: '[40, 50, 10, 20, 30]' },
      ],
      correct: ['a'],
      explanation: 'Elements after index 2 shift left. The last slot may hold a stale value or be cleared depending on implementation.',
    },
    {
      id: 'array-c2',
      type: 'variant',
      difficulty: 'hard',
      question: 'You need O(1) random access AND frequent insertions/deletions at BOTH ends. Which chapter should you read next?',
      options: [
        { id: 'a', text: 'Fixed Array (stay here)' },
        { id: 'b', text: 'Dynamic Array or Deque' },
        { id: 'c', text: 'Bloom Filter' },
        { id: 'd', text: 'HyperLogLog' },
      ],
      correct: ['b'],
      explanation: 'Raw fixed arrays are poor for frequent end mutations at scale. Dynamic arrays (slices) or deques handle this.',
    },
  ],
} satisfies QuizPack