import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/02-dynamic-array',
  topicId: 'dynamic-array',
  title: 'Dynamic Array',
  quiz: [
    {
      id: 'dynamic-array-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What three pieces of state does a dynamic array maintain internally?',
      options: [
        { id: 'a', text: 'Backing fixed array, logical count (size), and physical capacity' },
        { id: 'b', text: 'Head pointer, tail pointer, and a hash function' },
        { id: 'c', text: 'Left child, right child, and parent references' },
        { id: 'd', text: 'Only a linked list of nodes with no capacity limit' },
      ],
      correct: ['a'],
      explanation: 'The backing array holds elements; count is how many are in use; capacity is how much space is allocated.',
    },
    {
      id: 'dynamic-array-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'What is the amortized time complexity of appending to a dynamic array that doubles capacity when full?',
      options: [
        { id: 'a', text: 'O(1) amortized' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n) amortized' },
        { id: 'd', text: 'O(n²)' },
      ],
      correct: ['a'],
      explanation: 'Most appends are O(1); occasional O(n) resize is rare enough that the average cost per append stays O(1).',
    },
    {
      id: 'dynamic-array-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Doubling the capacity when a dynamic array is full is a common growth strategy that yields excellent amortized performance.',
      correct: true,
      explanation: '.NET List<T> doubles on resize; Go slices use similar growth policies. Doubling keeps resize frequency logarithmic.',
    },
    {
      id: 'dynamic-array-q4',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'Which operations on a dynamic array are O(1) in the worst case? (Select all that apply)',
      options: [
        { id: 'a', text: 'Access by index' },
        { id: 'b', text: 'Remove last element' },
        { id: 'c', text: 'Insert at the beginning' },
        { id: 'd', text: 'Update value at a known index' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'Index access and update are always O(1). Removing the last element only decrements count. Insert at index 0 requires shifting all elements — O(n).',
      misconception: 'Append is O(1) amortized, not worst-case O(1), because a full array triggers resize.',
    },
    {
      id: 'dynamic-array-q5',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'Repeatedly calling Insert(0, x) on a dynamic array can accidentally create ___ overall time complexity.',
      correct: ['O(n²)', 'o(n²)', 'quadratic', 'n squared'],
      aliases: ['n^2', 'on2'],
      explanation: 'Each insert at the front shifts every existing element. n inserts × O(n) shift each = O(n²).',
    },
    {
      id: 'dynamic-array-q6',
      type: 'scenario',
      difficulty: 'medium',
      question: 'You are building a hot path that will collect exactly 10,000 integers. Which initialization avoids unnecessary resizes?',
      options: [
        { id: 'a', text: 'Preallocate capacity: new List<int>(10000) or make([]int, 0, 10000)' },
        { id: 'b', text: 'Start with default capacity and let it grow organically' },
        { id: 'c', text: 'Use a linked list instead' },
        { id: 'd', text: 'Insert at index 0 for each element' },
      ],
      correct: ['a'],
      explanation: 'Pre-sizing to the expected count eliminates intermediate resize-and-copy operations in performance-critical code.',
    },
    {
      id: 'dynamic-array-q7',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'In Go, what memory pitfall does this pattern risk?',
      code: `big := make([]byte, 1_000_000)
window := big[0:100]  // keep only 100 bytes
// window is stored long-term; big is unreachable`,
      codeLang: 'go',
      options: [
        { id: 'a', text: 'The small slice keeps the entire 1 MB backing array alive (capacity leak)' },
        { id: 'b', text: 'Slice headers cannot share backing arrays' },
        { id: 'c', text: 'append on window always panics' },
        { id: 'd', text: 'No issue — Go automatically shrinks the backing array' },
      ],
      correct: ['a'],
      explanation: 'Go slices share backing arrays until append forces reallocation. A tiny window over a giant array pins all of it in memory.',
    },
    {
      id: 'dynamic-array-q8',
      type: 'matching',
      difficulty: 'medium',
      question: 'Match each language construct to its dynamic-array equivalent.',
      pairs: [
        { id: '1', left: 'C# List<T>', right: 'Dynamic array with doubling resize' },
        { id: '2', left: 'Go slice (append)', right: 'Header over backing array with growth policy' },
        { id: '3', left: 'Python list', right: 'Resizable contiguous sequence' },
        { id: '4', left: 'Java ArrayList', right: 'Dynamic array with amortized append' },
      ],
      explanation: 'All of these are dynamic-array implementations — the default "list" type in most languages.',
    },
  ],
  challenges: [
    {
      id: 'dynamic-array-c1',
      type: 'ordering',
      difficulty: 'medium',
      question: 'A dynamic array has count=4 and capacity=4. You call Add(99). Order the steps correctly.',
      items: [
        { id: 'a', text: 'Allocate a new backing array with capacity 8' },
        { id: 'b', text: 'Copy the 4 existing elements into the new array' },
        { id: 'c', text: 'Write 99 at index 4 and increment count to 5' },
        { id: 'd', text: 'Detect that count equals capacity (array is full)' },
      ],
      correct: ['d', 'a', 'b', 'c'],
      explanation: 'On a full array, resize happens before the write: detect fullness → allocate 2× → copy → append.',
    },
    {
      id: 'dynamic-array-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'You must remove an element from the middle of a large list where element order does NOT matter. What is the most efficient approach?',
      options: [
        { id: 'a', text: 'Swap the target with the last element, then remove the last — O(1)' },
        { id: 'b', text: 'Shift all elements after the target left — O(n) but preserves order' },
        { id: 'c', text: 'Rebuild the entire list from scratch' },
        { id: 'd', text: 'Use binary search to find the element' },
      ],
      correct: ['a'],
      explanation: 'The swap-with-last trick avoids shifting. It is a classic pattern when order is irrelevant (e.g., entity lists in game engines).',
    },
  ],
} satisfies QuizPack