import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/06-deque',
  topicId: 'deque',
  title: 'Deque',
  quiz: [
    {
      id: 'deque-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What does "deque" stand for and what is its defining capability?',
      options: [
        { id: 'a', text: 'Double-ended queue — efficient add/remove at both front and back' },
        { id: 'b', text: 'Deferred queue — delays all operations until commit' },
        { id: 'c', text: 'Distributed queue — spans multiple machines' },
        { id: 'd', text: 'Depth queue — processes deepest nodes first' },
      ],
      correct: ['a'],
      explanation: 'A deque (pronounced "deck") is the most flexible linear structure: O(1) operations at both ends.',
    },
    {
      id: 'deque-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'In a well-implemented circular-buffer deque, what is the time complexity of AddFront, AddBack, RemoveFront, and RemoveBack?',
      options: [
        { id: 'a', text: 'O(1) for all four' },
        { id: 'b', text: 'O(1) for back ops, O(n) for front ops' },
        { id: 'c', text: 'O(n) for all four' },
        { id: 'd', text: 'O(log n) for all four' },
      ],
      correct: ['a'],
      explanation: 'Circular array deques adjust head/tail with modulo — no shifting needed. All four end operations are O(1).',
    },
    {
      id: 'deque-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'A deque can behave as both a regular FIFO queue and a LIFO stack.',
      correct: true,
      explanation: 'Use AddBack/RemoveFront for queue behavior, or AddBack/RemoveBack for stack behavior — all O(1).',
    },
    {
      id: 'deque-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'The .NET ThreadPool and Go scheduler use deques internally. Why?',
      options: [
        { id: 'a', text: 'Work-stealing: owner pops one end, thief threads steal from the other' },
        { id: 'b', text: 'Deques automatically sort tasks by priority' },
        { id: 'c', text: 'Deques guarantee O(1) random access to any index' },
        { id: 'd', text: 'Deques replace the need for mutexes entirely' },
      ],
      correct: ['a'],
      explanation: 'Work-stealing schedulers use deques so each thread pushes/pops locally while thieves steal from the opposite end — excellent scalability.',
    },
    {
      id: 'deque-q5',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'Which problems are classic deque applications? (Select all that apply)',
      options: [
        { id: 'a', text: 'Sliding window maximum' },
        { id: 'b', text: 'Palindrome checking from both ends' },
        { id: 'c', text: 'Undo/redo with bidirectional navigation' },
        { id: 'd', text: 'Dijkstra shortest path on weighted graphs' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Sliding window max uses a monotonic deque of indices. Palindrome checks compare both ends. Undo/redo benefits from two-ended access. Dijkstra uses a priority queue, not a deque.',
    },
    {
      id: 'deque-q6',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'The sliding window maximum problem improves from O(nK) naive to ___ time using a monotonic deque.',
      correct: ['O(n)', 'o(n)', 'linear'],
      aliases: ['on'],
      explanation: 'Each element is added and removed from the deque at most once, giving a single O(n) pass over the array.',
    },
    {
      id: 'deque-q7',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'In this circular deque AddFront, why is the head update written this way?',
      code: `_head = (_head - 1 + Capacity) % Capacity;
_buffer[_head] = item;`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Adding Capacity before modulo handles wrap-around when head is at index 0' },
        { id: 'b', text: 'It sorts elements in descending order' },
        { id: 'c', text: 'It doubles the buffer size on every insert' },
        { id: 'd', text: 'It ensures the deque becomes a min-heap' },
      ],
      correct: ['a'],
      explanation: 'When head is 0, (_head - 1) is -1. Adding Capacity first makes it (Capacity-1), then modulo wraps to the last slot.',
    },
    {
      id: 'deque-q8',
      type: 'matching',
      difficulty: 'medium',
      question: 'Match each structure to its front-end operation complexity.',
      pairs: [
        { id: '1', left: 'Plain dynamic array (List)', right: 'Add/remove front: O(n)' },
        { id: '2', left: 'Deque (circular buffer)', right: 'Add/remove front: O(1)' },
        { id: '3', left: 'Stack', right: 'No front operations — back only' },
        { id: '4', left: 'Queue', right: 'Remove front O(1), no add-front' },
      ],
      explanation: 'This is why deques are preferred when both ends need fast mutation — plain arrays shift on front operations.',
    },
  ],
  challenges: [
    {
      id: 'deque-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Empty deque. Operations: AddBack(1), AddFront(2), AddBack(3), RemoveFront(). What is RemoveFront()\'s return value and what remains (front→back)?',
      options: [
        { id: 'a', text: 'Returns 2; deque is [1, 3]' },
        { id: 'b', text: 'Returns 1; deque is [2, 3]' },
        { id: 'c', text: 'Returns 3; deque is [2, 1]' },
        { id: 'd', text: 'Returns 2; deque is [3, 1]' },
      ],
      correct: ['a'],
      explanation: 'AddBack(1)→[1], AddFront(2)→[2,1], AddBack(3)→[2,1,3]. RemoveFront returns 2, leaving [1,3].',
    },
    {
      id: 'deque-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'For sliding window maximum (window size K), what invariant should the deque of indices maintain?',
      options: [
        { id: 'a', text: 'Indices in decreasing order of their corresponding array values' },
        { id: 'b', text: 'Indices in increasing order of their values' },
        { id: 'c', text: 'Indices sorted by position only, values ignored' },
        { id: 'd', text: 'All indices within the window in random order' },
      ],
      correct: ['a'],
      explanation: 'A decreasing-value deque ensures the front always holds the index of the current window maximum. Smaller values are popped from the back before they can become max.',
    },
  ],
} satisfies QuizPack