import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/09-hash-map',
  topicId: 'hash-map',
  title: 'Hash Map',
  quiz: [
    {
      id: 'hm-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What problem does a hash map solve compared to an unsorted array?',
      options: [
        { id: 'a', text: 'O(1) average-case key lookup instead of O(n) scan' },
        { id: 'b', text: 'Sorted iteration in O(1)' },
        { id: 'c', text: 'Guaranteed O(1) worst-case for all operations' },
        { id: 'd', text: 'Smaller memory than storing keys only' },
      ],
      correct: ['a'],
      explanation: 'Hash maps trade memory for speed — hash the key, jump to a bucket, find the value.',
      misconception: 'Worst-case can degrade to O(n) with bad hashing or many collisions.',
    },
    {
      id: 'hm-q2',
      type: 'true-false',
      difficulty: 'medium',
      question: 'A hash collision occurs when two different keys produce the same bucket index.',
      correct: true,
      explanation: 'Collisions are inevitable (pigeonhole principle). Resolution strategies: chaining or open addressing.',
    },
    {
      id: 'hm-q3',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'Which are valid collision resolution strategies? (Select all)',
      options: [
        { id: 'a', text: 'Separate chaining (linked list per bucket)' },
        { id: 'b', text: 'Open addressing (linear probing, quadratic probing)' },
        { id: 'c', text: 'Binary search on the key string' },
        { id: 'd', text: 'Robin Hood hashing' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'Chaining and open addressing are the two main families. Robin Hood is an open-addressing variant.',
    },
    {
      id: 'hm-q4',
      type: 'complexity',
      difficulty: 'easy',
      question: 'Average-case time complexity of Get/Set in a well-sized hash map:',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['a'],
      explanation: 'With low load factor and good hash distribution, bucket access is constant on average.',
    },
    {
      id: 'hm-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Redis uses hash tables for its key-value store. Why is a hash map the right abstraction?',
      options: [
        { id: 'a', text: 'Keys map to values in expected O(1) — perfect for GET/SET by key name' },
        { id: 'b', text: 'Keys are always sorted alphabetically' },
        { id: 'c', text: 'Hash maps use no memory overhead' },
        { id: 'd', text: 'Hash maps cannot store strings' },
      ],
      correct: ['a'],
      explanation: 'In-memory KV stores need fast arbitrary key lookup — hash tables are the default choice.',
    },
    {
      id: 'hm-q6',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'When a hash map exceeds its load factor threshold, it typically ___ to maintain performance.',
      correct: ['resize', 'rehash', 'rehashes', 'resizes', 'grow'],
      aliases: ['rehashing', 'resizing', 'expands'],
      explanation: 'Resize creates a larger table and rehashes all entries into new buckets.',
    },
    {
      id: 'hm-q7',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'Why is this a poor hash function for strings in a hash map?',
      code: `int Hash(string s) {
    return s.Length;  // only uses length
}`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Many different strings share the same length → massive collisions' },
        { id: 'b', text: 'Length is always O(n) to compute' },
        { id: 'c', text: 'It produces negative indices' },
        { id: 'd', text: 'It is actually a perfect hash function' },
      ],
      correct: ['a'],
      explanation: '"cat", "dog", "bat" all hash to 3. A good hash spreads keys across buckets uniformly.',
    },
    {
      id: 'hm-q8',
      type: 'true-false',
      difficulty: 'hard',
      question: 'Hash maps preserve insertion order by default in all languages.',
      correct: false,
      explanation: 'Classic hash maps do not guarantee order. LinkedHashMap (Java), dict (Python 3.7+), and ordered maps are special cases.',
    },
  ],
  challenges: [
    {
      id: 'hm-c1',
      type: 'design',
      difficulty: 'medium',
      question: 'You need to count word frequencies in a 10GB log file. Which structure for the counts?',
      options: [
        { id: 'a', text: 'Hash map: word → count' },
        { id: 'b', text: 'Sorted array searched with linear scan per word' },
        { id: 'c', text: 'Stack of all words' },
        { id: 'd', text: 'Binary heap keyed by word length only' },
      ],
      correct: ['a'],
      explanation: 'Frequency counting is the textbook hash map application — O(1) average increment per word.',
    },
    {
      id: 'hm-c2',
      type: 'trace',
      difficulty: 'hard',
      question: 'Table size 7, hash(k) = k % 7. Insert keys 14, 21, 8 using linear probing. Where does key 8 land?',
      options: [
        { id: 'a', text: 'Bucket 0' },
        { id: 'b', text: 'Bucket 1' },
        { id: 'c', text: 'Bucket 2' },
        { id: 'd', text: 'Bucket 3' },
      ],
      correct: ['c'],
      explanation: '14→0, 21→0 collides→1, 8→1 collides→2. Linear probing walks forward until an empty slot.',
    },
  ],
} satisfies QuizPack