import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/18-btree-bplustree',
  topicId: 'btree-bplustree',
  title: 'B-Tree and B+ Tree',
  quiz: [
    {
      id: 'btree-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'Why were B-Trees invented instead of using in-memory BSTs for database storage?',
      options: [
        { id: 'a', text: 'Disk random access is expensive — wide nodes minimize the number of disk reads' },
        { id: 'b', text: 'BSTs cannot store more than 1000 keys' },
        { id: 'c', text: 'B-Trees use less memory than BSTs in RAM' },
        { id: 'd', text: 'BSTs cannot be balanced' },
      ],
      correct: ['a'],
      explanation: 'B-Trees are short and wide: one disk page read brings hundreds of keys, keeping tree height very low.',
    },
    {
      id: 'btree-q2',
      type: 'true-false',
      difficulty: 'easy',
      question: 'In a B+ Tree, all actual data values are stored only in the leaf nodes.',
      correct: true,
      explanation: 'Internal nodes hold navigation keys only; leaves store records (or pointers) and are linked for range scans.',
    },
    {
      id: 'btree-q3',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Search in a B+ Tree of order m with n keys has time complexity:',
      options: [
        { id: 'a', text: 'O(log n)' },
        { id: 'b', text: 'O(log_m n)' },
        { id: 'c', text: 'O(m log n)' },
        { id: 'd', text: 'O(n)' },
      ],
      correct: ['b'],
      explanation: 'Each level branches by factor m, so height is O(log_m n) — typically only 3–5 levels for billions of rows.',
    },
    {
      id: 'btree-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'MySQL InnoDB uses a B+ Tree for its clustered index. A query needs all rows WHERE id BETWEEN 1000 AND 5000. What B+ Tree feature makes this efficient?',
      options: [
        { id: 'a', text: 'Leaf nodes linked as a doubly linked list for sequential traversal' },
        { id: 'b', text: 'Values stored in internal nodes for faster binary search' },
        { id: 'c', text: 'Each node holds exactly one key' },
        { id: 'd', text: 'Leaves are stored at random disk offsets' },
      ],
      correct: ['a'],
      explanation: 'After finding the start leaf, range scans walk the leaf linked list — O(log n + k) instead of re-descending the tree.',
    },
    {
      id: 'btree-q5',
      type: 'matching',
      difficulty: 'medium',
      question: 'Match each storage engine to its index structure (from the chapter).',
      pairs: [
        { id: '1', left: 'PostgreSQL', right: 'B+ tree indexes (plus GIN, GiST for special cases)' },
        { id: '2', left: 'MySQL InnoDB', right: 'Clustered and secondary indexes as B+ trees' },
        { id: '3', left: 'SQLite', right: 'Everything is B+ trees' },
        { id: '4', left: 'BoltDB / LMDB', right: 'B+ tree or B-tree key-value storage' },
      ],
      explanation: 'B+ trees dominate relational and embedded databases because they match disk page I/O patterns.',
    },
    {
      id: 'btree-q6',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'A B-Tree node of order m has at most ___ children.',
      correct: ['m'],
      aliases: ['M'],
      explanation: 'Order m means at most m children per node; internal nodes (except root) have at least ⌈m/2⌉ children.',
    },
    {
      id: 'btree-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Which are properties of a valid B-Tree? (Select all that apply)',
      options: [
        { id: 'a', text: 'All leaves are at the same level' },
        { id: 'b', text: 'A non-leaf node with k keys has k+1 children' },
        { id: 'c', text: 'Every internal node (except root) has at least ⌈m/2⌉ children' },
        { id: 'd', text: 'Tree height grows as O(n) in the worst case' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Balance invariants keep height O(log_m n), not O(n).',
    },
    {
      id: 'btree-q8',
      type: 'scenario',
      difficulty: 'hard',
      question: 'A table has 50 million rows. Why can point lookups still complete in milliseconds with a B+ Tree index?',
      options: [
        { id: 'a', text: 'Tree height is only 3–5 because each node fits a disk page with hundreds of keys' },
        { id: 'b', text: 'The database loads all rows into RAM on startup' },
        { id: 'c', text: 'B+ trees use hash functions for O(1) lookup' },
        { id: 'd', text: 'Inserts are forbidden after 1 million rows' },
      ],
      correct: ['a'],
      explanation: 'Wide nodes mean very shallow trees — a handful of disk reads even for huge datasets.',
    },
  ],
  challenges: [
    {
      id: 'btree-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'B+ Tree leaf keys (sorted, linked): L1=[10,20], L2=[35,50], L3=[60,80]. RangeQuery(25, 55) collects values in range. Which keys are included?',
      options: [
        { id: 'a', text: '35 and 50' },
        { id: 'b', text: '20, 35, and 50' },
        { id: 'c', text: '35 only' },
        { id: 'd', text: '10, 20, 35, and 50' },
      ],
      correct: ['a'],
      explanation: 'Keys 25–55: skip L1 (20 < 25), take 35 and 50 from L2, stop before 60 in L3.',
    },
    {
      id: 'btree-c2',
      type: 'variant',
      difficulty: 'hard',
      question: 'Compared to a Red-Black tree for an on-disk index, why does the chapter favor B+ Trees?',
      options: [
        { id: 'a', text: 'B+ Trees have wider nodes matching disk pages; RB trees are tall and cause many random reads' },
        { id: 'b', text: 'Red-Black trees cannot store integers' },
        { id: 'c', text: 'B+ Trees are always faster in pure in-memory workloads' },
        { id: 'd', text: 'Red-Black trees support range queries but B+ Trees do not' },
      ],
      correct: ['a'],
      explanation: 'RB trees are ~2 log n height with narrow nodes — fine in RAM, terrible when each node is a disk page read.',
    },
  ],
} satisfies QuizPack