import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/10-lru-cache',
  topicId: 'lru-cache',
  title: 'LRU Cache',
  quiz: [
    {
      id: 'lru-cache-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What does LRU stand for and what does it evict?',
      options: [
        { id: 'a', text: 'Least Recently Used — evicts the item accessed longest ago' },
        { id: 'b', text: 'Least Randomly Used — evicts a random item' },
        { id: 'c', text: 'Largest Recently Used — evicts the biggest item' },
        { id: 'd', text: 'Longest Retention Unit — evicts newest items first' },
      ],
      correct: ['a'],
      explanation: 'LRU keeps recently accessed items and removes the one that has been idle the longest when space runs out.',
    },
    {
      id: 'lru-cache-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'What is the time complexity of Get and Put in the classic HashMap + doubly linked list LRU design?',
      options: [
        { id: 'a', text: 'O(1) for both' },
        { id: 'b', text: 'O(log n) for both' },
        { id: 'c', text: 'O(1) Get, O(n) Put' },
        { id: 'd', text: 'O(n) for both' },
      ],
      correct: ['a'],
      explanation: 'The hash map gives O(1) key lookup; the doubly linked list gives O(1) move-to-front and evict-from-back.',
    },
    {
      id: 'lru-cache-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'The efficient LRU cache design combines a hash map for lookup with a doubly linked list for usage ordering.',
      correct: true,
      explanation: 'Naive "scan a list for least recent" is O(n). The two-structure design makes every operation O(1).',
    },
    {
      id: 'lru-cache-q4',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'Which real-world systems use LRU or LRU-like eviction? (Select all that apply)',
      options: [
        { id: 'a', text: 'Redis (allkeys-lru, volatile-lru)' },
        { id: 'b', text: 'Database buffer pools (PostgreSQL, MySQL)' },
        { id: 'c', text: 'CDN edge caches (Cloudflare, Fastly)' },
        { id: 'd', text: 'CPU L1/L2/L3 caches (variants and pseudo-LRU)' },
      ],
      correct: ['a', 'b', 'c', 'd'],
      explanation: 'LRU is one of the most important caching strategies — from browser caches to OS page caches to CPU hierarchies.',
    },
    {
      id: 'lru-cache-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Cache capacity=2. Operations: Put(A,1), Put(B,2), Get(A), Put(C,3). Which key is evicted?',
      options: [
        { id: 'a', text: 'B' },
        { id: 'b', text: 'A' },
        { id: 'c', text: 'C' },
        { id: 'd', text: 'None — cache has room' },
      ],
      correct: ['a'],
      explanation: 'After Get(A), order is B(oldest), A(recent). Put(C) evicts LRU → B. Cache holds A and C.',
    },
    {
      id: 'lru-cache-q6',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'In the doubly linked list LRU design, sentinel ___ nodes at head and tail simplify edge-case pointer updates.',
      correct: ['dummy', 'dummy nodes', 'sentinel', 'sentinel nodes'],
      aliases: ['head', 'tail'],
      explanation: 'Dummy head/tail sentinels eliminate null checks when inserting at boundaries or evicting the LRU node.',
    },
    {
      id: 'lru-cache-q7',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What does MoveToRecent accomplish when Get finds an existing key?',
      code: `private void MoveToRecent(Node node) {
    RemoveNode(node);
    AddToRecent(node);
}`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Unlinks the node from its current position and re-inserts it at the most-recently-used end' },
        { id: 'b', text: 'Deletes the node from the hash map' },
        { id: 'c', text: 'Sorts all nodes by key alphabetically' },
        { id: 'd', text: 'Evicts the node immediately' },
      ],
      correct: ['a'],
      explanation: 'Every access (Get or Put on existing key) must update recency. Remove + add-to-tail moves the node to the MRU position.',
    },
    {
      id: 'lru-cache-q8',
      type: 'true-false',
      difficulty: 'medium',
      question: 'LRU generally adapts better to real access patterns than FIFO because it considers recency, not just arrival order.',
      correct: true,
      explanation: 'FIFO can evict important data after a one-time spike. LRU keeps items that are actually being used.',
      misconception: 'LRU is not always optimal — scan-heavy workloads may favor LFU or hybrid policies.',
    },
  ],
  challenges: [
    {
      id: 'lru-cache-c1',
      type: 'ordering',
      difficulty: 'medium',
      question: 'Put a new key when the cache is at capacity. Order the eviction steps correctly.',
      items: [
        { id: 'a', text: 'Remove the LRU node (head.Next) from the doubly linked list' },
        { id: 'b', text: 'Remove the evicted key from the hash map' },
        { id: 'c', text: 'Create a new node and add it to the hash map' },
        { id: 'd', text: 'Insert the new node at the MRU (tail) end of the list' },
      ],
      correct: ['a', 'b', 'c', 'd'],
      explanation: 'Evict first (list + map), then insert the new entry at the recent end. Both structures must stay in sync.',
    },
    {
      id: 'lru-cache-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'A production cache needs thread-safe LRU with high read volume and occasional writes. Reasonable approach?',
      options: [
        { id: 'a', text: 'ReaderWriterLockSlim or careful locking around the map + list' },
        { id: 'b', text: 'No synchronization — hash maps are inherently thread-safe' },
        { id: 'c', text: 'Replace the linked list with a sorted array scanned on every Get' },
        { id: 'd', text: 'Use only a single global lock on every CPU core simultaneously' },
      ],
      correct: ['a'],
      explanation: 'Production LRU caches need explicit concurrency control. Reader-writer locks or lock-free designs are common; naive structures are not thread-safe.',
    },
  ],
} satisfies QuizPack