import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/19-skip-list',
  topicId: 'skip-list',
  title: 'Skip List',
  quiz: [
    {
      id: 'skiplist-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the core idea behind a skip list?',
      options: [
        { id: 'a', text: 'A layered linked list where higher levels act as express lanes for faster search' },
        { id: 'b', text: 'A perfectly balanced binary tree with rotations' },
        { id: 'c', text: 'A hash table with chaining' },
        { id: 'd', text: 'An array sorted on every insert' },
      ],
      correct: ['a'],
      explanation: 'Skip lists stack linked-list levels; search starts high and drops down, skipping large gaps.',
    },
    {
      id: 'skiplist-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'Expected time complexity for search in a skip list of n elements:',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['b'],
      explanation: 'Probabilistic level assignment gives expected O(log n) — similar to balanced trees.',
    },
    {
      id: 'skiplist-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Skip lists require complex rebalancing code like red-black tree rotations.',
      correct: false,
      explanation: 'Height is chosen randomly on insert — no rotation or rebalancing logic needed.',
      misconception: 'Skip lists trade guaranteed balance for probabilistic balance with simpler code.',
    },
    {
      id: 'skiplist-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Redis Sorted Sets (ZSET) combine a hash table with a skip list. Why both structures?',
      options: [
        { id: 'a', text: 'Hash gives O(1) member→score lookup; skip list gives O(log n) ordered-by-score operations' },
        { id: 'b', text: 'Hash stores scores; skip list stores member names only' },
        { id: 'c', text: 'Skip list replaces the hash for all operations' },
        { id: 'd', text: 'Two structures are needed only for persistence' },
      ],
      correct: ['a'],
      explanation: 'ZADD/ZRANK/ZRANGE need both fast member lookup and sorted-order traversal — dual structure design.',
    },
    {
      id: 'skiplist-q5',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'When inserting a skip list node, each additional level is promoted with roughly a ___% chance (p = 0.5).',
      correct: ['50', '50%'],
      aliases: ['fifty', 'half'],
      explanation: 'Coin-flip promotion: 50% height 1, 25% height 2, 12.5% height 3 — expected O(log n) levels.',
    },
    {
      id: 'skiplist-q6',
      type: 'ordering',
      difficulty: 'hard',
      question: 'Order the steps of skip list search for key 30 (levels 3→0):',
      items: [
        { id: '1', text: 'At each level, move forward while next key < target' },
        { id: '2', text: 'Start at the header at the highest active level' },
        { id: '3', text: 'Drop down one level and repeat' },
        { id: '4', text: 'At level 0, check if the next node\'s key equals the target' },
      ],
      correct: ['2', '1', '3', '4'],
      explanation: 'Search sweeps right at each level, then drops down — express lanes first, ground floor last.',
    },
    {
      id: 'skiplist-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Skip lists vs Red-Black trees — which statements are accurate? (Select all that apply)',
      options: [
        { id: 'a', text: 'Skip lists are simpler to implement' },
        { id: 'b', text: 'Skip lists are easier to make concurrent' },
        { id: 'c', text: 'Red-Black trees have guaranteed O(log n) worst case; skip lists can degrade to O(n) rarely' },
        { id: 'd', text: 'Skip lists always use less memory per element' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Skip lists use more pointers per node (multiple forward links). RB trees win on worst-case guarantees and memory.',
    },
    {
      id: 'skiplist-q8',
      type: 'true-false',
      difficulty: 'hard',
      question: 'LevelDB and RocksDB use a skip list as their in-memory MemTable write buffer.',
      correct: true,
      explanation: 'LSM-tree engines buffer writes in a sorted skip list before flushing to immutable SSTables on disk.',
    },
  ],
  challenges: [
    {
      id: 'skiplist-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Skip list level 0: 1→10→20→30→50. Level 1 express: 1→20→50. Searching for 30: at level 1 you reach 20, then drop. At level 0 you pass 10, 20. What is the next node examined?',
      options: [
        { id: 'a', text: '30' },
        { id: 'b', text: '50' },
        { id: 'c', text: '20 again' },
        { id: 'd', text: '10' },
      ],
      correct: ['a'],
      explanation: 'At level 0 after 20: forward[0] of 20 points to 30, which equals the target.',
    },
    {
      id: 'skiplist-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'You need a sorted in-memory set with fast insert/delete/range queries and plan heavy concurrent access. Why might you choose a skip list over a red-black tree?',
      options: [
        { id: 'a', text: 'Simpler lock-free or fine-grained locking on linked-list levels' },
        { id: 'b', text: 'Guaranteed O(1) worst-case search' },
        { id: 'c', text: 'No pointers needed — array-only storage' },
        { id: 'd', text: 'Automatic persistence to disk on every insert' },
      ],
      correct: ['a'],
      explanation: 'Linked-list layers allow localized updates without global tree rotations — a concurrency advantage cited in the chapter.',
    },
  ],
} satisfies QuizPack