import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/15-heap',
  topicId: 'heap',
  title: 'Heap',
  quiz: [
    {
      id: 'heap-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What property does a min-heap maintain?',
      options: [
        { id: 'a', text: 'Every parent ≤ its children' },
        { id: 'b', text: 'Left child < parent < right child (BST property)' },
        { id: 'c', text: 'All leaves are at the same depth' },
        { id: 'd', text: 'Elements are sorted in the array' },
      ],
      correct: ['a'],
      explanation: 'Heap property: parent is smaller (min-heap) or larger (max-heap) than children. Not fully sorted.',
    },
    {
      id: 'heap-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'Time to extract the minimum from a min-heap of n elements:',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['b'],
      explanation: 'Remove root, move last element to root, sift-down — height is log n.',
      misconception: 'Peeking at min is O(1); extracting requires restore heap property.',
    },
    {
      id: 'heap-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'A heap is typically stored in an array, with parent at i having children at 2i+1 and 2i+2.',
      correct: true,
      explanation: 'Array representation avoids pointer overhead. Index arithmetic maps tree structure.',
    },
    {
      id: 'heap-q4',
      type: 'mcq',
      difficulty: 'medium',
      question: 'Which operation is NOT efficient on a binary heap?',
      options: [
        { id: 'a', text: 'Find minimum (or maximum)' },
        { id: 'b', text: 'Insert a new element' },
        { id: 'c', text: 'Search for an arbitrary value' },
        { id: 'd', text: 'Extract min (or max)' },
      ],
      correct: ['c'],
      explanation: 'Arbitrary search is O(n) — heap only guarantees extremum at root.',
    },
    {
      id: 'heap-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Dijkstra\'s algorithm uses a priority queue. Why is a min-heap a natural fit?',
      options: [
        { id: 'a', text: 'Always need the unvisited node with smallest tentative distance' },
        { id: 'b', text: 'Heaps sort all edges automatically' },
        { id: 'c', text: 'Heaps store adjacency lists' },
        { id: 'd', text: 'Heaps guarantee O(1) arbitrary deletion' },
      ],
      correct: ['a'],
      explanation: 'Priority queue = "give me the minimum" repeatedly. Min-heap implements that efficiently.',
    },
    {
      id: 'heap-q6',
      type: 'true-false',
      difficulty: 'hard',
      question: 'After inserting 1 into min-heap [2, 4, 7] (array form), sift-up will move 1 all the way to the root.',
      correct: true,
      explanation: '1 is smaller than 2 (parent), so it sift-up swaps until reaching the root position.',
    },
    {
      id: 'heap-q7',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'Building a heap from n elements using bottom-up heapify runs in O(___) time.',
      correct: ['n', 'O(n)', 'o(n)'],
      aliases: ['linear'],
      explanation: 'Floyd\'s build-heap is O(n), not O(n log n) — a common interview trap.',
    },
    {
      id: 'heap-q8',
      type: 'true-false',
      difficulty: 'hard',
      question: 'Heapsort is an in-place O(n log n) sorting algorithm.',
      correct: true,
      explanation: 'Build max-heap, repeatedly swap root with end and heapify — O(n log n), O(1) extra space.',
    },
  ],
  challenges: [
    {
      id: 'heap-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Min-heap array: [1, 3, 2, 7, 5]. Extract-min. What is the new root after sift-down?',
      options: [
        { id: 'a', text: '2' },
        { id: 'b', text: '3' },
        { id: 'c', text: '5' },
        { id: 'd', text: '7' },
      ],
      correct: ['a'],
      explanation: 'Remove 1, move 7 to root, sift down: 7 swaps with smaller child 2 → root becomes 2.',
    },
    {
      id: 'heap-c2',
      type: 'mini-code',
      difficulty: 'hard',
      question: 'Implement sift-down for a min-heap at index i in an array. Verify with [1,3,2,7,5] after pop.',
      rubric: [
        'Compare node with both children',
        'Swap with smaller child if child is smaller',
        'Repeat until heap property restored or leaf reached',
        'Handle index bounds for children (2i+1, 2i+2)',
      ],
      explanation: 'Sift-down is the core heap operation. Implement in Playground and trace by hand.',
    },
  ],
} satisfies QuizPack