import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/16-priority-queue',
  topicId: 'priority-queue',
  title: 'Priority Queue',
  quiz: [
    {
      id: 'pq-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What distinguishes a priority queue from a regular FIFO queue?',
      options: [
        { id: 'a', text: 'The next item removed is determined by priority, not arrival order' },
        { id: 'b', text: 'Priority queues can only store integers' },
        { id: 'c', text: 'Priority queues always sort all elements on every insert' },
        { id: 'd', text: 'Priority queues guarantee O(1) removal from any position' },
      ],
      correct: ['a'],
      explanation: 'A priority queue always returns the highest-priority (or lowest, per definition) item next — not the oldest.',
    },
    {
      id: 'pq-q2',
      type: 'true-false',
      difficulty: 'easy',
      question: 'In practice, most priority queues are implemented using a binary heap.',
      correct: true,
      explanation: 'Binary heaps give O(log n) insert and extract with simple array storage — the standard backing structure.',
    },
    {
      id: 'pq-q3',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Using a binary heap, what is the time complexity of inserting a new element?',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['b'],
      explanation: 'Insert appends to the array and sift-up along the tree height — O(log n).',
      misconception: 'Peek is O(1); insert and extract require restoring the heap property.',
    },
    {
      id: 'pq-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Dijkstra\'s shortest-path algorithm repeatedly needs the unvisited vertex with the smallest tentative distance. Which structure fits best?',
      options: [
        { id: 'a', text: 'Min-priority queue (min-heap)' },
        { id: 'b', text: 'Stack' },
        { id: 'c', text: 'Deque' },
        { id: 'd', text: 'Bloom filter' },
      ],
      correct: ['a'],
      explanation: 'Dijkstra is "extract minimum repeatedly" — exactly what a min-priority queue provides.',
    },
    {
      id: 'pq-q5',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'Which are valid real-world uses of priority queues? (Select all that apply)',
      options: [
        { id: 'a', text: 'OS process/thread schedulers' },
        { id: 'b', text: 'Network packet QoS scheduling' },
        { id: 'c', text: 'Prim\'s minimum spanning tree algorithm' },
        { id: 'd', text: 'Exact membership testing with zero false positives' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Schedulers, routers, and graph algorithms all need "give me the best next item." Bloom filters solve a different problem.',
    },
    {
      id: 'pq-q6',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'When Dijkstra needs decrease-key on a plain binary heap, a common workaround is ___ deletion — insert a duplicate with the better priority and ignore stale entries when popped.',
      correct: ['lazy'],
      aliases: ['lazy deletion', 'lazy delete'],
      explanation: 'Lazy deletion avoids O(n) search in a heap: push the updated entry and skip outdated copies on pop.',
    },
    {
      id: 'pq-q7',
      type: 'scenario',
      difficulty: 'hard',
      question: 'You need the running median of a stream of numbers. Which pattern from the chapter applies?',
      options: [
        { id: 'a', text: 'Two heaps — max-heap for lower half, min-heap for upper half' },
        { id: 'b', text: 'Single min-heap storing all values' },
        { id: 'c', text: 'Sorted linked list with O(1) insert' },
        { id: 'd', text: 'Hash map counting frequencies' },
      ],
      correct: ['a'],
      explanation: 'The two-heap trick keeps the middle elements at the heap roots, giving O(log n) insert and O(1) median peek.',
    },
    {
      id: 'pq-q8',
      type: 'true-false',
      difficulty: 'hard',
      question: 'When priorities are small integers in a bounded range, bucket queues (Dial\'s algorithm) can achieve O(1) enqueue and dequeue.',
      correct: true,
      explanation: 'Bucket queues index by priority directly — ideal when the priority universe is small and known.',
    },
  ],
  challenges: [
    {
      id: 'pq-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Min-priority queue (smaller number = higher priority). Enqueue: ("low", 10), ("high", 1), ("medium", 5). Dequeue all three in order. What sequence is produced?',
      options: [
        { id: 'a', text: 'high, medium, low' },
        { id: 'b', text: 'low, medium, high' },
        { id: 'c', text: 'high, low, medium' },
        { id: 'd', text: 'medium, high, low' },
      ],
      correct: ['a'],
      explanation: 'Min-heap on priority: 1 ("high") first, then 5 ("medium"), then 10 ("low").',
    },
    {
      id: 'pq-c2',
      type: 'variant',
      difficulty: 'hard',
      question: 'Kubernetes scheduler and .NET\'s built-in PriorityQueue<TElement, TPriority> both rely on priority queues. You need decrease-key with frequent updates in C#. Which backing approach does the chapter suggest?',
      options: [
        { id: 'a', text: 'Lazy deletion with a binary heap, or SortedSet with explicit removal' },
        { id: 'b', text: 'Unsorted array with linear scan' },
        { id: 'c', text: 'Fibonacci heap is the only practical option' },
        { id: 'd', text: 'Trie for priority ordering' },
      ],
      correct: ['a'],
      explanation: 'Naive binary heaps lack efficient decrease-key; lazy deletion or a balanced BST (SortedSet) are the practical fixes.',
    },
  ],
} satisfies QuizPack