import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/17-trie',
  topicId: 'trie',
  title: 'Trie',
  quiz: [
    {
      id: 'trie-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'In a trie, what does each edge represent?',
      options: [
        { id: 'a', text: 'A single character' },
        { id: 'b', text: 'An entire word stored at the edge' },
        { id: 'c', text: 'A hash of the substring' },
        { id: 'd', text: 'The depth of the node in a BST' },
      ],
      correct: ['a'],
      explanation: 'Each edge is labeled with one character; the path from root to a node spells a prefix.',
    },
    {
      id: 'trie-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'What is the time complexity of searching for an exact word of length L in a trie?',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(L)' },
        { id: 'c', text: 'O(n) where n = number of words stored' },
        { id: 'd', text: 'O(n × L)' },
      ],
      correct: ['b'],
      explanation: 'You follow one edge per character — O(L), independent of how many words are in the trie.',
      misconception: 'Trie search depends on word length, not dictionary size.',
    },
    {
      id: 'trie-q3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'All words sharing the same prefix live in the same subtree of a trie.',
      correct: true,
      explanation: 'That shared-prefix locality is why tries excel at autocomplete and prefix queries.',
    },
    {
      id: 'trie-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'An IDE needs to suggest completions as the user types "app" from a dictionary of millions of symbols. Why is a trie a strong choice?',
      options: [
        { id: 'a', text: 'Navigate to the "app" prefix node, then enumerate words in that subtree' },
        { id: 'b', text: 'Hash the full query and look up O(1)' },
        { id: 'c', text: 'Binary search the entire dictionary on every keystroke' },
        { id: 'd', text: 'Store words in a min-heap sorted by length' },
      ],
      correct: ['a'],
      explanation: 'Prefix navigation is O(length of prefix); all matching words cluster in one subtree.',
    },
    {
      id: 'trie-q5',
      type: 'matching',
      difficulty: 'medium',
      question: 'Match each trie variant to its key characteristic.',
      pairs: [
        { id: '1', left: 'Radix / Patricia trie', right: 'Compresses single-child paths to save memory' },
        { id: '2', left: 'Binary trie', right: 'Each node has 0/1 children — used for IP routing' },
        { id: '3', left: 'Suffix trie/tree', right: 'Stores all suffixes of a string for advanced string algorithms' },
        { id: '4', left: 'Ternary search trie', right: 'Mixes BST and trie ideas with three-way branching' },
      ],
      explanation: 'Real systems pick variants based on memory, alphabet size, and query patterns.',
    },
    {
      id: 'trie-q6',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'The StartsWith(prefix) operation checks whether any word in the trie has the given ___.',
      correct: ['prefix'],
      aliases: ['Prefix'],
      explanation: 'StartsWith returns true if the prefix path exists — the node need not be marked as end-of-word.',
    },
    {
      id: 'trie-q7',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What does Search(word) require beyond finding the prefix path?',
      code: `public bool Search(string word) {
    var node = SearchPrefix(word);
    return node != null && node.IsEndOfWord;
}`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'The final node must be marked IsEndOfWord — "app" is not found if only "apple" exists' },
        { id: 'b', text: 'The word must be the longest key in the trie' },
        { id: 'c', text: 'All children of the final node must be empty' },
        { id: 'd', text: 'WordCount must equal the word length' },
      ],
      correct: ['a'],
      explanation: 'A prefix path can exist without the string being a complete stored word — IsEndOfWord distinguishes exact matches.',
    },
    {
      id: 'trie-q8',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Which are real-world trie applications mentioned in the chapter? (Select all that apply)',
      options: [
        { id: 'a', text: 'IP routing (longest prefix matching)' },
        { id: 'b', text: 'URL routing in web frameworks' },
        { id: 'c', text: 'DNA sequence matching (4-ary trie)' },
        { id: 'd', text: 'O(1) exact set membership with zero false positives' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Routers, web routers, and bioinformatics use trie variants. Zero-FP membership is a Bloom filter property.',
    },
  ],
  challenges: [
    {
      id: 'trie-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Insert "cat", "car", and "dog" into an empty trie. How many distinct nodes (excluding root) are created at minimum?',
      options: [
        { id: 'a', text: '7' },
        { id: 'b', text: '9' },
        { id: 'c', text: '6' },
        { id: 'd', text: '10' },
      ],
      correct: ['a'],
      explanation: 'Shared "ca" path: c→a→t and r (3 nodes). Separate "dog": d→o→g (3 nodes). Plus "a" under c = 7 total.',
    },
    {
      id: 'trie-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'A naive trie uses one node per character and consumes too much memory for a mobile keyboard dictionary. Which optimization from the chapter should you apply first?',
      options: [
        { id: 'a', text: 'Radix/Patricia compression to collapse single-child chains' },
        { id: 'b', text: 'Replace the trie with an unsorted array' },
        { id: 'c', text: 'Store each word as a full string only in a hash map with no prefix structure' },
        { id: 'd', text: 'Use a max-heap ordered by word length' },
      ],
      correct: ['a'],
      explanation: 'Radix/Patricia tries compress linear chains — a huge memory win while keeping prefix search fast.',
    },
  ],
} satisfies QuizPack