import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/28-cuckoo-filter',
  topicId: 'cuckoo-filter',
  title: 'Cuckoo Filter',
  quiz: [
    {
      id: 'cf-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is a Cuckoo Filter primarily used for?',
      options: [
        { id: 'a', text: 'Approximate set membership with support for deletion' },
        { id: 'b', text: 'Exact frequency counting of stream items' },
        { id: 'c', text: 'Cardinality estimation of unique elements' },
        { id: 'd', text: 'Spatial range queries on 2D rectangles' },
      ],
      correct: ['a'],
      explanation: 'Cuckoo filters are probabilistic membership structures like Bloom filters, but with deletion support.',
    },
    {
      id: 'cf-q2',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Unlike a standard Bloom filter, a Cuckoo Filter supports deleting items.',
      correct: true,
      explanation: 'Cuckoo filters store fingerprints that can be removed. Standard Bloom filters cannot delete without false negatives.',
    },
    {
      id: 'cf-q3',
      type: 'complexity',
      difficulty: 'medium',
      question: 'What is the average time complexity of Contains (query) in a Cuckoo Filter?',
      options: [
        { id: 'a', text: 'O(1) — checks exactly two possible bucket locations' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n) — scans entire table' },
        { id: 'd', text: 'O(d) where d is number of hash functions' },
      ],
      correct: ['a'],
      explanation: 'Each item has two possible bucket locations. Query checks both for the fingerprint.',
    },
    {
      id: 'cf-q4',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'Cuckoo filters store small ___ of items in buckets, derived from hashing.',
      correct: ['fingerprints', 'fingerprint'],
      aliases: ['fp', 'hash fingerprints'],
      explanation: 'Instead of setting bits, cuckoo filters store short fingerprint hashes in a table of buckets.',
    },
    {
      id: 'cf-q5',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'What advantages does a Cuckoo Filter have over a Bloom Filter? (Select all that apply)',
      options: [
        { id: 'a', text: 'Supports deletion' },
        { id: 'b', text: 'Often better space efficiency at low false-positive rates' },
        { id: 'c', text: 'Guarantees zero false positives' },
        { id: 'd', text: 'Based on cuckoo hashing relocation (kicking)' },
      ],
      correct: ['a', 'b', 'd'],
      explanation: 'Cuckoo filters can delete, often use less space at low FPR, and use cuckoo kicking. They still have false positives.',
    },
    {
      id: 'cf-q6',
      type: 'scenario',
      difficulty: 'medium',
      question: 'A storage engine needs fast "is this key possibly present?" checks AND the ability to remove stale keys. Best choice?',
      options: [
        { id: 'a', text: 'Cuckoo Filter' },
        { id: 'b', text: 'Standard Bloom Filter' },
        { id: 'c', text: 'HyperLogLog' },
        { id: 'd', text: 'Count-Min Sketch' },
      ],
      correct: ['a'],
      explanation: 'Bloom filters cannot delete. Cuckoo filters are being adopted as Bloom replacements in storage engines.',
    },
    {
      id: 'cf-q7',
      type: 'ordering',
      difficulty: 'hard',
      question: 'Order the Cuckoo Filter insert process when both candidate buckets are full.',
      items: [
        { id: '1', text: 'Compute fingerprint and two bucket indices (i1, i2)' },
        { id: '2', text: 'Try inserting fingerprint into i1 or i2' },
        { id: '3', text: 'Kick out an existing fingerprint and relocate it (cuckoo style)' },
        { id: '4', text: 'Repeat kicks up to MaxKicks; fail if table is full' },
      ],
      correct: ['1', '2', '3', '4'],
      explanation: 'Insert tries both buckets first. On overflow, random kicking relocates fingerprints until success or max kicks.',
    },
    {
      id: 'cf-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'How does Contains determine membership?',
      code: `ushort fp = Fingerprint(item);
int i1 = Hash1(item) & (bucketCount - 1);
int i2 = AltIndex(i1, fp);
return BucketContains(i1, fp) || BucketContains(i2, fp);`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Checks both alternate bucket locations for the item\'s fingerprint' },
        { id: 'b', text: 'Scans all buckets linearly for the full item string' },
        { id: 'c', text: 'Counts set bits in a bit array' },
        { id: 'd', text: 'Compares against a sorted suffix array' },
      ],
      correct: ['a'],
      explanation: 'Each item maps to exactly two buckets via Hash1 and AltIndex. Contains checks both for the fingerprint.',
    },
  ],
  challenges: [
    {
      id: 'cf-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Insert fails in both buckets i1 and i2. A kick evicts fingerprint A from i1, placing new fp B. What happens to A?',
      options: [
        { id: 'a', text: 'A is relocated to its alternate bucket via AltIndex (cuckoo kicking)' },
        { id: 'b', text: 'A is permanently deleted from the filter' },
        { id: 'c', text: 'A is merged with B into one fingerprint' },
        { id: 'd', text: 'A is stored in a separate overflow hash map' },
      ],
      correct: ['a'],
      explanation: 'Cuckoo kicking evicts an existing fingerprint and tries to place it in its alternate location, chaining kicks if needed.',
    },
    {
      id: 'cf-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'You need "how many unique search queries today?" at analytics scale. Which structure?',
      options: [
        { id: 'a', text: 'HyperLogLog — not Cuckoo Filter' },
        { id: 'b', text: 'Cuckoo Filter' },
        { id: 'c', text: 'Cuckoo Filter with deletion enabled' },
        { id: 'd', text: 'R-tree' },
      ],
      correct: ['a'],
      explanation: 'Cardinality (unique count) is HyperLogLog\'s job. Cuckoo filters answer membership, not distinct counts.',
    },
  ],
} satisfies QuizPack