import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/22-merkle-tree',
  topicId: 'merkle-tree',
  title: 'Merkle Tree',
  quiz: [
    {
      id: 'merkle-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What does each internal node in a Merkle tree store?',
      options: [
        { id: 'a', text: 'The hash of its children\'s hashes' },
        { id: 'b', text: 'The sum of its children\'s values' },
        { id: 'c', text: 'The lexicographically smaller child key' },
        { id: 'd', text: 'A pointer to disk without hashing' },
      ],
      correct: ['a'],
      explanation: 'Leaves hash data; each parent hashes the concatenation (or pair-hash) of its children up to the Merkle root.',
    },
    {
      id: 'merkle-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'How many hashes are needed to verify a Merkle proof for one leaf in a tree of n leaves?',
      options: [
        { id: 'a', text: 'O(1)' },
        { id: 'b', text: 'O(log n)' },
        { id: 'c', text: 'O(n)' },
        { id: 'd', text: 'O(n log n)' },
      ],
      correct: ['b'],
      explanation: 'One sibling hash per tree level — the proof path from leaf to root.',
    },
    {
      id: 'merkle-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'If any leaf data changes, the Merkle root hash will also change.',
      correct: true,
      explanation: 'Changed leaf hash propagates up through every ancestor to the root — the integrity fingerprint updates.',
    },
    {
      id: 'merkle-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'A Bitcoin light client (SPV wallet) wants to verify one transaction is in a block without downloading all transactions. What does it use?',
      options: [
        { id: 'a', text: 'Merkle proof — trusted root in block header + O(log n) sibling hashes' },
        { id: 'b', text: 'Download and hash every transaction linearly' },
        { id: 'c', text: 'Bloom filter with guaranteed zero false positives' },
        { id: 'd', text: 'B+ tree range scan of the block' },
      ],
      correct: ['a'],
      explanation: 'Block header stores only the 32-byte Merkle root; the client recomputes the root from a compact proof.',
    },
    {
      id: 'merkle-q5',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'Which systems use Merkle trees (or Merkle DAGs) per the chapter? (Select all that apply)',
      options: [
        { id: 'a', text: 'Git (content-addressable object storage)' },
        { id: 'b', text: 'Bitcoin/Ethereum blockchains' },
        { id: 'c', text: 'Cassandra/ScyllaDB anti-entropy between replicas' },
        { id: 'd', text: 'Standard FIFO task queues' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Git, blockchains, and distributed DBs use Merkle structures for integrity and efficient comparison.',
    },
    {
      id: 'merkle-q6',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'The single hash at the top of a Merkle tree is called the Merkle ___.',
      correct: ['root'],
      aliases: ['Root'],
      explanation: 'The Merkle root is a cryptographic fingerprint of the entire dataset.',
    },
    {
      id: 'merkle-q7',
      type: 'scenario',
      difficulty: 'hard',
      question: 'Two replicas of a large dataset need to find which subtrees differ without transferring everything. What is the efficient first step?',
      options: [
        { id: 'a', text: 'Compare Merkle roots; if equal, datasets match; if not, recurse into differing child hashes' },
        { id: 'b', text: 'Sort both datasets and diff byte-by-byte from the start' },
        { id: 'c', text: 'Use a trie for longest-prefix matching' },
        { id: 'd', text: 'Rebuild both trees from scratch on every sync' },
      ],
      correct: ['a'],
      explanation: 'Root comparison localizes differences to specific branches — core anti-entropy pattern in Cassandra/ScyllaDB.',
    },
    {
      id: 'merkle-q8',
      type: 'true-false',
      difficulty: 'hard',
      question: 'Ethereum uses a Merkle Patricia Trie (not a plain binary Merkle tree) for its world state.',
      correct: true,
      explanation: 'Merkle Patricia Trie combines Merkle hashing with trie-style key paths — an Ethereum-specific variant.',
    },
  ],
  challenges: [
    {
      id: 'merkle-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Merkle tree leaves: A, B, C, D. DataB is modified. Which hashes change?',
      options: [
        { id: 'a', text: 'H(B), H(AB), and Root only' },
        { id: 'b', text: 'All leaf hashes only' },
        { id: 'c', text: 'H(C) and H(D) only' },
        { id: 'd', text: 'Only the Root, not intermediate nodes' },
      ],
      correct: ['a'],
      explanation: 'Only the path from the changed leaf to root updates: H(B) → H(AB) → Root. H(C), H(D), H(CD) stay the same.',
    },
    {
      id: 'merkle-c2',
      type: 'debug',
      difficulty: 'hard',
      question: 'Merkle proof verification fails even though the data is correct. The verifier always hashes as HashPair(left, right) regardless of whether the leaf is a left or right child. What is the bug?',
      options: [
        { id: 'a', text: 'Hash order must flip based on index parity — left child hashes (hash, sibling), right child hashes (sibling, hash)' },
        { id: 'b', text: 'SHA-256 should be replaced with MD5' },
        { id: 'c', text: 'Proof must include all n leaf hashes' },
        { id: 'd', text: 'No bug — order never matters for cryptographic hashes' },
      ],
      correct: ['a'],
      explanation: 'Sibling position matters: concatenation order must match how the tree was built (see VerifyProof in the chapter).',
    },
  ],
} satisfies QuizPack