import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/25-disjoint-set-union-find',
  topicId: 'disjoint-set-union-find',
  title: 'Disjoint Set (Union-Find)',
  quiz: [
    {
      id: 'dsu-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What two operations does a Disjoint Set (Union-Find) support?',
      options: [
        { id: 'a', text: 'Find (which set?) and Union (merge sets)' },
        { id: 'b', text: 'Push and Pop' },
        { id: 'c', text: 'Enqueue and Dequeue by priority' },
        { id: 'd', text: 'Insert and Search by string prefix' },
      ],
      correct: ['a'],
      explanation: 'Union-Find tracks disjoint groups and answers connectivity queries between elements.',
    },
    {
      id: 'dsu-q2',
      type: 'complexity',
      difficulty: 'easy',
      question: 'With union by rank and path compression, Find and Union are effectively:',
      options: [
        { id: 'a', text: 'O(n) per operation' },
        { id: 'b', text: 'O(log n) per operation' },
        { id: 'c', text: 'O(α(n)) — inverse Ackermann, nearly constant' },
        { id: 'd', text: 'O(1) worst case guaranteed' },
      ],
      correct: ['c'],
      explanation: 'α(n) ≤ 4 for any n fitting in the observable universe — effectively constant in practice.',
    },
    {
      id: 'dsu-q3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Path compression makes every node on the find path point directly to the root.',
      correct: true,
      explanation: 'Flattening on Find dramatically reduces future traversal depth — one of the two key optimizations.',
    },
    {
      id: 'dsu-q4',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Kruskal\'s MST algorithm sorts edges by weight and adds them if endpoints are in different components. Which structure does it use?',
      options: [
        { id: 'a', text: 'Disjoint Set (Union-Find)' },
        { id: 'b', text: 'Min-heap only' },
        { id: 'c', text: 'Trie' },
        { id: 'd', text: 'Bloom filter' },
      ],
      correct: ['a'],
      explanation: 'Before adding edge (u,v), check Connected(u,v); if false, Union(u,v) and include the edge.',
    },
    {
      id: 'dsu-q5',
      type: 'matching',
      difficulty: 'medium',
      question: 'Match each Union-Find optimization to its purpose.',
      pairs: [
        { id: '1', left: 'Union by rank/size', right: 'Attach smaller tree under taller root to keep trees flat' },
        { id: '2', left: 'Path compression', right: 'Point all nodes on find path directly to root' },
        { id: '3', left: 'Connected(x, y)', right: 'Convenience check: Find(x) == Find(y)' },
        { id: '4', left: 'Initial state', right: 'Each element is its own parent (n singleton sets)' },
      ],
      explanation: 'Together, union by rank and path compression yield the near-constant amortized performance.',
    },
    {
      id: 'dsu-q6',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'In the initial DisjointSet(n) setup, parent[i] = ___ for all i.',
      correct: ['i'],
      aliases: ['itself'],
      explanation: 'Each element starts as its own set representative — parent[i] = i.',
    },
    {
      id: 'dsu-q7',
      type: 'mcq-multi',
      difficulty: 'hard',
      question: 'Which problems use Union-Find per the chapter? (Select all that apply)',
      options: [
        { id: 'a', text: 'Detecting redundant connections in a network' },
        { id: 'b', text: 'Account merge (same person, different emails)' },
        { id: 'c', text: 'Randomized maze generation' },
        { id: 'd', text: 'Computing shortest path distances in weighted graphs' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'Redundant connection, accounts merge, and maze generation are classic Union-Find problems. Shortest paths need BFS/Dijkstra.',
    },
    {
      id: 'dsu-q8',
      type: 'true-false',
      difficulty: 'hard',
      question: 'Union-Find can efficiently undo a Union operation without extra bookkeeping.',
      correct: false,
      explanation: 'The chapter notes Union-Find is destructive — undo requires rollback structures or a different approach.',
      misconception: 'Union-Find merges are one-way; path compression further complicates naive undo.',
    },
  ],
  challenges: [
    {
      id: 'dsu-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'DisjointSet(4). Union(0,1), Union(2,3), Union(1,2). How many distinct connected components remain?',
      options: [
        { id: 'a', text: '1' },
        { id: 'b', text: '2' },
        { id: 'c', text: '3' },
        { id: 'd', text: '4' },
      ],
      correct: ['a'],
      explanation: 'Union(0,1) → {0,1}. Union(2,3) → {2,3}. Union(1,2) merges both → all four in one component.',
    },
    {
      id: 'dsu-c2',
      type: 'mini-code',
      difficulty: 'hard',
      question: 'Implement Find(x) with path compression and Union(x,y) with union by rank. Trace Kruskal on edges [(0,1,10),(0,2,6),(0,3,5),(1,3,15),(2,3,4)].',
      rubric: [
        'Find recursively sets parent[x] = Find(parent[x]) when x is not root',
        'Union attaches lower-rank root under higher-rank root',
        'Equal ranks: pick one root and increment its rank',
        'Kruskal: process edges in ascending weight, skip if Connected',
      ],
      explanation: 'MST weight = 10+5+4 = 19 (edges (0,3), (2,3), (0,1) after sorting by weight).',
    },
  ],
} satisfies QuizPack