import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/26-hyperloglog',
  topicId: 'hyperloglog',
  title: 'HyperLogLog',
  quiz: [
    {
      id: 'hll-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What question does HyperLogLog answer?',
      options: [
        { id: 'a', text: 'How many unique (distinct) items are in a stream?' },
        { id: 'b', text: 'How many times has a specific item appeared?' },
        { id: 'c', text: 'Whether an item has been seen before (membership)' },
        { id: 'd', text: 'The exact sorted order of all items' },
      ],
      correct: ['a'],
      explanation: 'HyperLogLog estimates cardinality — the count of distinct elements — not frequency or membership.',
      misconception: 'Count-Min Sketch estimates frequency; Bloom/Cuckoo filters answer membership.',
    },
    {
      id: 'hll-q2',
      type: 'true-false',
      difficulty: 'easy',
      question: 'HyperLogLog uses the longest run of leading zeros in item hashes as a probabilistic signal for cardinality.',
      correct: true,
      explanation: 'Uniformly hashed items: longer leading-zero runs suggest you have seen roughly 2^zeros distinct items.',
    },
    {
      id: 'hll-q3',
      type: 'complexity',
      difficulty: 'medium',
      question: 'With precision parameter p, what are the typical time complexities of Add and Estimate?',
      options: [
        { id: 'a', text: 'Add O(1), Estimate O(2^p)' },
        { id: 'b', text: 'Add O(log n), Estimate O(1)' },
        { id: 'c', text: 'Both O(n)' },
        { id: 'd', text: 'Add O(2^p), Estimate O(1)' },
      ],
      correct: ['a'],
      explanation: 'Add updates one register in O(1). Estimate scans all m = 2^p registers.',
    },
    {
      id: 'hll-q4',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'At p=14, HyperLogLog uses about ___ KB of memory with roughly 2% relative error.',
      correct: ['1.5', '1.5kb', '1.5 kb'],
      aliases: ['1.5KB', '1-2', '2'],
      explanation: 'Typical p=10–14 uses 1.5 KB–24 KB. The chapter highlights ~1.5 KB at p=14.',
    },
    {
      id: 'hll-q5',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'When should you use HyperLogLog? (Select all that apply)',
      options: [
        { id: 'a', text: 'Approximate unique visitor counts at web scale' },
        { id: 'b', text: 'Exact billing amounts requiring 100% precision' },
        { id: 'c', text: 'Merging cardinality estimates across distributed nodes' },
        { id: 'd', text: 'Counting how many times each IP appeared in a stream' },
      ],
      correct: ['a', 'c'],
      explanation: 'HLL excels at approximate distinct counts and merge (PFMERGE). Billing needs exact counts; per-item frequency needs Count-Min Sketch.',
    },
    {
      id: 'hll-q6',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Your site has billions of page views per day. You need "unique visitors today" with minimal memory. Best approach?',
      options: [
        { id: 'a', text: 'HyperLogLog (e.g. Redis PFADD/PFCOUNT)' },
        { id: 'b', text: 'Store every user ID in a HashSet' },
        { id: 'c', text: 'Bloom filter' },
        { id: 'd', text: 'Sort all page views and deduplicate' },
      ],
      correct: ['a'],
      explanation: 'HashSet would use gigabytes for billions of uniques. HLL gives ~2% error with ~2 KB memory.',
    },
    {
      id: 'hll-q7',
      type: 'matching',
      difficulty: 'hard',
      question: 'Match each sketch or structure to what it answers.',
      pairs: [
        { id: '1', left: 'HyperLogLog', right: 'Cardinality (unique count)' },
        { id: '2', left: 'Count-Min Sketch', right: 'Frequency estimation' },
        { id: '3', left: 'Bloom Filter', right: 'Membership ("have I seen it?")' },
        { id: '4', left: 'HashSet', right: 'Exact distinct count (high memory)' },
      ],
      explanation: 'These probabilistic sketches are often used together — each answers a different streaming question.',
    },
    {
      id: 'hll-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'In the HyperLogLog Add operation, why is registers[idx] updated with Math.Max (only if rho is larger)?',
      code: `int rho = LeadingZeros(w) + 1;
if (rho > registers[idx]) {
    registers[idx] = rho;
}`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Each register tracks the maximum leading-zero run seen for its bucket — higher means more distinct items likely' },
        { id: 'b', text: 'Registers must always decrease to stay accurate' },
        { id: 'c', text: 'It prevents hash collisions entirely' },
        { id: 'd', text: 'It stores the exact count of items in that bucket' },
      ],
      correct: ['a'],
      explanation: 'Registers store the maximum observed ρ (leading zeros + 1). Estimate combines all registers via harmonic mean.',
    },
  ],
  challenges: [
    {
      id: 'hll-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Intuition check: you observe a hash with 10 leading zeros. Roughly how many distinct items have you likely seen?',
      options: [
        { id: 'a', text: 'About 2^10 ≈ 1,024' },
        { id: 'b', text: 'Exactly 10' },
        { id: 'c', text: 'About 10^10' },
        { id: 'd', text: 'About 2^32' },
      ],
      correct: ['a'],
      explanation: 'The chapter gives this intuition: 10 leading zeros → roughly 2^10 ≈ 1K distinct items.',
    },
    {
      id: 'hll-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'You need exact unique counts for financial audit compliance on 50M transactions. What do you use?',
      options: [
        { id: 'a', text: 'Exact HashSet or database DISTINCT — not HyperLogLog' },
        { id: 'b', text: 'HyperLogLog with p=14' },
        { id: 'c', text: 'Bloom filter' },
        { id: 'd', text: 'Count-Min Sketch' },
      ],
      correct: ['a'],
      explanation: 'The chapter explicitly says not to use HLL for financial, security, or billing where exact numbers are required.',
    },
  ],
} satisfies QuizPack