import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/23-graph',
  topicId: 'graph',
  title: 'Graph',
  quiz: [
    {
      id: 'graph-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What distinguishes a graph from a tree?',
      options: [
        { id: 'a', text: 'Graphs can have cycles; trees cannot' },
        { id: 'b', text: 'Graphs cannot have more than 100 nodes' },
        { id: 'c', text: 'Trees always use more memory' },
        { id: 'd', text: 'Graphs must be directed' },
      ],
      correct: ['a'],
      explanation: 'A tree is a connected acyclic graph. Graphs generalize to cycles and disconnected components.',
    },
    {
      id: 'graph-q2',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'Which are common graph representations? (Select all)',
      options: [
        { id: 'a', text: 'Adjacency list' },
        { id: 'b', text: 'Adjacency matrix' },
        { id: 'c', text: 'Hash map of hash maps' },
        { id: 'd', text: 'Sorted array only' },
      ],
      correct: ['a', 'b'],
      explanation: 'Adjacency list is space-efficient for sparse graphs; matrix is O(1) edge lookup for dense graphs.',
    },
    {
      id: 'graph-q3',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Space complexity of an adjacency matrix for V vertices:',
      options: [
        { id: 'a', text: 'O(V)' },
        { id: 'b', text: 'O(V + E)' },
        { id: 'c', text: 'O(V²)' },
        { id: 'd', text: 'O(E)' },
      ],
      correct: ['c'],
      explanation: 'V×V matrix stores every possible edge pair regardless of sparsity.',
    },
    {
      id: 'graph-q4',
      type: 'true-false',
      difficulty: 'easy',
      question: 'In an undirected graph, edge (A, B) implies edge (B, A).',
      correct: true,
      explanation: 'Undirected edges are bidirectional. Directed graphs have one-way edges.',
    },
    {
      id: 'graph-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Modeling a social network "friends" relationship (mutual friendship). Best graph type?',
      options: [
        { id: 'a', text: 'Undirected graph' },
        { id: 'b', text: 'Directed graph' },
        { id: 'c', text: 'DAG only' },
        { id: 'd', text: 'Tree only' },
      ],
      correct: ['a'],
      explanation: 'If A is friends with B, B is friends with A — undirected edge.',
    },
    {
      id: 'graph-q6',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'A graph with V vertices and E edges stored as an adjacency list uses O(___) space.',
      correct: ['V + E', 'v+e', 'V+E'],
      aliases: ['O(V+E)', 'o(v+e)'],
      explanation: 'One list entry per edge endpoint plus vertex array overhead.',
    },
    {
      id: 'graph-q7',
      type: 'matching',
      difficulty: 'easy',
      question: 'Match graph type to example:',
      pairs: [
        { id: '1', left: 'Directed acyclic graph (DAG)', right: 'Build dependencies / task scheduling' },
        { id: '2', left: 'Weighted graph', right: 'Road network with distances' },
        { id: '3', left: 'Bipartite graph', right: 'Job applicants ↔ job openings matching' },
      ],
      explanation: 'Different graph flavors model different real-world relationships.',
    },
    {
      id: 'graph-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What does this compute for an undirected graph?',
      code: `int degree = 0;
for (int v : adj[u]) degree++;
return degree;`,
      codeLang: 'pseudocode',
      options: [
        { id: 'a', text: 'Number of edges incident to vertex u' },
        { id: 'b', text: 'Shortest path length from u' },
        { id: 'c', text: 'Total edges in the graph' },
        { id: 'd', text: 'Whether the graph is connected' },
      ],
      correct: ['a'],
      explanation: 'Degree of a vertex = count of neighbors = incident edges in undirected graph.',
    },
  ],
  challenges: [
    {
      id: 'graph-c1',
      type: 'design',
      difficulty: 'medium',
      question: 'Sparse graph with 1M vertices, average degree 3. Which representation?',
      options: [
        { id: 'a', text: 'Adjacency list — O(V + E) ≈ 4M entries' },
        { id: 'b', text: 'Adjacency matrix — O(V²) ≈ 1 trillion entries' },
        { id: 'c', text: 'No representation needed' },
        { id: 'd', text: 'Sorted array of all pairs' },
      ],
      correct: ['a'],
      explanation: 'Sparse graphs blow up with matrices. Adjacency lists scale with actual edges.',
    },
    {
      id: 'graph-c2',
      type: 'trace',
      difficulty: 'hard',
      question: 'Directed graph: A→B, A→C, B→D, C→D. How many valid topological orderings include A first and D last?',
      options: [
        { id: 'a', text: '2 (A,B,C,D and A,C,B,D)' },
        { id: 'b', text: '1' },
        { id: 'c', text: '4' },
        { id: 'd', text: '0' },
      ],
      correct: ['a'],
      explanation: 'B and C are independent after A; both must precede D. Two orderings.',
    },
  ],
} satisfies QuizPack