import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/29-rope',
  topicId: 'rope',
  title: 'Rope',
  quiz: [
    {
      id: 'rope-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is a rope data structure?',
      options: [
        { id: 'a', text: 'A binary tree of string chunks for efficient large-string manipulation' },
        { id: 'b', text: 'A dynamic array with a gap around the cursor' },
        { id: 'c', text: 'A sorted array of all string suffixes' },
        { id: 'd', text: 'A 2D tree that partitions space into four quadrants' },
      ],
      correct: ['a'],
      explanation: 'Ropes split strings into chunks connected in a tree, avoiding O(n) copies on middle edits.',
    },
    {
      id: 'rope-q2',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Rope concatenation (Concat) can be performed in O(1) time by creating a new internal node.',
      correct: true,
      explanation: 'Concat creates a new node pointing to left and right subtrees — structural sharing without copying all characters.',
    },
    {
      id: 'rope-q3',
      type: 'complexity',
      difficulty: 'medium',
      question: 'What is the time complexity of Insert at an arbitrary position in a rope?',
      options: [
        { id: 'a', text: 'O(log n)' },
        { id: 'b', text: 'O(1)' },
        { id: 'c', text: 'O(n) always' },
        { id: 'd', text: 'O(n²)' },
      ],
      correct: ['a'],
      explanation: 'Insert uses Split (O(log n)) then Concat. Split and Delete are also O(log n).',
    },
    {
      id: 'rope-q4',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'Each internal rope node stores ___ — the total length of the string in its left subtree.',
      correct: ['weight', 'Weight'],
      aliases: ['left subtree length', 'left weight'],
      explanation: 'Weight lets Index and Split navigate the tree without visiting every leaf character.',
    },
    {
      id: 'rope-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: 'A text editor handles 10 MB+ files with frequent middle insertions/deletions. Best document buffer?',
      options: [
        { id: 'a', text: 'Rope (tree of string chunks)' },
        { id: 'b', text: 'Single contiguous char[] copied on every edit' },
        { id: 'c', text: 'Bloom filter' },
        { id: 'd', text: 'Suffix array rebuilt on every keystroke' },
      ],
      correct: ['a'],
      explanation: 'Ropes make arbitrary-position insert/delete O(log n) instead of O(n) for flat contiguous strings.',
    },
    {
      id: 'rope-q6',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'When do ropes become worth considering over StringBuilder/strings.Builder? (Select all)',
      options: [
        { id: 'a', text: 'Tens or hundreds of megabytes of text' },
        { id: 'b', text: 'Many middle insertions and deletions' },
        { id: 'c', text: 'Need for structural sharing (immutability)' },
        { id: 'd', text: 'Short strings with only append-at-end operations' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'For normal short strings with append-only patterns, StringBuilder is usually sufficient.',
    },
    {
      id: 'rope-q7',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'How does Index(i) locate character i in the rope?',
      code: `if (Left == null && Right == null) return Value[i];
if (i < Weight) return Left!.Index(i);
return Right!.Index(i - Weight);`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'At leaves, direct access; at internal nodes, go left if i < Weight, else right with adjusted index' },
        { id: 'b', text: 'Always scans every leaf from left to right in O(n)' },
        { id: 'c', text: 'Binary searches the alphabet at each node' },
        { id: 'd', text: 'Uses a gap buffer internally at every node' },
      ],
      correct: ['a'],
      explanation: 'Weight guides tree traversal: left subtree covers indices [0, Weight), right covers [Weight, end).',
    },
    {
      id: 'rope-q8',
      type: 'true-false',
      difficulty: 'hard',
      question: 'GCC\'s std::rope from the SGI STL extension is a well-known real-world rope implementation.',
      correct: true,
      explanation: 'The chapter cites GCC\'s std::rope as one of the most famous rope implementations in C++.',
    },
  ],
  challenges: [
    {
      id: 'rope-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Rope Insert(5, "XY") is called. What is the high-level algorithm?',
      options: [
        { id: 'a', text: 'Split at index 5, then Concat(left, new chunk, right)' },
        { id: 'b', text: 'Copy entire string, insert at position 5 in the copy' },
        { id: 'c', text: 'Move the gap to index 5 and write "XY"' },
        { id: 'd', text: 'Rebuild the suffix array after insertion' },
      ],
      correct: ['a'],
      explanation: 'Insert = Split(index) → Concat(Concat(left, FromString(text)), right).',
    },
    {
      id: 'rope-c2',
      type: 'variant',
      difficulty: 'hard',
      question: 'Normal typing in a small source file (< 100 KB) with cursor-local edits. Best structure?',
      options: [
        { id: 'a', text: 'Gap Buffer — simpler and exploits editing locality' },
        { id: 'b', text: 'Rope — always better regardless of size' },
        { id: 'c', text: 'Suffix array' },
        { id: 'd', text: 'Quadtree' },
      ],
      correct: ['a'],
      explanation: 'Gap buffers excel at cursor-local editing (Emacs-style). Ropes shine for very large files and non-local edits.',
    },
  ],
} satisfies QuizPack