import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/27-count-min-sketch',
  topicId: 'count-min-sketch',
  title: 'Count-Min Sketch',
  quiz: [
    {
      id: 'cms-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What question does a Count-Min Sketch answer?',
      options: [
        { id: 'a', text: 'Approximately how many times has item X appeared in a stream?' },
        { id: 'b', text: 'How many unique items exist in the stream?' },
        { id: 'c', text: 'Whether item X has ever been seen (yes/no only)' },
        { id: 'd', text: 'The exact top-k items in sorted order' },
      ],
      correct: ['a'],
      explanation: 'Count-Min Sketch estimates frequency counts with bounded error using very little memory.',
    },
    {
      id: 'cms-q2',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Count-Min Sketch queries take the minimum across all depth rows because collisions can only increase counters, never decrease them.',
      correct: true,
      explanation: 'Hash collisions inflate counters. The minimum across independent hash rows is the most trustworthy estimate.',
    },
    {
      id: 'cms-q3',
      type: 'complexity',
      difficulty: 'medium',
      question: 'For a Count-Min Sketch with width w and depth d, what is the time complexity of Add and Query?',
      options: [
        { id: 'a', text: 'O(d) for both' },
        { id: 'b', text: 'O(w) for both' },
        { id: 'c', text: 'O(w × d) for both' },
        { id: 'd', text: 'O(1) for both' },
      ],
      correct: ['a'],
      explanation: 'Each operation hashes the item with d hash functions and touches d counters — one per row.',
    },
    {
      id: 'cms-q4',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'To achieve error ≤ ε × total with probability ≥ 1 − δ, width w = ⌈___/ε⌉ and depth d = ⌈ln(1/δ)⌉.',
      correct: ['e', 'math.e', '2.718'],
      aliases: ['E', 'euler', 'eulers number'],
      explanation: 'Standard CMS sizing: w = ⌈e/ε⌉ and d = ⌈ln(1/δ)⌉.',
    },
    {
      id: 'cms-q5',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'Which are real-world uses of Count-Min Sketch? (Select all that apply)',
      options: [
        { id: 'a', text: 'Network traffic heavy-hitter detection' },
        { id: 'b', text: 'Stream processing in Flink/Kafka/Spark' },
        { id: 'c', text: 'TinyLFU cache admission frequency tracking' },
        { id: 'd', text: 'Exact financial ledger reconciliation' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'CMS is used for approximate frequency in networking, streaming analytics, and cache policies — not exact billing.',
    },
    {
      id: 'cms-q6',
      type: 'scenario',
      difficulty: 'medium',
      question: 'You process billions of click events and need "how many times did user X click?" without storing every user. Best fit?',
      options: [
        { id: 'a', text: 'Count-Min Sketch' },
        { id: 'b', text: 'HyperLogLog' },
        { id: 'c', text: 'Bloom filter' },
        { id: 'd', text: 'Suffix array' },
      ],
      correct: ['a'],
      explanation: 'Frequency estimation is exactly what CMS solves. HLL counts uniques; Bloom answers membership only.',
    },
    {
      id: 'cms-q7',
      type: 'matching',
      difficulty: 'hard',
      question: 'Match each probabilistic sketch to its primary question.',
      pairs: [
        { id: '1', left: 'HyperLogLog', right: 'How many unique items?' },
        { id: '2', left: 'Count-Min Sketch', right: 'How often did item X occur?' },
        { id: '3', left: 'Bloom Filter', right: 'Is item X possibly in the set?' },
        { id: '4', left: 'Cuckoo Filter', right: 'Is item X possibly in the set (with delete)?' },
      ],
      explanation: 'These sketches are complementary and often deployed together in analytics pipelines.',
    },
    {
      id: 'cms-q8',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'What does the Add method do for each item?',
      code: `for (int i = 0; i < depth; i++) {
    int col = Hash(item, i) % width;
    table[i, col] += count;
}`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Increments one counter in each of the d rows at the hashed column' },
        { id: 'b', text: 'Increments only the single counter with the minimum value' },
        { id: 'c', text: 'Sets bits in a bit array' },
        { id: 'd', text: 'Stores the exact count in a hash map' },
      ],
      correct: ['a'],
      explanation: 'Add hashes the item d times (different seeds) and increments the corresponding counter in each row.',
    },
  ],
  challenges: [
    {
      id: 'cms-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Row counters for item X after adds: [47, 52, 45, 49]. True count is 45. What does Estimate return?',
      options: [
        { id: 'a', text: '45 (the minimum)' },
        { id: 'b', text: '49 (the maximum)' },
        { id: 'c', text: '48 (the average)' },
        { id: 'd', text: '193 (the sum)' },
      ],
      correct: ['a'],
      explanation: 'Estimate takes Math.Min across all depth rows. Collisions only inflate values, so minimum is best.',
    },
    {
      id: 'cms-c2',
      type: 'variant',
      difficulty: 'hard',
      question: 'You need per-URL view counts for 10M unique URLs with guaranteed zero error. Which structure?',
      options: [
        { id: 'a', text: 'Exact hash map (URL → count) — not Count-Min Sketch' },
        { id: 'b', text: 'Count-Min Sketch with ε=0.001' },
        { id: 'c', text: 'HyperLogLog' },
        { id: 'd', text: 'Bloom filter' },
      ],
      correct: ['a'],
      explanation: 'CMS gives approximate counts with bounded error. Guaranteed exact counts require exact storage (hash map / DB).',
    },
  ],
} satisfies QuizPack