import type { QuizPack } from '../types'

export default {
  pagePath: '/data-structures/33-kd-tree',
  topicId: 'kd-tree',
  title: 'KD Tree',
  quiz: [
    {
      id: 'kdt-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'How does a KD-tree split space in 2D?',
      options: [
        { id: 'a', text: 'Alternates splitting on X and Y axes at each level' },
        { id: 'b', text: 'Always splits into four quadrants' },
        { id: 'c', text: 'Splits only on the Y axis' },
        { id: 'd', text: 'Uses minimum bounding rectangles at each node' },
      ],
      correct: ['a'],
      explanation: 'KD-trees cycle through dimensions: level 0 splits on X, level 1 on Y, level 2 on X again, etc.',
    },
    {
      id: 'kdt-q2',
      type: 'true-false',
      difficulty: 'easy',
      question: 'KD-trees suffer from the curse of dimensionality — performance degrades badly in high dimensions.',
      correct: true,
      explanation: 'KD-trees work well for k ≤ 10–20. In high dimensions, pruning becomes ineffective and performance approaches O(n).',
    },
    {
      id: 'kdt-q3',
      type: 'complexity',
      difficulty: 'medium',
      question: 'In low dimensions, what is the average-case time for nearest-neighbor search in a KD-tree?',
      options: [
        { id: 'a', text: 'O(log n)' },
        { id: 'b', text: 'O(1)' },
        { id: 'c', text: 'O(n²)' },
        { id: 'd', text: 'O(n log² n)' },
      ],
      correct: ['a'],
      explanation: 'Average nearest-neighbor is O(log n) in low dimensions, though worst case can be O(n).',
    },
    {
      id: 'kdt-q4',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'Building a KD-tree from n points takes O(n ___ n) time.',
      correct: ['log'],
      aliases: ['log n', 'logn'],
      explanation: 'Build recursively sorts and splits — O(n log n) average and worst case for n points.',
    },
    {
      id: 'kdt-q5',
      type: 'scenario',
      difficulty: 'medium',
      question: '"Find the 5 closest restaurants to this GPS coordinate." Best spatial structure for point data in 2D?',
      options: [
        { id: 'a', text: 'KD-tree' },
        { id: 'b', text: 'Suffix array' },
        { id: 'c', text: 'HyperLogLog' },
        { id: 'd', text: 'Gap buffer' },
      ],
      correct: ['a'],
      explanation: 'KD-trees excel at nearest-neighbor queries in low-dimensional spaces — common in location services and KNN ML.',
    },
    {
      id: 'kdt-q6',
      type: 'matching',
      difficulty: 'hard',
      question: 'Match each spatial structure to its best use case.',
      pairs: [
        { id: '1', left: 'Quadtree', right: 'Uniform 2D partitioning, range queries' },
        { id: '2', left: 'R-tree', right: 'Rectangles, disk-based spatial indexes' },
        { id: '3', left: 'KD-tree', right: 'Point nearest-neighbor in low dimensions' },
        { id: '4', left: 'Count-Min Sketch', right: 'Stream frequency estimation' },
      ],
      explanation: 'Each spatial structure targets different data shapes and query types.',
    },
    {
      id: 'kdt-q7',
      type: 'code-analysis',
      difficulty: 'hard',
      question: 'When does nearest-neighbor search explore the "far" subtree?',
      code: `SearchNearest(near, target, ref best, ref bestDist);
if (diff * diff < bestDist) {
    SearchNearest(far, target, ref best, ref bestDist);
}`,
      codeLang: 'csharp',
      options: [
        { id: 'a', text: 'Only when the splitting plane is closer than the current best distance — otherwise the far side can be pruned' },
        { id: 'b', text: 'Always explores both subtrees completely' },
        { id: 'c', text: 'Never explores the far subtree' },
        { id: 'd', text: 'Only when the tree has exactly two nodes' },
      ],
      correct: ['a'],
      explanation: 'If diff² < bestDist, a closer point might exist on the far side of the split. Otherwise, prune the far subtree.',
    },
    {
      id: 'kdt-q8',
      type: 'mcq-multi',
      difficulty: 'medium',
      question: 'Which are weaknesses of KD-trees? (Select all)',
      options: [
        { id: 'a', text: 'Poor performance in high dimensions' },
        { id: 'b', text: 'Most implementations are static — not great for frequent updates' },
        { id: 'c', text: 'Nearest neighbor can degenerate to O(n) worst case' },
        { id: 'd', text: 'Cannot answer range queries at all' },
      ],
      correct: ['a', 'b', 'c'],
      explanation: 'KD-trees can answer range queries but degrade in high dimensions, resist dynamic updates, and have O(n) worst-case NN.',
    },
  ],
  challenges: [
    {
      id: 'kdt-c1',
      type: 'trace',
      difficulty: 'medium',
      question: 'Building a 2D KD-tree: at depth 0, 2, 4... which axis is used for splitting?',
      options: [
        { id: 'a', text: 'X axis (axis = depth % 2 == 0)' },
        { id: 'b', text: 'Y axis always' },
        { id: 'c', text: 'The axis with the most points' },
        { id: 'd', text: 'Random axis each level' },
      ],
      correct: ['a'],
      explanation: 'axis = depth % 2: even depths split on X (0), odd depths split on Y (1).',
    },
    {
      id: 'kdt-c2',
      type: 'design',
      difficulty: 'hard',
      question: 'You index millions of map feature bounding boxes for PostGIS-style range queries. Best structure?',
      options: [
        { id: 'a', text: 'R-tree — designed for rectangles/MBRs in spatial databases' },
        { id: 'b', text: 'KD-tree — always best for any spatial data' },
        { id: 'c', text: 'Cuckoo filter' },
        { id: 'd', text: 'Suffix array' },
      ],
      correct: ['a'],
      explanation: 'R-trees index rectangles/MBRs for production spatial DBs. KD-trees target point nearest-neighbor in low dimensions.',
    },
  ],
} satisfies QuizPack