import type { QuizPack } from '../types'

export default {
  pagePath: '/fundamentals/00-what-is-an-algorithm',
  topicId: 'what-is-algo',
  title: 'What is an Algorithm?',
  quiz: [
    {
      id: 'wialg-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is an algorithm in software terms?',
      options: [
        { id: 'a', text: 'A precise step-by-step recipe a computer follows to turn input into desired output' },
        { id: 'b', text: 'Only code that runs on a GPU' },
        { id: 'c', text: 'A database index stored on disk' },
        { id: 'd', text: 'The name of a programming language feature' },
      ],
      correct: ['a'],
      explanation: 'An algorithm is a recipe — it need not be code (IKEA instructions count), but in software it must be exact enough for a machine to execute.',
    },
    {
      id: 'wialg-q2',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Algorithmic thinking means memorizing dozens of named algorithms before writing any code.',
      correct: false,
      explanation: 'The real skill is defining the problem, breaking it down, choosing tools, analyzing cost, and implementing correctly — not rote memorization.',
      misconception: 'Engineers ask about correctness, constraints, and whether work can be avoided before typing loops.',
    },
    {
      id: 'wialg-q3',
      type: 'scenario',
      difficulty: 'medium',
      question: 'Two Crystal Balls, 100-story building: you must find the lowest floor where a ball breaks. You have exactly 2 balls and want to minimize worst-case drops. Why is pure binary search not automatically optimal?',
      options: [
        { id: 'a', text: 'Binary search needs infinite balls; with 2 balls a bad first break can force a long linear scan below' },
        { id: 'b', text: 'Binary search only works on sorted arrays, not buildings' },
        { id: 'c', text: 'The balls are too heavy for binary search' },
        { id: 'd', text: 'Worst case for binary search is always 100 drops' },
      ],
      correct: ['a'],
      explanation: 'Constraints change the optimal strategy. With only 2 balls, one ball narrows the range via jumps; the second does linear search in the danger zone — roughly 14 worst-case drops, not naive 100.',
      misconception: 'The best algorithm depends on constraints, not just the problem name.',
    },
    {
      id: 'wialg-q4',
      type: 'complexity',
      difficulty: 'medium',
      question: 'Find duplicates in 100k items. Naive: compare every pair. Algorithmic thinking with a hash set gives:',
      options: [
        { id: 'a', text: 'O(n) time, O(n) extra space' },
        { id: 'b', text: 'O(n²) time, O(1) space' },
        { id: 'c', text: 'O(log n) time, O(n) space' },
        { id: 'd', text: 'O(n!) time, O(1) space' },
      ],
      correct: ['a'],
      explanation: 'Trade memory for time: one pass, track seen items in a set — O(n) time. Multiple correct answers exist (sort then scan is O(n log n)), but the chapter highlights the set approach.',
    },
    {
      id: 'wialg-q5',
      type: 'ordering',
      difficulty: 'easy',
      question: 'Order the algorithmic thinking checklist as the chapter presents it (first step at top):',
      items: [
        { id: 'a', text: 'What is the actual goal (not just the literal task)?' },
        { id: 'b', text: 'What does the input look like — size, sorted, duplicates?' },
        { id: 'c', text: 'What operations must be fast?' },
        { id: 'd', text: 'What are my real constraints (memory, latency, scale)?' },
      ],
      correct: ['a', 'b', 'c', 'd'],
      explanation: 'Clarify the goal, understand input, identify hot operations, then weigh constraints before optimizing.',
    },
    {
      id: 'wialg-q6',
      type: 'matching',
      difficulty: 'medium',
      question: 'Match each real-world tool behavior to the algorithm family behind it:',
      pairs: [
        { id: '1', left: 'git bisect finding a bad commit', right: 'Binary search' },
        { id: '2', left: 'npm resolving install order from dependencies', right: 'Topological sort' },
        { id: '3', left: 'Browser cache evicting least-recently-used pages', right: 'LRU cache eviction' },
      ],
      explanation: 'Algorithms are embedded in tools you use daily — recognizing them builds algorithmic intuition.',
    },
    {
      id: 'wialg-q7',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'For the Two Crystal Balls problem on 100 floors, the optimal worst-case strategy uses roughly ___ drops (solve x(x+1)/2 ≥ 100).',
      correct: ['14', 'fourteen'],
      aliases: ['~14', 'about 14'],
      explanation: 'With 2 balls and x drops, you can cover x(x+1)/2 floors. Solving x(x+1)/2 ≥ 100 gives x ≈ 14 — decreasing jump sizes, not floor-by-floor linear search.',
      misconception: 'One ball forces up to 100 drops; two balls enable a jump-then-linear strategy.',
    },
    {
      id: 'wialg-q8',
      type: 'mcq',
      difficulty: 'hard',
      question: 'Which pair correctly contrasts data structures and algorithms from the chapter?',
      options: [
        { id: 'a', text: 'Data structure = organization + speed promises; Algorithm = recipe using structures to produce answers' },
        { id: 'b', text: 'Data structure = loops; Algorithm = variables' },
        { id: 'c', text: 'Data structure = always O(1); Algorithm = always O(n)' },
        { id: 'd', text: 'Data structure = correctness proof; Algorithm = memory layout only' },
      ],
      correct: ['a'],
      explanation: 'Structures define how data is stored and what is fast; algorithms are the step-by-step procedures that operate on that data.',
    },
  ],
  challenges: [
    {
      id: 'wialg-c1',
      type: 'trace',
      difficulty: 'hard',
      question: 'Two Crystal Balls: first ball drops at floors 14, 27, 39, 50… (decreasing jump sizes). It breaks at floor 50. How do you use the second ball in the worst case?',
      options: [
        { id: 'a', text: 'Linear search from floor 40 up to 49 (previous safe jump floor + 1)' },
        { id: 'b', text: 'Binary search between floors 1 and 100' },
        { id: 'c', text: 'Drop from floor 100 downward only' },
        { id: 'd', text: 'Give up — two balls cannot beat linear search' },
      ],
      correct: ['a'],
      explanation: 'After the first ball breaks at 50, the breaking floor is in the interval just above the last safe jump (39) up to 49. The second ball checks linearly — at most ~13 drops in that window, keeping total worst case near 14.',
    },
    {
      id: 'wialg-c2',
      type: 'design',
      difficulty: 'medium',
      question: 'You must show the top 10 newest items from a stream of millions. A teammate says "sort the entire stream." What is the algorithmic-thinking response?',
      options: [
        { id: 'a', text: 'Clarify the goal — you may only need a heap or partial sort of the newest 10, not full O(n log n) sort of millions' },
        { id: 'b', text: 'Always sort everything — that is the only correct approach' },
        { id: 'c', text: 'Use nested loops comparing every pair — simpler code' },
        { id: 'd', text: 'Skip analysis — optimize after shipping' },
      ],
      correct: ['a'],
      explanation: 'Step 1 of algorithmic thinking: what is the actual goal? "Top 10 newest" often means a bounded structure (heap, partial selection) — not sorting the entire stream.',
    },
  ],
} satisfies QuizPack