import type { QuizPack } from '../types'

export default {
  pagePath: '/fundamentals/00-what-is-a-data-structure',
  topicId: 'what-is-ds',
  title: 'What is a Data Structure?',
  quiz: [
    {
      id: 'wids-q1',
      type: 'mcq',
      difficulty: 'easy',
      question: 'According to the chapter, a data structure is best defined as:',
      options: [
        { id: 'a', text: 'Organized storage + rules for access/change + performance characteristics' },
        { id: 'b', text: 'Any variable declared in a program' },
        { id: 'c', text: 'A SQL table schema only' },
        { id: 'd', text: 'The number of bytes used by a file on disk' },
      ],
      correct: ['a'],
      explanation: 'A data structure is not just a container — it is storage, the operations you can perform, and the guarantees about how fast those operations are.',
      misconception: 'Lists and maps are not just names; they are contracts about time and memory.',
    },
    {
      id: 'wids-q2',
      type: 'true-false',
      difficulty: 'easy',
      question: 'There is almost always one universally "best" data structure for every problem.',
      correct: false,
      explanation: 'Every structure trades something for something else — fast lookup may cost extra memory, fast insert at the front may cost slow random access.',
      misconception: 'The right choice depends on which operations must be fast and at what scale.',
    },
    {
      id: 'wids-q3',
      type: 'scenario',
      difficulty: 'medium',
      question: 'You need O(1) lookup of users by ID for 10 million records, and insertion order does not matter. Which choice fits best?',
      options: [
        { id: 'a', text: 'List<User> — scan until you find the ID' },
        { id: 'b', text: 'Dictionary<int, User> / map[int]User — hash map' },
        { id: 'c', text: 'LinkedList<User> — traverse from head' },
        { id: 'd', text: 'Sorted array only — no index structure' },
      ],
      correct: ['b'],
      explanation: 'Hash maps trade extra memory and lack of sorted order for average O(1) key lookup — exactly the promise you need at scale.',
      misconception: 'A List scan is O(n) per lookup; 10M users makes that unusable for hot paths.',
    },
    {
      id: 'wids-q4',
      type: 'matching',
      difficulty: 'medium',
      question: 'Match each everyday .NET / Go choice to its underlying structure:',
      pairs: [
        { id: '1', left: 'List<T> / Go slice', right: 'Dynamic array' },
        { id: '2', left: 'Dictionary<K,V> / Go map', right: 'Hash map' },
        { id: '3', left: 'Queue<T> with capacity limit', right: 'Queue (FIFO)' },
      ],
      explanation: 'These daily API choices are data structure decisions — each comes with different performance promises.',
    },
    {
      id: 'wids-q5',
      type: 'fill-blank',
      difficulty: 'medium',
      question: 'In a sorted array, elements must always stay in order — this rule is called an ___.',
      correct: ['invariant', 'invariants'],
      aliases: ['structural invariant', 'data invariant'],
      explanation: 'Invariants are rules that must always hold. Break them and the structure stops being useful (e.g., binary search on an unsorted array).',
    },
    {
      id: 'wids-q6',
      type: 'ordering',
      difficulty: 'medium',
      question: 'Order these steps when choosing a data structure (first question at top):',
      items: [
        { id: 'a', text: 'What operations must be fast?' },
        { id: 'b', text: 'How much data will I store?' },
        { id: 'c', text: 'Do I need a specific order (sorted, insertion, none)?' },
        { id: 'd', text: 'What is my memory and concurrency budget?' },
      ],
      correct: ['a', 'b', 'c', 'd'],
      explanation: 'Start with required operations, then scale, then ordering needs, then resource constraints — the chapter\'s decision checklist.',
    },
    {
      id: 'wids-q7',
      type: 'scenario',
      difficulty: 'hard',
      question: 'Rate limiting: track the last 1000 request IDs per user and check if a specific ID was seen recently. Worst approach vs better approach?',
      options: [
        { id: 'a', text: 'List + linear scan each check — good at scale' },
        { id: 'b', text: 'HashSet for O(1) membership + Queue/ring buffer to evict old IDs' },
        { id: 'c', text: 'Nested loops comparing every pair of requests' },
        { id: 'd', text: 'Single global string concatenation of all IDs' },
      ],
      correct: ['b'],
      explanation: 'HashSet gives O(1) "was this ID seen?" while a Queue or ring buffer evicts entries beyond 1000 — the chapter\'s rate-limiting example.',
      misconception: 'Scanning a List on every check is O(n) and melts under load.',
    },
    {
      id: 'wids-q8',
      type: 'mcq',
      difficulty: 'medium',
      question: 'You need fast min/max extraction and can accept slower arbitrary inserts. Which structure fits the tradeoff table?',
      options: [
        { id: 'a', text: 'Hash map' },
        { id: 'b', text: 'Doubly linked list' },
        { id: 'c', text: 'Heap / Priority Queue' },
        { id: 'd', text: 'Unsorted dynamic array only' },
      ],
      correct: ['c'],
      explanation: 'Heaps promise fast min/max (and extract-min/max) at the cost of more complex inserts — a classic tradeoff from the chapter table.',
    },
  ],
  challenges: [
    {
      id: 'wids-c1',
      type: 'design',
      difficulty: 'hard',
      question: 'A product needs range queries: "total sales between Jan 1 and Mar 31" on billions of rows. Which real-world index family does the chapter point to?',
      options: [
        { id: 'a', text: 'Hash set only — O(1) point lookup covers ranges' },
        { id: 'b', text: 'B+ tree / segment tree style structures for ordered range access' },
        { id: 'c', text: 'Singly linked list scanned from head each query' },
        { id: 'd', text: 'Stack — LIFO is ideal for date ranges' },
      ],
      correct: ['b'],
      explanation: 'Range queries need ordered storage or specialized trees (B+ trees in databases, segment trees for aggregates) — hash maps do not preserve order for ranges.',
    },
    {
      id: 'wids-c2',
      type: 'variant',
      difficulty: 'medium',
      question: 'When you pick Dictionary over List for GetById, what "promise" are you making to your team?',
      options: [
        { id: 'a', text: 'GetById(id) will be fast at the cost of extra memory and no sorted iteration' },
        { id: 'b', text: 'Elements will always stay in insertion order with zero overhead' },
        { id: 'c', text: 'Memory usage will always be lower than a plain array' },
        { id: 'd', text: 'Every operation on the collection is O(1)' },
      ],
      correct: ['a'],
      explanation: 'Data structures are promises about performance. A hash map promises fast key lookup; you pay with memory and typically lose sorted order.',
      misconception: 'No single structure makes every operation O(1).',
    },
  ],
} satisfies QuizPack